# https://crontab.guru/ ตั้งเวลา
services:
  php:
    container_name: ${CONTAINER_NAME}
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
    ports:
      - '${HOS_CODE}:80'
    links:
      - mysqlDB:db
    env_file:
      - ./.env

  mysqlDB:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME}_db
    hostname: mysqldboffice
    
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
    command:
      [
        # 'RUN echo "memory_limit = 2048M" >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;',
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
      ]

    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./docker/mysql5.7/data:/var/lib/mysql
      - ./docker/mysql5.7/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin_mysql:
    image: phpmyadmin
    container_name: ${CONTAINER_NAME}_pma
    restart: always
    links:
      - mysqlDB:db
    ports:
      - ${PAM_PORT}:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mysqlDB
      UPLOAD_LIMIT: 300M

  data-backup:
    container_name: ${CONTAINER_NAME}_backup
    image: tiredofit/db-backup
    volumes:
      - ./db-backup:/backup
      - ./:/home/app
      # - ./post-script.sh:/assets/custom-scripts/post-script.sh
      - ./post-script.sh:/assets/scripts/post/post-script.sh
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=Asia/bangkok
      - CONTAINER_NAME=data-backup
      - CONTAINER_ENABLE_MONITORING=TRUE
      - DEBUG_MODE=TRUE
      - DB01_SCRIPT_LOCATION_POST=TRUE

      - BACKUP_JOB_CONCURRENCY=1     # Only run one job at a time
      - DEFAULT_CHECKSUM=NONE        # Don't create checksums
      - DEFAULT_BACKUP_INTERVAL=1440   # Backup every 1440 minutes
      - DEFAULT_BACKUP_BEGIN=0000      # Start backing up at midnight
      - DEFAULT_CLEANUP_TIME=8640    # Cleanup backups after a week

      - DB01_TYPE=mysql
      - DB01_HOST=mysqlDB
      - DB01_NAME=dansai
      - DB01_USER=root
      - DB01_PASS=docker
      - DB01_BACKUP_INTERVAL=30        # (override) Backup every 30 minutes
      - DB01_BACKUP_BEGIN=+1           # (override) Backup starts immediately
      - DB01_CLEANUP_TIME=180        # (override) Cleanup backups they are older than 180 minutes
      # - DB01_CHECKSUM=SHA1           # (override) Create a SHA1 checksum
      - DB01_COMPRESSION=GZ          # (override) Compress with GZIP


    restart: always

  # mysqlbackup:
  #   image: selim13/automysqlbackup:2.6-9
  #   volumes:
  #     - "./docker/backup:/backup"
  #   environment:
  #     USERNAME: root
  #     PASSWORD: "docker"
  #     DBNAMES: ${CONTAINER_NAME}
  #     DBHOST: mysqlDB
  #     DBEXCLUDE: "performance_schema information_schema"
  #     # CRON_SCHEDULE: "*/2 * * * *"
  #     CRON_SCHEDULE: "0 0 * * *" 
  #     EXTRA_OPTS: "--single-transaction"
  #   depends_on:
  #     - mysqlDB
