# https://crontab.guru/ ตั้งเวลา
services:
  php:
    container_name: ${CONTAINER_NAME}
    image: yiisoftware/yii2-php:8.2-apache
    environment:
      PHP_MEMORY_LIMIT: 2048M
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
    ports:
      - "${HOS_CODE}:80"
    links:
      - mysqlDB:db
    env_file:
      - ./.env

  mysqlDB:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}_db
    hostname: mysqldboffice

    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
    command:
      [
        "mysqld",
        "--innodb-buffer-pool-size=1G",
        "--innodb-log-file-size=256M",
        "--innodb-flush-log-at-trx-commit=2",
        "--innodb-flush-method=O_DIRECT",
        "--tmp_table_size=64M",
        "--max-heap-table-size=64M",
        "--max-connections=200",
        "--table-open-cache=400",
        "--max-allowed-packet=64M",
        "--wait_timeout=28800",
        "--interactive_timeout=28800",
        "--character-set-server=utf8",
        "--collation-server=utf8_general_ci",
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
      ]

    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql8.0/data:/var/lib/mysql
      # - ./docker/mysql_dansai8.0/data:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/mysql5.7/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin_mysql:
    image: phpmyadmin
    container_name: ${CONTAINER_NAME}_pma
    restart: always
    links:
      - mysqlDB:db
    ports:
      - ${PAM_PORT}:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mysqlDB
      UPLOAD_LIMIT: 300M
