$data = [
                ['title' => 'AIR WAY 60 mm. No.0', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 70 mm. No.1', 'unit' => 'อัน', 'qty' => '69', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 80 mm. No.2', 'unit' => 'อัน', 'qty' => '6', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 90 mm. No.3', 'unit' => 'อัน', 'qty' => '30', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 100 mm. No.4', 'unit' => 'อัน', 'qty' => '25', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 110 mm. No.5', 'unit' => 'อัน', 'qty' => '34', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 120 mm. No.6', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 20.00],
                ['title' => 'AIR WAY 130 mm. No.7', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 20.00],
                ['title' => 'Arm SLING No. S', 'unit' => 'อัน', 'qty' => '7', 'unit_price' => 32.10],
                ['title' => 'Arm SLING No. M', 'unit' => 'อัน', 'qty' => '10', 'unit_price' => 32.10],
                ['title' => 'Arm SLING No. L', 'unit' => 'อัน', 'qty' => '17', 'unit_price' => 32.10],
                ['title' => 'Arm SLING No. XL', 'unit' => 'อัน', 'qty' => '-50', 'unit_price' => 32.10],
                ['title' => 'Arm SLING No. เด็กหญิง,เด็กชาย', 'unit' => 'อัน', 'qty' => '8', 'unit_price' => 32.10],
                ['title' => 'AUTOCLAVE TAPE 1/2"', 'unit' => 'ม้วน', 'qty' => '72', 'unit_price' => 176.55],
                ['title' => 'AUTOCLAVE TAPE 1/2"', 'unit' => 'ม้วน', 'qty' => '9', 'unit_price' => 0.00],
                ['title' => 'BLOOD SET', 'unit' => 'ชุด', 'qty' => '30', 'unit_price' => 30.00],
                ['title' => 'BP CUFF เด็กเล็ก', 'unit' => 'ชุด', 'qty' => '0', 'unit_price' => 330.00],
                ['title' => 'BP CUFF เด็กโต', 'unit' => 'ชุด', 'qty' => '8', 'unit_price' => 330.00],
                ['title' => 'BP CUFF ผู้ใหญ่', 'unit' => 'ชุด', 'qty' => '5', 'unit_price' => 330.00],
                ['title' => 'BP Cuff Digital Weich Allene N0.10 (เด็ก)', 'unit' => 'ชุด', 'qty' => '1', 'unit_price' => 1200.00],
                ['title' => 'BP Cuff Digital Weich Allene N0.11', 'unit' => 'ชุด', 'qty' => '13', 'unit_price' => 1200.00],
                ['title' => 'BP Cuff Digital Weich Allene N0.13', 'unit' => 'ชุด', 'qty' => '2', 'unit_price' => 1200.00],
                ['title' => 'BP Cuff Digital Weich Allene N0.13(วัดต้นขา)', 'unit' => 'ชุด', 'qty' => '2', 'unit_price' => 1200.00],
                ['title' => 'Bacteria friter', 'unit' => 'ชุด', 'qty' => '50', 'unit_price' => 48.00],
                ['title' => 'BREAST PUMP', 'unit' => 'โหล', 'qty' => '36', 'unit_price' => 520.00],
                ['title' => 'BOWIEDICK TEST', 'unit' => 'ชุด', 'qty' => '24', 'unit_price' => 110.00],
                ['title' => 'CUTTING 1/2 CIRCLE NO 24', 'unit' => 'โหล', 'qty' => '5', 'unit_price' => 230.00],
                ['title' => 'CUTTING 1/2 CIRCLE No. 28', 'unit' => 'โหล', 'qty' => '5', 'unit_price' => 230.00],
                ['title' => 'CUTTING 1/2 CIRCLE No. 32', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 230.00],
                ['title' => 'CUTTING 1/2 CIRCLE No. 36', 'unit' => 'โหล', 'qty' => '5', 'unit_price' => 230.00],
                ['title' => 'CUTTING 1/2 CIRCLE No. 55', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 220.00],
                ['title' => 'CLAVICLE TRACTION No. SS', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 150.00],
                ['title' => 'CLAVICLE TRACTION No. S', 'unit' => 'อัน', 'qty' => '7', 'unit_price' => 150.00],
                ['title' => 'CLAVICLE TRACTION No. M', 'unit' => 'อัน', 'qty' => '8', 'unit_price' => 150.00],
                ['title' => 'CLAVICLE TRACTION No. L', 'unit' => 'อัน', 'qty' => '4', 'unit_price' => 150.00],
                ['title' => 'CLAVICLE TRACTION No. XL', 'unit' => 'อัน', 'qty' => '7', 'unit_price' => 150.00],
                ['title' => 'CHROMIC CATGUT No 0 ติดเข็ม 30', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 950.00],
                ['title' => 'CHROMIC CATGUT No 0 ไม่ติดเข็ม', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 950.00],
                ['title' => 'CHROMIC CATGUT No. 2/0 ติดเข็ม26', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 950.00],
                ['title' => 'CHROMIC CATGUT No. 2/0', 'unit' => 'โหล', 'qty' => '8', 'unit_price' => 950.00],
                ['title' => 'CHROMIC CATGUT No. 3/0 ติดเข็ม22', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 950.00],
                ['title' => 'CHROMIC CATGUT No. 4/0 ติดเข็ม22', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 950.00],
                ['title' => 'COLOSTOMY BAG', 'unit' => 'อัน(50/กล่อง)', 'qty' => '300', 'unit_price' => 9.00],
                ['title' => 'CRUSH No. 40"', 'unit' => 'คู่', 'qty' => '7', 'unit_price' => 315.00],
                ['title' => 'CRUSH No. 48"', 'unit' => 'คู่', 'qty' => '4', 'unit_price' => 337.00],
                ['title' => 'CRUSH No. 50"', 'unit' => 'คู่', 'qty' => '3', 'unit_price' => 315.00],
                ['title' => 'CRUSH No. 52"', 'unit' => 'คู่', 'qty' => '0', 'unit_price' => 315.00],
                ['title' => 'Clamp โต้ง 14 cm.', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 800.00],
                ['title' => 'Clamp CVD 125 cm.', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 800.00],
                ['title' => 'Curetage wound', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 280.00],
                ['title' => 'Collugate Dispos.', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 790.00],
                ['title' => 'CPE (เอี้ยมฟ้าแขนยาว)', 'unit' => 'ชิ้น', 'qty' => '1000', 'unit_price' => 10.00],
                ['title' => 'DISPOS. NEEDLE No. 18*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '45', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 20*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '27', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 21*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '0', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 22*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '59', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 23*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '22', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 24*1.5"', 'unit' => 'กล่อง (100)', 'qty' => '20', 'unit_price' => 48.15],
                ['title' => 'DISPOS. NEEDLE No. 25*1"', 'unit' => 'กล่อง (100)', 'qty' => '90', 'unit_price' => 48.15],
                ['title' => 'DISPOS SPINAL NEEDLE No. 20', 'unit' => 'ชิ้น1*25', 'qty' => '0', 'unit_price' => 40.40],
                ['title' => 'DISPOS SPINAL NEEDLE No. 22', 'unit' => 'ชิ้น1*25', 'qty' => '10', 'unit_price' => 32.10],
                ['title' => 'DISPOS. SYRING 1 ML ถอดเข็ม26*1"', 'unit' => 'กล่อง (100)', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'DISPOS. SYRING 1 ML ถอดเข็ม26*1"(LDS)', 'unit' => 'ก.1*100', 'qty' => '352', 'unit_price' => 0.00],
                ['title' => 'DISPOS. SYRING 1 ML ไม่ติกเข็ม', 'unit' => 'ก.1*200', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'DISPOS. SYRING 1 ML ติดเข็ม', 'unit' => 'กล่อง (100)', 'qty' => '0', 'unit_price' => 227.91],
                ['title' => 'DISPOS. SYRING 1 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (100)', 'qty' => '0', 'unit_price' => 191.53],
                ['title' => 'DISPOS. SYRING 3 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (100)', 'qty' => '42', 'unit_price' => 115.56],
                ['title' => 'DISPOS. SYRING 5 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (100)', 'qty' => '19', 'unit_price' => 133.75],
                ['title' => 'DISPOS. SYRING 10 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (100)', 'qty' => '40', 'unit_price' => 203.30],
                ['title' => 'DISPOS. SYRING 20 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (1*100)', 'qty' => '33', 'unit_price' => 383.06],
                ['title' => 'DISPOS. SYRING 20 ML ไม่ติดเข็ม', 'unit' => 'กล่อง (50)', 'qty' => '0', 'unit_price' => 214.00],
                ['title' => 'DISPOS. SYRING 50 ML ไม่ติดเข็ม', 'unit' => '1ก.*(20)', 'qty' => '8', 'unit_price' => 331.61],
                ['title' => 'DEXON No. 0 ติดเข็ม', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 1700.00],
                ['title' => 'ELASTIC BANDAGE No. 2"', 'unit' => 'โหล', 'qty' => '9', 'unit_price' => 145.00],
                ['title' => 'ELASTIC BANDAGE No. 3"', 'unit' => 'โหล', 'qty' => '35', 'unit_price' => 180.00],
                ['title' => 'ELASTIC BANDAGE No. 4"', 'unit' => 'โหล', 'qty' => '9', 'unit_price' => 240.00],
                ['title' => 'ELASTIC BANDAGE No. 6"', 'unit' => 'โหล', 'qty' => '13', 'unit_price' => 360.00],
                ['title' => 'E- T TUBE No. 2.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '10', 'unit_price' => 30.00],
                ['title' => 'E- T TUBE No. 3.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '20', 'unit_price' => 30.00],
                ['title' => 'E- T TUBE No. 3.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '0', 'unit_price' => 30.00],
                ['title' => 'E- T TUBE No. 4.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '10', 'unit_price' => 30.00],
                ['title' => 'E- T TUBE No. 4.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '30', 'unit_price' => 30.00],
                ['title' => 'E- T TUBE No. 5.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '70', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 5.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '30', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 6.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '40', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 6.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '50', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 7.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '110', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 7.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '70', 'unit_price' => 40.00],
                ['title' => 'E- T TUBE No. 8.0', 'unit' => 'อัน(10/กล่อง)', 'qty' => '20', 'unit_price' => 50.00],
                ['title' => 'E- T TUBE No. 8.5', 'unit' => 'อัน(10/กล่อง)', 'qty' => '10', 'unit_price' => 50.00],
                ['title' => 'EXTENTION TUBE 42"', 'unit' => 'เส้น', 'qty' => '80', 'unit_price' => 5.80],
                ['title' => 'EYES PAD', 'unit' => 'ห่อ (50 ชิ้น)', 'qty' => '4', 'unit_price' => 150.00],
                ['title' => 'Ear Suction No. 6', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 1100.00],
                ['title' => 'Ear Suction No. 8', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 1100.00],
                ['title' => 'Electrode gel', 'unit' => 'หลอด', 'qty' => '4', 'unit_price' => 300.00],
                ['title' => 'FOLEY\'S CATHETER No. 8', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '20', 'unit_price' => 38.00],
                ['title' => 'FOLEY\'S CATHETER No. 10', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '10', 'unit_price' => 38.00],
                ['title' => 'FOLEY\'S CATHETER No. 12', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '0', 'unit_price' => 17.00],
                ['title' => 'FOLEY\'S CATHETER No. 14', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '40', 'unit_price' => 17.00],
                ['title' => 'FOLEY\'S CATHETER No. 16', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '60', 'unit_price' => 17.00],
                ['title' => 'FOLEY\'S CATHETER No. 18', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '20', 'unit_price' => 17.00],
                ['title' => 'FOLEY\'S CATHETER No. 20', 'unit' => 'เส้น(10/กล่อง)', 'qty' => '60', 'unit_price' => 17.00],
                ['title' => 'Foley Cath. 3 way No. 16', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 50.00],
                ['title' => 'Foley Cath 3. way No. 18', 'unit' => 'เส้น', 'qty' => '20', 'unit_price' => 50.00],
                ['title' => 'Foley Cath 3. way No. 20', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 50.00],
                ['title' => 'FINGER SPLINT 3/4"', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 310.00],
                ['title' => 'FINGER SPLINT 1/2"', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 310.00],
                ['title' => 'FINGER TIP', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 24.00],
                ['title' => 'Face Shield', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 550.00],
                ['title' => 'หน้ากาก Face Shield', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 120.00],
                ['title' => 'Face Shield Dispos.', 'unit' => 'อัน', 'qty' => '70', 'unit_price' => 25.00],
                ['title' => 'Forceps None-Tooth', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 170.00],
                ['title' => 'Forceps Tooth', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 180.00],
                ['title' => 'Gas แอทลีนออกไซด์', 'unit' => 'กระป๋อง', 'qty' => '2', 'unit_price' => 300.00],
                ['title' => 'Gauze 36 x 100 หลา (วชย.)', 'unit' => 'ม้วน', 'qty' => '7', 'unit_price' => 700.00],
                ['title' => 'Gauze Bandage(Conform)ยืด 3 นิ้ว(วชย.)', 'unit' => 'โหล', 'qty' => '244', 'unit_price' => 65.00],
                ['title' => 'Gauze พับ 3*8 (pack50ซอง)', 'unit' => 'ซอง(10แผ่น)', 'qty' => '3', 'unit_price' => 8.00],
                ['title' => 'GYPSONA 3"', 'unit' => 'กล่อง (24ชิ้น)', 'qty' => '0', 'unit_price' => 642.00],
                ['title' => 'GYPSONA 4"', 'unit' => 'กล่อง (24ชิ้น)', 'qty' => '0', 'unit_price' => 856.00],
                ['title' => 'GYPSONA 6"', 'unit' => 'กล่อง (24ชิ้น)', 'qty' => '2', 'unit_price' => 941.60],
                ['title' => 'Guild E-Tube No. S (Stylet)', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 220.00],
                ['title' => 'Guild E-Tube No. M (Stylet)', 'unit' => 'อัน', 'qty' => '5', 'unit_price' => 220.00],
                ['title' => 'Guild E-Tube No. L (Stylet)', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 220.00],
                ['title' => 'IV Set', 'unit' => 'Set(100/ห่อ)', 'qty' => '800', 'unit_price' => 9.63],
                ['title' => 'Knee Jerk', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 280.00],
                ['title' => 'LATEX Tube No. 200 (tuniquet)', 'unit' => 'ม้วน', 'qty' => '1', 'unit_price' => 320.00],
                ['title' => 'LATEX Tube No. 201 (สายยางแดง)', 'unit' => 'ม้วน', 'qty' => '5', 'unit_price' => 550.00],
                ['title' => 'LATEX Tube Selicone 7X12mm.(15 ม.)', 'unit' => 'ม้วน (15เมตร)', 'qty' => '0', 'unit_price' => 120.00],
                ['title' => 'LUMBAR SUPPORT Size S', 'unit' => 'อัน', 'qty' => '6', 'unit_price' => 280.00],
                ['title' => 'LUMBAR SUPPORT Size M', 'unit' => 'อัน', 'qty' => '1', 'unit_price' => 280.00],
                ['title' => 'LUMBAR SUPPORT Size L', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 280.00],
                ['title' => 'LUMBAR SUPPORT Size XL', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 280.00],
                ['title' => 'LUMBAR SUPPORT Size XXL', 'unit' => 'อัน', 'qty' => '3', 'unit_price' => 280.00],
                ['title' => 'MEDICUT No. 16', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '0', 'unit_price' => 10.38],
                ['title' => 'MEDICUT No. 18', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '180', 'unit_price' => 10.38],
                ['title' => 'MEDICUT No. 20', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '100', 'unit_price' => 10.38],
                ['title' => 'MEDICUT No. 22', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '200', 'unit_price' => 10.38],
                ['title' => 'MEDICUT No. 24', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '0', 'unit_price' => 10.38],
                ['title' => 'MEDICUT No. 26', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '30', 'unit_price' => 10.38],
                ['title' => 'MICRODRIP SET', 'unit' => 'ชุด', 'qty' => '125', 'unit_price' => 12.84],
                ['title' => 'MICROPORE 1/2"', 'unit' => 'ม้วน(24ม้วน)', 'qty' => '86', 'unit_price' => 14.16],
                ['title' => 'MICROPORE 1"', 'unit' => 'ม้วน (12ม้วน)', 'qty' => '32', 'unit_price' => 28.33],
                ['title' => 'MASK DIPOS.', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '59', 'unit_price' => 60.00],
                ['title' => 'MASK DIPOS.(สสจ.)', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'Mask N-95 (กล่องละ20ชิ้น)', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'Mask N-95 (บริจาค)', 'unit' => 'อัน', 'qty' => '2000', 'unit_price' => 0.00],
                ['title' => 'Mask N-95 สสจ.', 'unit' => 'อัน', 'qty' => '840', 'unit_price' => 0.00],
                ['title' => 'Mouth piece Adult (COPD Clinic)', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 60.00],
                ['title' => 'Neubulizer Mask Adult (ชุดพ่นยา)(วชย.)', 'unit' => '1 ชุด', 'qty' => '10', 'unit_price' => 50.00],
                ['title' => 'Neubulizer Mask Child (ชุดพ่นยา)(วชย.)', 'unit' => '1 ชุด', 'qty' => '60', 'unit_price' => 50.00],
                ['title' => 'Needdle Holder 13 cm.', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 400.00],
                ['title' => 'NYLON No. 2/0 ติดเข็ม 26', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 550.00],
                ['title' => 'NYLON No. 3/0 ติดเข็ม 24', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 550.00],
                ['title' => 'NYLON No. 4/0 ติดเข็ม 19', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 550.00],
                ['title' => 'NYLON No. 5/0 ติดเข็ม 16', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 550.00],
                ['title' => 'NG TUBE No. 5', 'unit' => 'เส้น', 'qty' => '85', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 6', 'unit' => 'เส้น', 'qty' => '16', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 8', 'unit' => 'เส้น', 'qty' => '57', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 10', 'unit' => 'เส้น', 'qty' => '30', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 12', 'unit' => 'เส้น', 'qty' => '85', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 14 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '72', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 16 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '10', 'unit_price' => 11.00],
                ['title' => 'NG TUBE No. 18 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '29', 'unit_price' => 11.00],
                ['title' => 'O2 CANNULAR 2 END', 'unit' => 'เส้น', 'qty' => '32', 'unit_price' => 14.00],
                ['title' => 'O2 CANNULAR 2 END (เด็ก)', 'unit' => 'เส้น', 'qty' => '20', 'unit_price' => 14.00],
                ['title' => 'O2 MASK ADULT', 'unit' => 'ชุด', 'qty' => '0', 'unit_price' => 50.00],
                ['title' => 'O2 MASK CHILD', 'unit' => 'ชุด', 'qty' => '40', 'unit_price' => 35.00],
                ['title' => 'O2 ถังใหญ่', 'unit' => 'ถัง', 'qty' => '0', 'unit_price' => 150.00],
                ['title' => 'O2 ถังเล็ก', 'unit' => 'ถัง', 'qty' => '0', 'unit_price' => 110.00],
                ['title' => 'O2 liquid', 'unit' => 'ลบ.ม.', 'qty' => '0', 'unit_price' => 14.02],
                ['title' => 'Peak flow (เล็ก)', 'unit' => 'ชุด', 'qty' => '2', 'unit_price' => 650.00],
                ['title' => 'Peak flow (ใหญ่)', 'unit' => 'ชุด', 'qty' => '4', 'unit_price' => 1600.00],
                ['title' => 'PENROSE DRAIN 1/2"', 'unit' => 'ชิ้น', 'qty' => '0', 'unit_price' => 20.00],
                ['title' => 'Plaster กันน้ำ 3 M (4.4x4.4 cm.)', 'unit' => 'กล่อง(50ชิ้น)', 'qty' => '0', 'unit_price' => 860.00],
                ['title' => 'Portex Blulite Ultracanular 7.0', 'unit' => 'ชิ้น', 'qty' => '10', 'unit_price' => 1267.95],
                ['title' => 'Portex Blulite Ultracanular 7.5', 'unit' => 'ชิ้น', 'qty' => '17', 'unit_price' => 1267.95],
                ['title' => 'ROUND 1/2 CIRCLE No.18', 'unit' => 'โหล', 'qty' => '11', 'unit_price' => 230.00],
                ['title' => 'ROUND 1/2 CIRCLE No.24', 'unit' => 'โหล', 'qty' => '3', 'unit_price' => 230.00],
                ['title' => 'ROUND 1/2 CIRCLE No.50', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 230.00],
                ['title' => 'RET DOT 3M', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '1', 'unit_price' => 1290.00],
                ['title' => 'SYRING แก้ว 1 ML', 'unit' => 'กล่อง (10อัน)', 'qty' => '3', 'unit_price' => 1150.00],
                ['title' => 'SYRING แก้ว 2 ML', 'unit' => 'โหล', 'qty' => '3', 'unit_price' => 245.00],
                ['title' => 'SYRING แก้ว 5 ML', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 355.00],
                ['title' => 'SYRING แก้ว 10 ML', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 460.00],
                ['title' => 'SYRING แก้ว 20 ML', 'unit' => 'โหล', 'qty' => '6', 'unit_price' => 710.00],
                ['title' => 'SYRING แก้ว 50 ML', 'unit' => 'อัน', 'qty' => '35', 'unit_price' => 160.00],
                ['title' => 'Syring IRRIGATE (แก้ว) 50 ML', 'unit' => 'อัน', 'qty' => '24', 'unit_price' => 200.00],
                ['title' => 'Stepper Heparin lock (Injection Plug)', 'unit' => 'อัน(200/กล่อง)', 'qty' => '314', 'unit_price' => 4.00],
                ['title' => 'SOFT CLOT TAPE ON LINER', 'unit' => 'ม้วน', 'qty' => '5', 'unit_price' => 180.00],
                ['title' => 'SOFT COLLAR Size S', 'unit' => 'อัน', 'qty' => '4', 'unit_price' => 147.66],
                ['title' => 'SOFT COLLAR Size M', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 147.66],
                ['title' => 'SOFT COLLAR Size L', 'unit' => 'อัน', 'qty' => '1', 'unit_price' => 147.66],
                ['title' => 'SOFT COLLAR Size XL', 'unit' => 'อัน', 'qty' => '3', 'unit_price' => 147.66],
                ['title' => 'SUCTION Tube No. 6', 'unit' => 'เส้น', 'qty' => '30', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 8', 'unit' => 'เส้น', 'qty' => '80', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 10', 'unit' => 'เส้น', 'qty' => '35', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 12', 'unit' => 'เส้น', 'qty' => '120', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 14 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '20', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 16 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '80', 'unit_price' => 3.50],
                ['title' => 'SUCTION Tube No. 18 (50/ห่อ)', 'unit' => 'เส้น', 'qty' => '40', 'unit_price' => 3.50],
                ['title' => 'SILK No. 0 [ Suture # Sterile) ]', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 750.00],
                ['title' => 'SILK No.2/0', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 750.00],
                ['title' => 'SILK No. 3/0', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 750.00],
                ['title' => 'SILK No. 4/0', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 750.00],
                ['title' => 'SPATULAR', 'unit' => 'อัน(100/กล่อง)', 'qty' => '0', 'unit_price' => 1.68],
                ['title' => 'SOFRA TULLE (Pack ละ 5 กล่อง)', 'unit' => 'กล่อง(10แผ่น)', 'qty' => '13', 'unit_price' => 150.00],
                ['title' => 'Solf Paddle (Telemed)', 'unit' => 'ชุด', 'qty' => '2', 'unit_price' => 1800.00],
                ['title' => 'Solf Paddle (AED Zoll plus)', 'unit' => 'ชุด', 'qty' => '2', 'unit_price' => 2200.00],
                ['title' => 'Steam Strip Comply test', 'unit' => 'กล่อง (240ชิ้น)', 'qty' => '5', 'unit_price' => 856.00],
                ['title' => 'Strip Comply Test E.O. (Class5)', 'unit' => 'ห่อ(250)', 'qty' => '0', 'unit_price' => 1000.00],
                ['title' => 'Spore Test', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '2', 'unit_price' => 3370.00],
                ['title' => 'Spore Test E.O.(Biological Indicator)4ชม.', 'unit' => 'กล่อง(50)', 'qty' => '3', 'unit_price' => 5000.00],
                ['title' => 'SPLINT ROLL [ 3*288*10 ]', 'unit' => 'ม้วน', 'qty' => '1', 'unit_price' => 2354.00],
                ['title' => 'SPLINT ROLL [ 4*288*10 ]', 'unit' => 'ม้วน', 'qty' => '1', 'unit_price' => 2675.00],
                ['title' => 'SPLINT ROLL [ 6*288*15 ]', 'unit' => 'ม้วน', 'qty' => '0', 'unit_price' => 4250.00],
                ['title' => 'SKIN TACK เด็ก', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '2', 'unit_price' => 350.00],
                ['title' => 'SKIN TACK', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '15', 'unit_price' => 350.00],
                ['title' => 'Scalp veine No. 22 ( 1 x 50)', 'unit' => 'กล่อง (50ชิ้น)', 'qty' => '50', 'unit_price' => 450.00],
                ['title' => 'TRANSPORE 3M 12"', 'unit' => 'ม้วน', 'qty' => '21', 'unit_price' => 299.60],
                ['title' => 'TRANSPORE 3M 1 นิ้ว (ห้องยา)', 'unit' => 'กล่อง(24ม้วน)', 'qty' => '2', 'unit_price' => 363.80],
                ['title' => 'TENSOPLAST 10 cm.', 'unit' => '1/ม้วน', 'qty' => '10', 'unit_price' => 330.00],
                ['title' => 'THORACIC CATHETER No. 24', 'unit' => 'เส้น', 'qty' => '5', 'unit_price' => 200.00],
                ['title' => 'THORACIC CATHETER No. 28', 'unit' => 'เส้น', 'qty' => '5', 'unit_price' => 200.00],
                ['title' => 'THORACIC CATHETER No. 32', 'unit' => 'เส้น', 'qty' => '6', 'unit_price' => 200.00],
                ['title' => 'Thoracic cath with trocar tube No. 24', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 290.00],
                ['title' => 'Thoracic cath with trocar tube No. 28', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 290.00],
                ['title' => 'Thoracic cath with trocar tube No. 32', 'unit' => 'เส้น', 'qty' => '0', 'unit_price' => 2920.00],
                ['title' => 'Termometer วัดอุณหภูมิตู้เย็นแบบแท่ง', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 125.00],
                ['title' => 'TREE - WAY PLASTIC', 'unit' => 'อัน (50/กล่อง)', 'qty' => '130', 'unit_price' => 12.00],
                ['title' => 'URINE BAG', 'unit' => 'ชิ้น (10/ห่อ)', 'qty' => '0', 'unit_price' => 13.50],
                ['title' => 'URENAL ผู้ชาย', 'unit' => 'อัน', 'qty' => '6', 'unit_price' => 26.00],
                ['title' => 'ULTRASONIC เจล', 'unit' => 'กระปุก', 'qty' => '2', 'unit_price' => 520.00],
                ['title' => 'VISIBLE BAG 16"X 100 M', 'unit' => 'ม้วน', 'qty' => '1', 'unit_price' => 2500.00],
                ['title' => 'VISIBLE BAG 2"X200 M', 'unit' => 'ม้วน', 'qty' => '2', 'unit_price' => 440.00],
                ['title' => 'VISIBLE BAG 3"X200 M', 'unit' => 'ม้วน', 'qty' => '0', 'unit_price' => 700.00],
                ['title' => 'VISIBLE BAG 4"X200 M', 'unit' => 'ม้วน', 'qty' => '2', 'unit_price' => 800.00],
                ['title' => 'VISIBLE BAG 6"X200 M', 'unit' => 'ม้วน', 'qty' => '0', 'unit_price' => 1200.00],
                ['title' => 'VISIBLE BAG 6"X100 M ขยายข้าง', 'unit' => 'ม้วน', 'qty' => '1', 'unit_price' => 1000.00],
                ['title' => 'WEBRILL 3"', 'unit' => 'โหล', 'qty' => '3', 'unit_price' => 120.00],
                ['title' => 'WEBRILL 4"', 'unit' => 'โหล', 'qty' => '2', 'unit_price' => 180.00],
                ['title' => 'WEBRILL 6"', 'unit' => 'โหล', 'qty' => '0', 'unit_price' => 240.00],
                ['title' => 'Y-CONNEGTER NO 11/9', 'unit' => 'อัน', 'qty' => '10', 'unit_price' => 55.00],
                ['title' => 'กระดาษEKG เครื่องdfib (A4)', 'unit' => 'ม้วน', 'qty' => '2', 'unit_price' => 120.00],
                ['title' => 'กระดาษEKG ม้วนเล็ก (FX 2111 FUKUDA)', 'unit' => 'ม้วน', 'qty' => '15', 'unit_price' => 120.00],
                ['title' => 'กระดาษ EKG (Zoll)', 'unit' => 'พับ', 'qty' => '4', 'unit_price' => 350.00],
                ['title' => 'กระดาษEKG (Mac 1200) (A4) วอร์ด', 'unit' => 'ม้วน', 'qty' => '0', 'unit_price' => 500.00],
                ['title' => 'กระดาษEKG (Mac 800)', 'unit' => 'พับ', 'qty' => '8', 'unit_price' => 400.00],
                ['title' => 'กระดาษEKG Iocare มีเส้นกราฟ', 'unit' => 'พับ', 'qty' => '5', 'unit_price' => 550.00],
                ['title' => 'กระดาษEKG Iocare ไม่มีเส้นกราฟ', 'unit' => 'พับ', 'qty' => '10', 'unit_price' => 550.00],
                ['title' => 'กระดาษอัลตร้าซาวด์ HD 110', 'unit' => 'ม้วน', 'qty' => '6', 'unit_price' => 655.00],
                ['title' => 'กระดาษเครื่อง NST', 'unit' => 'พับ', 'qty' => '4', 'unit_price' => 280.00],
                ['title' => 'กระดาษห่อเกรด A', 'unit' => 'ห่อ(2000ชิ้น)', 'qty' => '2600', 'unit_price' => 1.42],
                ['title' => 'กาแก้วอันดีน (UNDINE)', 'unit' => 'อัน', 'qty' => '1', 'unit_price' => 550.00],
                ['title' => 'แก้วยาน้ำ 2 ออน์', 'unit' => 'โหล', 'qty' => '1', 'unit_price' => 47.00],
                ['title' => 'กรรไกรตัดฝีเย็บ', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 1455.00],
                ['title' => 'กรรไกรตัดสะดือเด้ก', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 1450.00],
                ['title' => 'กรรไกรตัดไหม ปลายแหลม', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 540.00],
                ['title' => 'กรรไกรตัดไหม 13"', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 540.00],
                ['title' => 'กรรไกรตัดเนื้อ (Mezenbaum Siscer)', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 900.00],
                ['title' => 'กระเปาะ Neubulzer', 'unit' => 'ชุด', 'qty' => '7', 'unit_price' => 250.00],
                ['title' => 'ขวดน้ำยา 250 ML. (ใส)', 'unit' => 'ขวด', 'qty' => '0', 'unit_price' => 90.00],
                ['title' => 'ขวดน้ำยา 250 ML. (สีชา)', 'unit' => 'ขวด', 'qty' => '22', 'unit_price' => 120.00],
                ['title' => 'ขวด Suction Thomus', 'unit' => 'ขวด', 'qty' => '0', 'unit_price' => 1500.00],
                ['title' => 'ขวด Suction มีScale', 'unit' => 'ขวด', 'qty' => '0', 'unit_price' => 800.00],
                ['title' => 'ขวด Chest Drain 1000 ml.', 'unit' => 'ขวด', 'qty' => '1', 'unit_price' => 235.00],
                ['title' => 'จุก Chest Drain 2 ท่อ สั้น-ยาว ไม่ปีก', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 80.00],
                ['title' => 'จุก Chest Drain 2 ท่อ สั้น-สั้น ไม่ปีก', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 65.00],
                ['title' => 'จุก Chest Drain 2 ท่อ สั้น-สั้น ปีก', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 65.00],
                ['title' => 'จุก Chest Drain 3 ท่อ สั้น-ยาว ปีก', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 70.00],
                ['title' => 'จุกยางไม้ค้ำยัน', 'unit' => 'อัน', 'qty' => '10', 'unit_price' => 17.00],
                ['title' => 'เครื่องวัดออกซิเจน O2', 'unit' => 'อัน', 'qty' => '22', 'unit_price' => 1500.00],
                ['title' => 'ด้ามมีดผ่าตัดเบอร์3', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 120.00],
                ['title' => 'ถ้วยยาเม็ดพลาสติก', 'unit' => 'โหล', 'qty' => '36', 'unit_price' => 35.00],
                ['title' => 'ถุงมือผ่าตัด เบอร์ 6.0', 'unit' => 'กล่อง (50)', 'qty' => '2', 'unit_price' => 850.00],
                ['title' => 'ถุงมือผ่าตัด เบอร์ 6.5', 'unit' => 'กล่อง (50)', 'qty' => '2', 'unit_price' => 850.00],
                ['title' => 'ถุงมือผ่าตัด เบอร์ 7.0', 'unit' => 'กล่อง (50)', 'qty' => '3', 'unit_price' => 850.00],
                ['title' => 'ถุงมือผ่าตัด เบอร์ 7.5', 'unit' => 'กล่อง (50)', 'qty' => '3', 'unit_price' => 850.00],
                ['title' => 'ถุงมือล้วงรก Size S', 'unit' => 'คู่', 'qty' => '3', 'unit_price' => 200.00],
                ['title' => 'ถุงมือล้วงรก Size M', 'unit' => 'คู่', 'qty' => '4', 'unit_price' => 200.00],
                ['title' => 'ถุงมือล้วงรก Size L', 'unit' => 'คู่', 'qty' => '17', 'unit_price' => 200.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ SS', 'unit' => 'กล่อง (50คู่)', 'qty' => '9', 'unit_price' => 95.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ S', 'unit' => 'กล่อง (50คู่)', 'qty' => '19', 'unit_price' => 95.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ M', 'unit' => 'กล่อง (50คู่)', 'qty' => '46', 'unit_price' => 95.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ L', 'unit' => 'กล่อง (50คู่)', 'qty' => '40', 'unit_price' => 95.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ SS สสจ.', 'unit' => 'กล่อง (50คู่)', 'qty' => '260', 'unit_price' => 0.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ S สสจ.', 'unit' => 'กล่อง (50คู่)', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ M สสจ.', 'unit' => 'กล่อง (50คู่)', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'ถุงมือใช้แล้วทิ้ง เบอร์ L สสจ.', 'unit' => 'กล่อง (50คู่)', 'qty' => '12', 'unit_price' => 0.00],
                ['title' => 'ถุงตวงเลือด', 'unit' => 'ถุง', 'qty' => '20', 'unit_price' => 29.00],
                ['title' => 'ถุงพลาสติกห่อศพ (สีขาว)', 'unit' => 'ถุง', 'qty' => '13', 'unit_price' => 350.00],
                ['title' => 'เทปผูกท่อช่วยหายใจ', 'unit' => 'ม้วน', 'qty' => '0', 'unit_price' => 100.00],
                ['title' => 'ใบมีดผ่าตัดเบอร์ 10', 'unit' => 'กล่อง(100ช้น)', 'qty' => '4', 'unit_price' => 321.00],
                ['title' => 'ใบมีดผ่าตัดเบอร์ 11', 'unit' => 'กล่อง(100ช้น)', 'qty' => '11', 'unit_price' => 321.00],
                ['title' => 'ใบมีดผ่าตัดเบอร์ 15', 'unit' => 'กล่อง(100ช้น)', 'qty' => '0', 'unit_price' => 321.00],
                ['title' => 'แป้งคลุกถุงมือ', 'unit' => 'ถุง', 'qty' => '7', 'unit_price' => 20.00],
                ['title' => 'ปรอทแก้ว', 'unit' => 'อัน', 'qty' => '12', 'unit_price' => 45.84],
                ['title' => 'ปรอทแท่งติดตู้เย็น', 'unit' => '', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'ปรอทวัดไข้ทางทวารหนัก', 'unit' => 'โหล', 'qty' => '4', 'unit_price' => 270.00],
                ['title' => 'ป้ายข้อมือเด็ก สีฟ้า (ชาย)', 'unit' => 'กล่อง(100ช้น)', 'qty' => '4', 'unit_price' => 260.00],
                ['title' => 'ป้ายข้อมือเด็ก สีชมพู (หญิง)', 'unit' => 'กล่อง(100ช้น)', 'qty' => '3', 'unit_price' => 260.00],
                ['title' => 'ป้ายข้อมือผู้ใหญ่ สีฟ้า (ชาย)', 'unit' => 'กล่อง(100ช้น)', 'qty' => '4', 'unit_price' => 260.00],
                ['title' => 'ป้ายข้อมือผู้ใหญ่ สีชมพู (หญิง)', 'unit' => 'กล่อง(100ช้น)', 'qty' => '2', 'unit_price' => 260.00],
                ['title' => 'ผ้ายางกันเปื้อน', 'unit' => 'ชิ้น (100/ห่อ)', 'qty' => '1100', 'unit_price' => 4.00],
                ['title' => 'ผ้าอ้อมผู้ใหญ่ เบอร์ L', 'unit' => 'ชิ้น', 'qty' => '24', 'unit_price' => 0.00],
                ['title' => 'ผ้าอ้อมผู้ใหญ่ เบอร์ X L', 'unit' => 'ชิ้น', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'เฝือกดามคอชนิดแข็ง เบอร์ S ปรับไม่ได้', 'unit' => 'เส้น', 'qty' => '2', 'unit_price' => 900.00],
                ['title' => 'เฝือกดามคอชนิดแข็ง เบอร์ M ปรับไม่ได้', 'unit' => 'เส้น', 'qty' => '2', 'unit_price' => 900.00],
                ['title' => 'เฝือกดามคอชนิดแข็ง เบอร์ L ปรับไม่ได้', 'unit' => 'เส้น', 'qty' => '2', 'unit_price' => 900.00],
                ['title' => 'เฝือกดามคอชนิดแข็ง ชนิด ปรับได้', 'unit' => 'เส้น', 'qty' => '2', 'unit_price' => 1000.00],
                ['title' => 'เครื่องช่วยเดิน 4 ขา', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 600.00],
                ['title' => 'ไม้เท้า 3 ขา', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 350.00],
                ['title' => 'ไม้เท้าสระอา', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 190.00],
                ['title' => 'ไม้พันสำลี Sterile', 'unit' => 'ห่อ(50ซอง)', 'qty' => '9', 'unit_price' => 175.00],
                ['title' => 'ลูกยาง BP + วาล์ว', 'unit' => 'อัน', 'qty' => '6', 'unit_price' => 120.00],
                ['title' => 'ลูกยางแดง เบอร์ 1 (pack1โหล)', 'unit' => 'กล่อง', 'qty' => '12', 'unit_price' => 50.00],
                ['title' => 'ลูกยางแดง เบอร์ 2 (pack1โหล)', 'unit' => 'อัน', 'qty' => '10', 'unit_price' => 55.00],
                ['title' => 'ลูกยางแดง เบอร์ 3 (pack1โหล)', 'unit' => 'อัน', 'qty' => '35', 'unit_price' => 75.00],
                ['title' => 'ส้นยางรองเฝือก เด็ก', 'unit' => 'อัน', 'qty' => '2', 'unit_price' => 100.00],
                ['title' => 'ส้นยางรองเฝือก ผู้ใหญ่', 'unit' => 'อัน', 'qty' => '5', 'unit_price' => 100.00],
                ['title' => 'สำลี 1 ปอนด์ (450กรัม) BPC (วยม.)', 'unit' => 'ม้วน', 'qty' => '224', 'unit_price' => 90.00],
                ['title' => 'สำลีก้อน 450 กร้ม', 'unit' => 'ห่อ', 'qty' => '143', 'unit_price' => 70.00],
                ['title' => 'สำลีก้อน 0.35 กร้ม (pack50ซอง)', 'unit' => 'ซอง(5ก้อน)', 'qty' => '0', 'unit_price' => 4.00],
                ['title' => 'เหล็กกดลิ้น เด็ก 15 ซม', 'unit' => 'อัน', 'qty' => '19', 'unit_price' => 31.00],
                ['title' => 'เหล็กกดลิ้น ผู้ใหญ่ 19 ซม', 'unit' => 'อัน', 'qty' => '19', 'unit_price' => 38.00],
                ['title' => 'อับสำลีขนาด 3 นิ้ว ( กลาง )', 'unit' => 'ชุด', 'qty' => '0', 'unit_price' => 160.00],
                ['title' => 'กระปุกสำลี ขนาด 5x6.5 นิ้ว (ทรงสูง)', 'unit' => 'ชุด', 'qty' => '0', 'unit_price' => 535.00],
                ['title' => 'ถาดหลุมทำแผล', 'unit' => 'อัน', 'qty' => '0', 'unit_price' => 180.00],
                ['title' => 'Blendera MF 2.5 kg', 'unit' => '', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'อาหาร สูตรDM', 'unit' => '', 'qty' => '0', 'unit_price' => 0.00],
                ['title' => 'ไม้กดลิ้น Dispos Sterile', 'unit' => '1*100ชิ้น', 'qty' => '8', 'unit_price' => 160.00],
                ['title' => 'Dispos. Needle EACU No.16*13', 'unit' => 'กล่อง(100)', 'qty' => '0', 'unit_price' => 128.40],
                ['title' => 'Dispos. Needle EACU No.0.25*25', 'unit' => 'กล่อง(100)', 'qty' => '0', 'unit_price' => 128.40],
                ['title' => 'Dispos. Needle EACU No.0.25*40', 'unit' => 'กล่อง(100)', 'qty' => '400', 'unit_price' => 128.40],
                ['title' => 'Dispos. Needle EACU No.0.25*50', 'unit' => 'กล่อง(100)', 'qty' => '0', 'unit_price' => 128.40],
                ['title' => 'Dispos. Needle EACU No.0.3*75', 'unit' => 'กล่อง(100)', 'qty' => '5', 'unit_price' => 128.40],
                ['title' => 'เข็มติดหู + พลาสเตอร์สีเนื้อ', 'unit' => 'กล่อง(100)', 'qty' => '1', 'unit_price' => 149.80],
                ['title' => 'ถ้วยแก้ว ขนาด 5.5 ซม. No.3', 'unit' => 'อัน', 'qty' => '18', 'unit_price' => 64.20],
                ['title' => 'ถ้วยแก้ว ขนาด 6.5 ซม. No.4', 'unit' => 'อัน', 'qty' => '11', 'unit_price' => 64.20],
        ];