<?php
use yii\helpers\Html;
$this->title = 'จัดการแบบสอบถาม Exit Interview';
$this->beginBlock('page-title'); echo Html::encode($this->title); $this->endBlock();
$this->beginBlock('page-action'); echo $this->render('@app/modules/hr/menu', ['active' => 'exit']); $this->endBlock();
?>
<div class="container-fluid px-0"><?= $this->render('_nav', ['active' => 'templates']) ?><div class="mb-4"><h1 class="h3 mb-1">แบบสอบถามและเวอร์ชัน</h1><p class="text-body-secondary mb-0">เวอร์ชันที่เผยแพร่แล้วจะไม่ถูกแก้ไข ให้คัดลอกเป็นฉบับร่างก่อนเปลี่ยนคำถาม</p></div><div id="exit-templates">
<?php foreach ($templates as $template): ?><section class="card bg-body border shadow-sm mb-3"><div class="card-header bg-body-tertiary"><h2 class="h5 mb-1"><?= Html::encode($template->title) ?></h2><p class="text-body-secondary small mb-0"><?= Html::encode($template->description) ?></p></div><div class="card-body"><div class="accordion" id="versions-<?= (int)$template->id ?>">
<?php foreach ($template->versions as $version): ?><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#version-<?= (int)$version->id ?>">เวอร์ชัน <?= (int)$version->version_no ?> <span class="badge ms-2 <?= $version->status === 'published' ? 'bg-success-subtle text-success-emphasis' : ($version->status === 'draft' ? 'bg-warning-subtle text-warning-emphasis' : 'bg-secondary-subtle text-secondary-emphasis') ?>"><?= Html::encode(['published' => 'ใช้งาน', 'draft' => 'ฉบับร่าง', 'retired' => 'เลิกใช้'][$version->status] ?? $version->status) ?></span></button></h3><div id="version-<?= (int)$version->id ?>" class="accordion-collapse collapse"><div class="accordion-body"><div class="d-flex flex-wrap justify-content-end gap-2 mb-3"><?php if ($version->status !== 'draft'): ?><?= Html::a('คัดลอกเป็นเวอร์ชันใหม่', ['clone-version', 'id' => $version->id], ['class' => 'btn btn-sm btn-outline-primary', 'data-method' => 'post']) ?><?php else: ?><?= Html::a('เผยแพร่เวอร์ชันนี้', ['publish', 'id' => $version->id], ['class' => 'btn btn-sm btn-primary', 'data-method' => 'post', 'data-confirm' => 'เผยแพร่เวอร์ชันนี้และเลิกใช้เวอร์ชันปัจจุบันหรือไม่']) ?><?php endif ?></div>
<?php foreach ($version->sections as $section): ?><div class="mb-4"><div class="d-flex justify-content-between align-items-center gap-2 mb-2"><h4 class="h6 mb-0"><?= Html::encode($section->title) ?></h4><?php if ($version->status === 'draft'): ?><?= Html::a('เพิ่มคำถาม', ['question', 'section_id' => $section->id], ['class' => 'btn btn-sm btn-outline-primary open-modal', 'data-size' => 'modal-lg']) ?><?php endif ?></div><div class="list-group"><?php foreach ($section->questions as $question): ?><div class="list-group-item d-flex justify-content-between align-items-start gap-3"><div><span class="badge bg-secondary-subtle text-secondary-emphasis me-2"><?= Html::encode($question->question_type) ?></span><?= Html::encode($question->prompt) ?><?php if ($question->is_required): ?><span class="text-danger"> *</span><?php endif ?><small class="d-block text-body-secondary mt-1"><?= Html::encode($question->analytics_key ? 'ตัวชี้วัด: ' . $question->analytics_key : 'ไม่รวมในตัวชี้วัดคะแนน') ?></small></div><?php if ($version->status === 'draft'): ?><?= Html::a('แก้ไข', ['question', 'id' => $question->id], ['class' => 'btn btn-sm btn-outline-secondary open-modal', 'data-size' => 'modal-lg']) ?><?php endif ?></div><?php endforeach ?></div></div><?php endforeach ?></div></div></div><?php endforeach ?>
</div></div></section><?php endforeach ?></div></div>
