<?php

use yii\helpers\Html;
$receipt=$model->receipt;$allocation=$model->allocations[0]??null;$invoice=$allocation?->invoice;$account=$invoice?->monthlyAccount;
$this->title='ใบเสร็จ '.($receipt?->receipt_no?:$model->payment_no);
$this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock();
$this->beginBlock('page-action'); ?><?= $this->render('../_menu',['active'=>'utility']) ?><?php $this->endBlock();
?>
<div class="container py-3" style="max-width:920px">
<?php foreach(['success','error'] as $type):if(Yii::$app->session->hasFlash($type)):?><div class="alert alert-<?= $type==='error'?'danger':'success' ?>"><?= Html::encode(Yii::$app->session->getFlash($type)) ?></div><?php endif;endforeach;?>
<div class="d-flex justify-content-between gap-2 mb-3"><?= Html::a('กลับประวัติรับชำระ',['index'],['class'=>'btn btn-outline-secondary']) ?><?= Html::a('พิมพ์ใบเสร็จ',['print','id'=>$model->id],['class'=>'btn btn-outline-primary','target'=>'_blank']) ?></div>
<div class="card shadow-sm mb-3"><div class="card-header bg-body d-flex justify-content-between"><strong>ข้อมูลรับชำระ</strong><span class="badge <?= $model->status==='confirmed'?'bg-success-subtle text-success-emphasis':'bg-danger-subtle text-danger-emphasis' ?>"><?= $model->status==='confirmed'?'รับชำระแล้ว':'ยกเลิกแล้ว' ?></span></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">เลขที่ใบเสร็จ</dt><dd class="col-sm-8 fw-semibold"><?= Html::encode($receipt?->receipt_no) ?></dd><dt class="col-sm-4">ผู้ชำระ</dt><dd class="col-sm-8"><?= Html::encode($account?->payer_name) ?></dd><dt class="col-sm-4">ประจำเดือน</dt><dd class="col-sm-8"><?= Html::encode($account?->period?->name) ?></dd><dt class="col-sm-4">วันที่รับชำระ</dt><dd class="col-sm-8"><?= Yii::$app->formatter->asDatetime($model->paid_at,'php:d/m/Y H:i') ?></dd><dt class="col-sm-4">วิธีชำระ</dt><dd class="col-sm-8"><?= $model->payment_method==='transfer'?'เงินโอน':'เงินสด' ?><?= $model->reference_no?' · '.Html::encode($model->reference_no):'' ?></dd><dt class="col-sm-4">จำนวนเงิน</dt><dd class="col-sm-8 fs-5 fw-bold"><?= Yii::$app->formatter->asDecimal($model->amount,2) ?> บาท</dd><dt class="col-sm-4">ยอดคงเหลือหลังชำระ</dt><dd class="col-sm-8"><?= Yii::$app->formatter->asDecimal($invoice?->balance_amount,2) ?> บาท</dd></dl></div></div>
<?php if($model->status==='confirmed'):?><div class="card border-danger-subtle"><div class="card-header bg-body fw-semibold">ยกเลิกรายการรับชำระ</div><div class="card-body"><?= Html::beginForm(['cancel','id'=>$model->id],'post',['class'=>'d-flex flex-column gap-3']) ?><div><label class="form-label">เหตุผลการยกเลิก</label><?= Html::textarea('cancel_reason','',['class'=>'form-control','rows'=>2,'required'=>true]) ?></div><div class="text-end"><button class="btn btn-outline-danger" data-confirm="ยืนยันยกเลิกรายการรับชำระและคืนยอดคงเหลือหรือไม่?">ยกเลิกรายการรับชำระ</button></div><?= Html::endForm() ?></div></div><?php elseif($model->cancel_reason):?><div class="alert alert-danger">เหตุผลการยกเลิก: <?= Html::encode($model->cancel_reason) ?></div><?php endif;?>
</div>
