<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
$this->title='ตรวจสอบก่อนปิดงวด';$this->params['breadcrumbs'][]=['label'=>'ระบบบัญชี','url'=>['/accounting/dashboard']];$this->params['breadcrumbs'][]=$this->title;
$this->beginBlock('page-title'); ?><h4 class="mb-0"><i class="bi bi-calendar-check me-2" aria-hidden="true"></i><?= Html::encode($this->title) ?></h4><?php $this->endBlock();
$this->beginBlock('sub-title'); ?>ตรวจยอด GL และรายการค้างก่อนอนุญาตให้ล็อกงวด<?php $this->endBlock();
$this->beginBlock('page-action'); ?><?= $this->render('@app/modules/accounting/menu',['active'=>'period-review']) ?><?php $this->endBlock(); ?>
<form class="card card-body border mb-3" method="get"><div class="row g-2 align-items-end"><div class="col-sm-3"><label class="form-label" for="review-year">ปีงบประมาณ</label><?= Html::input('number','year',$year,['id'=>'review-year','class'=>'form-control','min'=>2500,'max'=>2700]) ?></div><div class="col-sm-6"><label class="form-label" for="review-period">งวดรายเดือน</label><?= Html::dropDownList('period_id',$period?->id,ArrayHelper::map($periods,'id',fn($p)=>$p->name.' ('.$p->start_date.' – '.$p->end_date.')'),['id'=>'review-period','class'=>'form-select','prompt'=>$periods?'เลือกงวด':'ยังไม่มีงวดบัญชี']) ?></div><div class="col-sm-3"><?= Html::submitButton('<i class="bi bi-arrow-repeat me-1"></i>ตรวจสอบยอด',['class'=>'btn btn-primary w-100']) ?></div></div></form>
<?php if(!$period): ?><div class="alert alert-warning" role="status"><strong>ยังตรวจสอบไม่ได้</strong> — ไม่พบงวดบัญชีรายเดือนในปีงบประมาณ <?= Html::encode($year) ?> กรุณาสร้างงวดบัญชีก่อน</div>
<?php else: $summary=$review['summary']; ?>
<div class="alert <?= $summary['ready']?'alert-success':'alert-warning' ?>" role="status"><div class="d-flex gap-2 align-items-start"><i class="bi <?= $summary['ready']?'bi-check-circle-fill':'bi-exclamation-triangle-fill' ?> mt-1" aria-hidden="true"></i><div><strong><?= $summary['ready']?'ยอด GL พร้อมสำหรับขั้นปิดงวด':'ยังไม่พร้อมปิดงวด' ?></strong><?php if($summary['issues']): ?><ul class="mb-0 mt-1"><?php foreach($summary['issues'] as $issue): ?><li><?= Html::encode($issue) ?></li><?php endforeach; ?></ul><?php else: ?><div>ไม่พบยอดต่างหรือรายการค้าง การล็อกงวดจริงจะพัฒนาในเฟสถัดไป</div><?php endif; ?></div></div></div>
<div class="d-flex flex-wrap justify-content-between gap-2 bg-body-tertiary rounded px-3 py-2 mb-3"><span><span class="text-body-secondary me-2">รายการผ่านบัญชี</span><strong><?= number_format($summary['journal_count']) ?></strong></span><span><span class="text-body-secondary me-2">รายการร่างค้าง</span><strong><?= number_format($summary['draft_count']) ?></strong></span><span><span class="text-body-secondary me-2">เดบิต</span><strong class="font-monospace"><?= number_format($summary['debit'],2) ?></strong></span><span><span class="text-body-secondary me-2">เครดิต</span><strong class="font-monospace"><?= number_format($summary['credit'],2) ?></strong></span></div>
<section class="card border"><div class="card-header bg-body"><h5 class="mb-0">ยอดเคลื่อนไหวรายบัญชี — <?= Html::encode($period->name) ?></h5></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th class="text-end">เดบิต</th><th class="text-end">เครดิต</th><th class="text-end">ยอดสุทธิ</th></tr></thead><tbody><?php foreach($review['balances'] as $row): ?><tr><td class="font-monospace text-nowrap"><?= Html::encode($row['account_code_snapshot']) ?></td><td><?= Html::encode($row['account_name_snapshot']) ?></td><td class="text-end text-nowrap"><?= number_format((float)$row['debit'],2) ?></td><td class="text-end text-nowrap"><?= number_format((float)$row['credit'],2) ?></td><td class="text-end text-nowrap"><?= number_format((float)$row['balance'],2) ?></td></tr><?php endforeach; ?><?php if(!$review['balances']): ?><tr><td colspan="5" class="text-center text-body-secondary py-5">ยังไม่มีรายการผ่านบัญชีในงวดนี้</td></tr><?php endif; ?></tbody></table></div></section>
<?php endif; ?>
