<?php
/** php tests/hr-engagement-integration.php — isolated in-memory SQLite, never loads production config. */
defined('YII_DEBUG') or define('YII_DEBUG',false);
require dirname(__DIR__).'/vendor/autoload.php';
require dirname(__DIR__).'/vendor/yiisoft/yii2/Yii.php';
new yii\console\Application(['id'=>'engagement-test','basePath'=>dirname(__DIR__),'components'=>['db'=>['class'=>yii\db\Connection::class,'dsn'=>'sqlite::memory:']]]);
require dirname(__DIR__).'/migrations/engagement/m260908_120000_create_engagement.php';
$db=Yii::$app->db;
ob_start(); (new m260908_120000_create_engagement(['db'=>$db]))->up(); ob_end_clean();
$db->createCommand()->createTable('employees',['id'=>'integer PRIMARY KEY','department'=>'integer','fname'=>'text','lname'=>'text','branch'=>'text'])->execute();
for($i=2;$i<=8;$i++) $db->createCommand()->insert('employees',['id'=>$i,'department'=>10,'fname'=>'Synthetic','lname'=>(string)$i,'branch'=>'MAIN'])->execute();
$service=new class($db) extends app\modules\hr\services\EngagementService {
    public function eligibleEmployees(): array { return (new yii\db\Query())->select(['id','department',new yii\db\Expression("'Synthetic unit' AS department_name")])->from('employees')->all(); }
};
$checks=0;
$check=function($condition,$message) use (&$checks) { $checks++; if(!$condition) throw new RuntimeException($message); };
$reject=function(callable $callback,$message) use($check) { try { $callback(); } catch(DomainException $e) { $check(true,$message); return; } $check(false,$message); };
$dimensions=[['code'=>'engagement','title'=>'ผลความผูกพัน','kind'=>'outcome','questions'=>[['prompt'=>'Pride'],['prompt'=>'Stay']]],['code'=>'workload','title'=>'ภาระงาน','kind'=>'driver','questions'=>[['prompt'=>'Excessive workload','reverse_scored'=>true]]]];
$v=$service->saveTemplate('Synthetic template',$dimensions,99);
$reject(fn()=>$service->createRound(['version_id'=>$v],99),'draft template cannot open round');
$service->publishVersion($v,99);
$reject(fn()=>$service->saveTemplate('changed',$dimensions,99,$v),'published template immutable');
$copy=$service->cloneVersion($v,99); $service->publishVersion($copy,99);
$check($service->row('version',$v)['comparability_key']===$service->row('version',$copy)['comparability_key'],'clone remains comparable');
$input=['version_id'=>$v,'title'=>'Synthetic round','fiscal_year'=>2569,'open_at'=>date('Y-m-d\TH:i',time()-86400),'close_at'=>date('Y-m-d\TH:i',time()+86400),'privacy_notice'=>str_repeat('คำชี้แจงข้อมูลสังเคราะห์ ',3),'retention_days'=>365,'minimum_group_size'=>5,'policy_confirmed'=>'1'];
$round=$service->createRound($input,99);
$service->openRound($round,99);
$reject(fn()=>$service->openRound($round,99),'cannot open twice');
$reject(fn()=>$service->createRound($input,99,$round),'open round immutable');
$check((int)$service->query('invitation')->where(['round_id'=>$round])->count()===7,'frozen eligible denominator');
$db->createCommand()->update('employees',['department'=>99],['id'=>2])->execute();
$check((int)$service->invitation($round,2)['department_id_snapshot']===10,'department does not drift');
$definition=$service->definition($v); $answers=[]; $na=[];
foreach($definition as $d) foreach($d['questions'] as $q) { foreach($q['options'] as $o) { if((string)$o['code']==='4') $answers[$q['id']]=$o['id']; if($o['is_missing']) $na[$q['id']]=$o['id']; } }
$reject(fn()=>$service->submit($round,999,$answers,str_repeat('x',20)),'non-eligible rejected');
$bad=$answers; $keys=array_keys($bad); $bad[$keys[0]]=$bad[$keys[1]];
$reject(fn()=>$service->submit($round,2,$bad,str_repeat('x',20)),'cross-question option rejected');
$check($service->invitation($round,2)['completion_status']==='pending','failure leaves completion pending');
$bad=$answers; $bad[999999]=1;
$reject(fn()=>$service->submit($round,2,$bad,str_repeat('x',20)),'extra question rejected');
for($i=2;$i<=6;$i++) $service->submit($round,$i,$answers,str_repeat((string)$i,20));
$service->submit($round,2,$na,str_repeat('z',20));
$check((int)$service->query('response')->where(['round_id'=>$round])->count()===5,'duplicate remains one');
$check($service->report($round)['metrics']===[],'no scores before close/publish');
$reject(fn()=>$service->publishResults($round,99),'cannot publish open round');
$service->closeRound($round,99);
$reject(fn()=>$service->submit($round,7,$answers,str_repeat('7',20)),'closed rejects new submission');
$service->publishResults($round,99);
$report=$service->report($round); $metrics=array_column($report['metrics'],null,'dimension_code');
$check(abs((float)$metrics['engagement']['mean_score']-4)<0.0001,'outcome mean 4');
$check(abs((float)$metrics['_overall']['index_score']-75)<0.0001,'index 75, not 80');
$check(abs((float)$metrics['workload']['mean_score']-2)<0.0001,'reverse scoring 6 minus 4');
$check((int)$metrics['_overall']['eligible_n']===7 && (int)$metrics['_overall']['respondent_n']===5,'rate denominator frozen');
$check($service->dashboard(2569,null)['report']['round']['id']==$round,'dashboard one round');
$check($service->dashboard(2570,$round)['report']===null,'cross-year selection rejected');
$action=$service->saveAction(['round_id'=>$round,'dimension_code'=>'workload','owner_emp_id'=>2,'due_date'=>'2026-12-31','issue_summary'=>'Synthetic improvement','target'=>'Follow up next round'],99);
$reject(fn()=>$service->saveAction(['status'=>'done'],99,$action),'completion needs evidence');
$service->saveAction(['status'=>'done','effectiveness_note'=>'Synthetic work complete; outcome follow-up pending'],99,$action);
$check($service->row('action',$action)['completed_at']!==null,'action completed');
$small=$service->createRound(array_merge($input,['title'=>'Small group']),99); $service->openRound($small,99);
for($i=2;$i<=5;$i++) $service->submit($small,$i,$answers,str_repeat((string)$i,20));
$service->closeRound($small,99); $service->publishResults($small,99);
foreach($service->report($small)['metrics'] as $m) $check($m['status']==='suppressed' && $m['mean_score']===null && $m['valid_n']===null && $m['eligible_n']===null && $m['favorable_percent']===null,'suppression removes values and denominators');
$check($service->dashboard(2569,null)['report']===null,'multiple rounds require selection');
$empty=$service->createRound(array_merge($input,['title'=>'Empty']),99); $service->openRound($empty,99); $service->closeRound($empty,99); $service->publishResults($empty,99);
$check($service->report($empty)['metrics'][0]['status']==='no_data','empty is not zero');
$score=app\modules\hr\services\EngagementService::score([['code'=>'a','title'=>'A','kind'=>'outcome','questions'=>[['id'=>1],['id'=>2],['id'=>3],['id'=>4],['id'=>5]]]],['one'=>[1=>5,2=>5,3=>5,4=>5,5=>null],'two'=>[1=>1,2=>1,3=>1,4=>null,5=>null]]);
$check($score['a']['valid_n']===1 && $score['a']['mean']===5.0,'80% completion and NA omitted');
$check(!isset($db->getTableSchema('hr_engagement_response')->columns['created_by']),'no response actor');
$check((int)$service->query('audit')->where(['event'=>'response_submitted'])->count()===0,'no identified response audit');
$check(app\modules\hr\services\EngagementService::localToUtc('2026-09-08T07:00')==='2026-09-08 00:00:00','Thai time conversion');
$reject(fn()=>app\modules\hr\services\EngagementService::localToUtc('2026-02-31T07:00'),'invalid calendar date');
$unconfirmed=$service->createRound(array_merge($input,['policy_confirmed'=>'0']),99);
$reject(fn()=>$service->openRound($unconfirmed,99),'unconfirmed policy cannot open');
$service->createRound($input,99,$unconfirmed); $service->openRound($unconfirmed,99);
$check($service->row('round',$unconfirmed)['status']==='open','draft policy can be completed');
$retention=new app\modules\hr\services\EngagementRetentionService($db);
$expires=(new DateTimeImmutable($service->row('round',$small)['close_at'],new DateTimeZone('UTC')))->modify('+365 days');
$reject(fn()=>$retention->purge($small,'Synthetic test',$expires->modify('-1 second')->format('Y-m-d H:i:s')),'purge cannot run before expiry');
$retention->purge($small,'Synthetic test',$expires->format('Y-m-d H:i:s'));
$check(!$service->query('response')->where(['round_id'=>$small])->exists() && !$service->query('invitation')->where(['round_id'=>$small])->exists(),'expired identity and raw responses removed');
$check(count($service->report($small)['metrics'])===3,'published aggregates retained');
$retention->purge($small,'Synthetic retry',$expires->format('Y-m-d H:i:s'));
$check((int)$service->query('audit')->where(['round_id'=>$small,'event'=>'raw_data_purged'])->count()===1,'purge idempotent audit');
$check(in_array($unconfirmed,array_column($retention->due($expires->format('Y-m-d H:i:s')),'id'),true),'expired unclosed round included in retention');
$retention->purge($unconfirmed,'Synthetic abandoned round',$expires->format('Y-m-d H:i:s'));
$check($service->row('round',$unconfirmed)['status']==='closed' && !$service->query('invitation')->where(['round_id'=>$unconfirmed])->exists(),'expired unclosed round purged and closed');
$reject(fn()=>$service->publishResults($unconfirmed,99),'purged data cannot replace results');
$target=new class extends yii\log\Target {
    public string $captured='';
    public function export() { foreach($this->messages as $message) $this->captured.=$this->formatMessage($message); }
};
Yii::$app->log->targets=['privacy_test'=>$target];
$_POST=['answers'=>['PRIVATE_ANSWER_SENTINEL'],'submission_key'=>'PRIVATE_KEY_SENTINEL']; $_SESSION=['identity'=>'PRIVATE_IDENTITY_SENTINEL'];
app\modules\hr\services\EngagementPrivacy::protect();
Yii::error('Synthetic submission failure; payload omitted','engagement'); Yii::getLogger()->flush(true);
$check(strpos($target->captured,'Synthetic submission failure')!==false,'operational error still logged');
$check(strpos($target->captured,'PRIVATE_')===false,'no answer/key/identity in exported log context');
$_POST=[]; $_SESSION=[];
echo "PASS {$checks} engagement integration checks (isolated SQLite, synthetic records only)\n";
