<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\appreciation\models\AppreciationProgramYear;
use app\modules\appreciation\models\AppreciationValue;
use app\modules\appreciation\models\AppreciationLevel;
use app\modules\appreciation\models\AppreciationReward;
use app\modules\appreciation\models\AppreciationChallenge;
use app\modules\appreciation\models\AppreciationRedemption;
use app\modules\appreciation\models\AppreciationParticipation;
use yii\helpers\ArrayHelper;
use app\widgets\datepicker\DatepickerThai;
use app\components\AppHelper;

$this->title='จัดการพลังแห่งคำขอบคุณ';
$this->registerCssFile('@web/css/appreciation-media.css');
$yearItems=ArrayHelper::map($years,'id',fn($y)=>$y->name.' ('.$y->year.')');
?>
<div class="py-3 px-2 px-md-3 appreciation-admin">
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><h1 class="h4 fw-bold mb-1">จัดการพลังแห่งคำขอบคุณ</h1><p class="text-muted mb-0">กำหนดรอบปี ค่านิยม ระดับ กิจกรรม ของรางวัล และตรวจสอบการแลก</p></div><?= Html::a('กลับไปหน้าคำขอบคุณ',['/appreciation/default/index'],['class'=>'btn btn-outline-secondary']) ?></div>
<div class="row g-3 mb-4 appreciation-admin-metrics"><?php foreach([['กิจกรรมทั้งหมด',$dashboard['activities'],'bi-calendar-event'],['บุคลากรที่มีส่วนร่วม',$dashboard['participants'],'bi-people'],['อัตราการมีส่วนร่วม',$dashboard['participationRate'].'%','bi-graph-up'],['คะแนนจากกิจกรรม',$dashboard['points'],'bi-star']] as $metric): ?><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><i class="bi <?= $metric[2] ?> text-primary" aria-hidden="true"></i><div class="fs-3 fw-bold mt-2"><?= is_numeric($metric[1])?number_format($metric[1]):Html::encode($metric[1]) ?></div><div class="small text-muted"><?= $metric[0] ?></div></div></div></div><?php endforeach; ?></div>
<ul class="nav nav-tabs mb-3" role="tablist">
<?php foreach(['years'=>'รอบปี','values'=>'ค่านิยมองค์กร','levels'=>'ระดับ','scores'=>'คะแนนบุคลากร','activities'=>'กิจกรรมสะสมคะแนน','participations'=>'ผู้เข้าร่วม','challenges'=>'ภารกิจคำขอบคุณ','rewards'=>'ของรางวัล','redemptions'=>'การแลกรางวัล'] as $id=>$label): ?><li class="nav-item"><button class="nav-link<?= $id==='years'?' active':'' ?>" data-bs-toggle="tab" data-bs-target="#<?= $id ?>" type="button"><?= $label ?></button></li><?php endforeach; ?>
<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#analytics" type="button"><i class="bi bi-bar-chart me-1"></i> วิเคราะห์ HR</button></li>
</ul>
<div class="tab-content">
<?= $this->render('_analytics', ['activeYear'=>$activeYear,'valueColumns'=>$valueColumns,'analyticsRows'=>$analyticsRows,'participantAnalytics'=>$participantAnalytics,'participations'=>$participations,'employees'=>$employees]) ?>
<?php
$forms=[
 'years'=>[$editType==='year'&&$editModel?$editModel:new AppreciationProgramYear(), 'year', [['year','number'],['name','text'],['points_per_thank','number'],['start_at','date'],['end_at','date'],['status','dropDownList',AppreciationProgramYear::statusLabels()]], $years],
 'values'=>[$editType==='value'&&$editModel?$editModel:new AppreciationValue(), 'value', [['code','text'],['name','text'],['core_value_code','text'],['core_value_name','text'],['icon','text'],['points','number'],['sort_order','number'],['is_active','checkbox']], $values],
 'levels'=>[$editType==='level'&&$editModel?$editModel:new AppreciationLevel(), 'level', [['program_year_id','dropDownList',$yearItems],['name','text'],['min_points','number'],['color','color']], $levels],
 'challenges'=>[$editType==='challenge'&&$editModel?$editModel:new AppreciationChallenge(), 'challenge', [['name','text'],['description','textarea'],['start_at','date'],['end_at','date'],['goal_type','dropDownList',AppreciationChallenge::goalTypeLabels()],['goal_value','number'],['reward_name','text'],['status','dropDownList',AppreciationChallenge::statusLabels()]], $challenges],
 'rewards'=>[$editType==='reward'&&$editModel?$editModel:new AppreciationReward(), 'reward', [['program_year_id','dropDownList',$yearItems],['name','text'],['description','textarea'],['imageFile','image'],['points_cost','number'],['stock_qty','number'],['is_active','checkbox']], $rewards],
 'activities'=>[$editType==='activity'&&$editModel?$editModel:new \app\modules\appreciation\models\AppreciationActivity(), 'activity', [['program_year_id','dropDownList',$yearItems],['title','text'],['description','textarea'],['imageFile','image'],['activity_type','dropDownList',\app\modules\appreciation\models\AppreciationActivity::typeLabels()],['participation_mode','dropDownList',\app\modules\appreciation\models\AppreciationActivity::modeLabels()],['external_url','text'],['points','number'],['capacity','number'],['start_at','date'],['end_at','date'],['status','dropDownList',\app\modules\appreciation\models\AppreciationActivity::statusLabels()],['requires_review','checkbox']], $activities],
];
foreach($forms as $tab=>$cfg): [$model,$type,$fields,$items]=$cfg; ?>
<section class="tab-pane fade<?= $tab==='years'?' show active':'' ?>" id="<?= $tab ?>">
 <div class="row g-4"><div class="col-12 col-xl-4"><div class="card shadow-sm border-0"><div class="card-header bg-white d-flex justify-content-between align-items-center px-4 py-3"><span class="fw-semibold"><?= $model->isNewRecord?'เพิ่มข้อมูล':'แก้ไขข้อมูล' ?></span><?php if(!$model->isNewRecord): ?><?= Html::a('ยกเลิก',['index','#'=>$tab],['class'=>'btn btn-sm btn-outline-secondary']) ?><?php endif; ?></div><div class="card-body p-4"><?php $form=ActiveForm::begin(['action'=>['save','type'=>$type,'id'=>$model->isNewRecord?null:$model->id],'options'=>['class'=>'d-flex flex-column gap-1','enctype'=>'multipart/form-data']]); foreach($fields as $f){ [$attr,$kind]=$f; if($kind==='dropDownList') echo $form->field($model,$attr)->dropDownList($f[2],['prompt'=>'เลือก']); elseif($kind==='textarea') echo $form->field($model,$attr)->textarea(['rows'=>3]); elseif($kind==='checkbox') echo $form->field($model,$attr)->checkbox(); elseif($kind==='image'){ if(!empty($model->image_url)) echo Html::img($model->image_url,['class'=>'img-fluid rounded-2 border mb-2','style'=>'max-height:180px;object-fit:cover','alt'=>'ภาพปัจจุบัน']); echo $form->field($model,$attr)->fileInput(['accept'=>'image/png,image/jpeg,image/webp','class'=>'form-control'])->hint('JPG, PNG หรือ WebP ขนาดไม่เกิน 5 MB'); } elseif($kind==='date'){ $inputId=Html::getInputId($model,$attr); echo '<div class="mb-3"><label class="form-label fw-semibold" for="'.$inputId.'">'.Html::encode($model->getAttributeLabel($attr)).'</label>'; echo DatepickerThai::widget(['name'=>Html::getInputName($model,$attr),'value'=>$model->$attr?AppHelper::convertToThai($model->$attr):'','options'=>['id'=>$inputId,'class'=>'form-control','autocomplete'=>'off','placeholder'=>'วว/ดด/พ.ศ.']]); echo Html::error($model,$attr,['class'=>'invalid-feedback d-block']).'</div>'; } else echo $form->field($model,$attr)->textInput(['type'=>$kind]); } echo '<div class="d-flex flex-wrap gap-2 pt-2">'.Html::submitButton($model->isNewRecord?'บันทึกข้อมูล':'บันทึกการแก้ไข',['class'=>'btn btn-primary px-4']).'</div>'; ActiveForm::end(); ?></div></div></div>
 <div class="col-12 col-xl-8"><div class="card shadow-sm border-0"><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>รายการ</th><th>รายละเอียด</th><th class="text-end">สถานะ/ค่า</th><th class="text-end">จัดการ</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td class="fw-semibold"><?= Html::encode($item->title ?? $item->name ?? $item->code ?? $item->year) ?></td><td class="small text-muted"><?= Html::encode($item->description ?? ($item->start_at ?? '').(isset($item->end_at)?' ถึง '.$item->end_at:'')) ?></td><td class="text-end"><?= Html::encode($item->status ?? ($item->points_cost ?? ($item->min_points ?? ($item->points ?? '')))) ?></td><td class="text-end"><?= Html::a('แก้ไข',['index','edit_type'=>$type,'edit_id'=>$item->id,'#'=>$tab],['class'=>'btn btn-sm btn-outline-primary']) ?></td></tr><?php endforeach; ?><?php if(!$items): ?><tr><td colspan="4" class="text-center py-5 text-muted">ยังไม่มีรายการ กรุณาเพิ่มข้อมูลจากแบบฟอร์ม</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
</section><?php endforeach; ?>
<section class="tab-pane fade" id="participations"><div class="card shadow-sm border-0"><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>บุคลากร</th><th>กิจกรรม</th><th>สถานะ</th><th class="text-end">คะแนน</th><th class="text-end">ตรวจสอบ</th></tr></thead><tbody><?php foreach($participations as $p): $emp=$employees[$p->emp_id]??null; ?><tr><td class="fw-semibold"><?= Html::encode($emp?$emp->fullname():'#'.$p->emp_id) ?><div class="small text-muted"><?= Yii::$app->formatter->asDatetime($p->registered_at) ?></div></td><td><?= Html::encode($p->activity?$p->activity->title:'—') ?><?php if($p->evidence_url): ?><div><a href="<?= Html::encode($p->evidence_url) ?>" target="_blank" rel="noopener">ดูหลักฐาน</a></div><?php endif; ?></td><td><?= Html::encode(AppreciationParticipation::statusLabels()[$p->status]??$p->status) ?></td><td class="text-end"><?= number_format($p->points_awarded) ?></td><td class="text-end"><div class="btn-group btn-group-sm"><?= Html::a('ให้คะแนน',['participation','id'=>$p->id,'status'=>'completed'],['class'=>'btn btn-outline-success','data-method'=>'post']) ?><?= Html::a('ไม่ผ่าน',['participation','id'=>$p->id,'status'=>'rejected'],['class'=>'btn btn-outline-danger','data-method'=>'post']) ?></div></td></tr><?php endforeach; ?></tbody></table></div></div></div></section>
<section class="tab-pane fade" id="scores"><div class="card shadow-sm border-0"><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>บุคลากร</th><th class="text-end">คำขอบคุณ</th><th class="text-end">กิจกรรม</th><th class="text-end">คะแนนรวม</th></tr></thead><tbody><?php foreach($scoreRows as $row): $emp=$employees[$row['emp_id']]??null; ?><tr><td class="fw-semibold"><?= Html::encode($emp?$emp->fullname():'#'.$row['emp_id']) ?></td><td class="text-end"><?= number_format($row['thanks']) ?></td><td class="text-end"><?= number_format($row['activities']) ?></td><td class="text-end fw-bold text-primary"><?= number_format($row['total']) ?></td></tr><?php endforeach; ?><?php if(!$scoreRows): ?><tr><td colspan="4" class="text-center py-5 text-muted">ยังไม่มีคะแนนในรอบปีที่กำลังใช้งาน</td></tr><?php endif; ?></tbody></table></div></div></div></section>
<section class="tab-pane fade" id="redemptions"><div class="card shadow-sm border-0"><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ผู้ขอ</th><th>ของรางวัล</th><th class="text-end">คะแนน</th><th>สถานะ</th><th class="text-end">ดำเนินการ</th></tr></thead><tbody><?php foreach($redemptions as $r): ?><tr><td>#<?= (int)$r->emp_id ?><div class="small text-muted"><?= Yii::$app->formatter->asDatetime($r->requested_at) ?></div></td><td><?= Html::encode($r->reward ? $r->reward->name : '—') ?></td><td class="text-end"><?= number_format($r->points_used) ?></td><td><?= Html::encode(AppreciationRedemption::statusLabels()[$r->status]??$r->status) ?></td><td class="text-end"><div class="btn-group btn-group-sm"><?= Html::a('อนุมัติ',['redemption','id'=>$r->id,'status'=>'approved'],['class'=>'btn btn-outline-primary','data-method'=>'post']) ?><?= Html::a('ส่งมอบแล้ว',['redemption','id'=>$r->id,'status'=>'delivered'],['class'=>'btn btn-outline-success','data-method'=>'post']) ?><?= Html::a('ไม่อนุมัติ',['redemption','id'=>$r->id,'status'=>'rejected'],['class'=>'btn btn-outline-danger','data-method'=>'post']) ?></div></td></tr><?php endforeach; ?></tbody></table></div></div></div></section>
</div></div>
<?php
$this->registerJs(<<<'JS'
var target = window.location.hash;
if (target) {
    var trigger = document.querySelector('[data-bs-target="' + target + '"]');
    if (trigger && window.bootstrap) {
        bootstrap.Tab.getOrCreateInstance(trigger).show();
    }
}
JS);
?>
