<?php
use yii\helpers\Html;
$this->title='ตรวจสอบข้อมูลก่อนนำเข้า';
$this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock();
$this->beginBlock('page-action'); ?><?= $this->render('../_menu',['active'=>'strategy']) ?><?php $this->endBlock();
$summary=$batch->summary();
$this->registerCss('.pm-import-preview-text{max-width:48rem}');
?>
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h2 class="h5 mb-1">ผลการอ่านไฟล์ <?= Html::encode($batch->original_name) ?></h2><p class="text-muted mb-0">ตรวจสอบรายการเตือนก่อนยืนยันนำเข้า</p></div><span class="badge bg-warning-subtle text-warning align-self-start">รอตรวจสอบ</span></div>
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">ชีตที่อ่าน</div><div class="fs-3 fw-bold"><?= (int)($summary['sheets']??0) ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">รายการทั้งหมด</div><div class="fs-3 fw-bold"><?= (int)$batch->total_rows ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">พร้อมนำเข้า</div><div class="fs-3 fw-bold text-success"><?= (int)$batch->valid_rows ?></div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">มีคำเตือน</div><div class="fs-3 fw-bold text-warning"><?= (int)$batch->error_rows ?></div></div></div></div></div>
<div class="card border-0 shadow-sm overflow-hidden"><div class="card-header bg-body-tertiary fw-semibold">ตัวอย่างข้อมูล 100 รายการแรก</div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-4">ตำแหน่ง</th><th>เป้าประสงค์/ตัวชี้วัด</th><th>ผลตรวจ</th></tr></thead><tbody><?php foreach(array_slice($rows,0,100) as $row):$p=$row->payload(); ?><tr><td class="ps-4"><div class="fw-semibold"><?= Html::encode($row->sheet_name) ?></div><div class="small text-muted">แถว <?= (int)$row->row_no ?></div></td><td><div><?= Html::encode($p['indicator']['code'].' '.$p['indicator']['name']) ?></div><div class="pm-import-preview-text small text-muted text-truncate"><?= Html::encode($p['goal']['name']) ?></div></td><td><?php if($row->status==='valid'): ?><span class="badge bg-success-subtle text-success">พร้อม</span><?php else: ?><span class="badge bg-warning-subtle text-warning"><?= Html::encode(implode(', ',$row->errors())) ?></span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="card-footer bg-body d-flex flex-column flex-sm-row justify-content-between gap-2 p-3"><?= Html::a('ยกเลิกชุดนำเข้า',['cancel','id'=>$batch->id],['class'=>'btn btn-outline-danger','data-method'=>'post','data-confirm'=>'ยกเลิกชุดนำเข้านี้?']) ?><?= Html::a('<i data-lucide="database-zap" class="me-1"></i> ยืนยันนำเข้า',['commit','id'=>$batch->id],['class'=>'btn btn-primary','data-method'=>'post','data-confirm'=>'ยืนยันนำข้อมูลทั้งหมดเข้าทะเบียนฉบับร่าง?']) ?></div></div>
