<?php use yii\helpers\Html; use app\modules\filemanager\components\FileManagerHelper; ?>
<style>
body{font-family:garuda;color:#1e293b;font-size:11pt;line-height:1.65}.cover{height:245mm;background:#123b70;color:#fff;padding:28mm 22mm;box-sizing:border-box}.cover .type{display:inline-block;border:1px solid #a9c8ef;padding:3mm 5mm;font-size:11pt}.cover h1{font-size:30pt;line-height:1.3;margin:25mm 0 8mm}.cover .objective{font-size:14pt;color:#dbeafe}.cover .meta{margin-top:35mm;border-top:1px solid #5c82ad;padding-top:8mm}.section-title{color:#123b70;font-size:20pt;border-bottom:2px solid #123b70;padding-bottom:3mm}.info{width:100%;border-collapse:collapse;margin:6mm 0 12mm}.info td{padding:3mm;border-bottom:1px solid #dbe3ec}.step{page-break-before:always}.step-head{background:#123b70;color:#fff;padding:6mm}.step-no{font-size:11pt}.step h2{font-size:21pt;margin:1mm 0}.content{padding:7mm 2mm}.caution{margin-top:7mm;background:#fff7db;border:1px solid #e3bd55;padding:5mm}.step-image{margin-top:8mm;text-align:center}.step-image img{max-width:165mm;max-height:105mm}.caption{font-size:9pt;color:#64748b;margin-top:2mm}
</style>
<div class="cover"><span class="type"><?= Html::encode($model->document_type) ?> · คู่มือปฏิบัติงาน</span><h1><?= Html::encode($model->title) ?></h1><p class="objective"><?= Html::encode($model->objective) ?></p><div class="meta"><strong><?= Html::encode($model->document_no) ?></strong><br>ฉบับที่ <?= number_format($model->current_revision) ?><br><?= Html::encode($model->organization ? $model->organization->name : 'โรงพยาบาล') ?></div></div>
<pagebreak />
<h1 class="section-title">ข้อมูลเอกสาร</h1><table class="info"><tr><td width="32%"><strong>รหัสเอกสาร</strong></td><td><?= Html::encode($model->document_no) ?></td></tr><tr><td><strong>หมวดหมู่</strong></td><td><?= Html::encode($model->category) ?></td></tr><tr><td><strong>วัตถุประสงค์</strong></td><td><?= nl2br(Html::encode($model->objective)) ?></td></tr><tr><td><strong>ขอบเขต</strong></td><td><?= nl2br(Html::encode($model->scope ?: '-')) ?></td></tr><tr><td><strong>วันที่ทบทวน</strong></td><td><?= $model->review_date ? Yii::$app->formatter->asDate($model->review_date, 'long') : '-' ?></td></tr></table>
<h2 class="section-title">สารบัญขั้นตอน</h2><ol><?php foreach ($model->steps as $step): ?><li><?= Html::encode($step->title) ?></li><?php endforeach; ?></ol>
<?php foreach ($model->steps as $index => $step): ?><div class="step"><div class="step-head"><div class="step-no">ขั้นตอนที่ <?= $index + 1 ?></div><h2><?= Html::encode($step->title) ?></h2></div><div class="content"><p><?= nl2br(Html::encode($step->description)) ?></p><?php if ($step->caution): ?><div class="caution"><strong>ข้อควรระวัง</strong><br><?= nl2br(Html::encode($step->caution)) ?></div><?php endif; ?><?php foreach ($step->media as $media): ?><?php if ($media->media_type === 'image'): ?><?php $imagePath = $media->upload_id ? FileManagerHelper::getFilePath($media->upload_id) : (strpos($media->file_path, '/') === 0 ? Yii::getAlias('@webroot') . $media->file_path : $media->file_path); ?><?php if ($imagePath): ?><div class="step-image"><img src="<?= Html::encode($imagePath) ?>"><div class="caption"><?= Html::encode($media->file_name) ?></div></div><?php endif; ?><?php endif; ?><?php endforeach; ?></div></div><?php endforeach; ?>
