<?php
use yii\helpers\Html;
$employee = $row['employee_snapshot'];
$calculation = $row['calculation_snapshot'];
$thaiMonths = [1 => 'มกราคม', 2 => 'กุมภาพันธ์', 3 => 'มีนาคม', 4 => 'เมษายน', 5 => 'พฤษภาคม', 6 => 'มิถุนายน', 7 => 'กรกฎาคม', 8 => 'สิงหาคม', 9 => 'กันยายน', 10 => 'ตุลาคม', 11 => 'พฤศจิกายน', 12 => 'ธันวาคม'];
$periodParts = explode('-', (string) $row['period_code']);
$periodLabel = ($thaiMonths[(int) ($periodParts[1] ?? 0)] ?? $row['period_code']) . ' ' . ((int) ($periodParts[0] ?? 0) + 543);
$organizationName = trim((string) ($organization['company_name'] ?? '')) ?: 'ไม่ระบุหน่วยงาน';
$createdTimestamp = strtotime((string) ($row['period_created_at'] ?? ''));
$issuedDate = $createdTimestamp ? date('d/m/', $createdTimestamp) . ((int) date('Y', $createdTimestamp) + 543) : '—';
$formatThaiDate = static function ($value): string {
    $timestamp = $value ? strtotime((string) $value) : false;
    return $timestamp ? date('d/m/', $timestamp) . ((int) date('Y', $timestamp) + 543) : '—';
};
?>
<article class="card border shadow-sm payslip payslip-preview-sheet"><div class="card-body p-4 p-lg-5">
<header class="payslip-heading border-bottom pb-3 mb-3"><div class="row g-3 align-items-start"><div class="col-sm-7"><div class="d-flex align-items-center gap-3"><div class="d-inline-flex flex-shrink-0 align-items-center justify-content-center rounded-3 bg-primary text-white" style="width:48px;height:48px"><i class="bi bi-building fs-4" aria-hidden="true"></i></div><div><h5 class="mb-1"><?= Html::encode($organizationName) ?></h5><div class="text-body-secondary small">เอกสารแจ้งรายละเอียดการจ่ายเงิน</div></div></div></div><div class="col-sm-5 text-sm-end"><h4 class="text-primary mb-1">สลิป<?= Html::encode($types[$row['period_type']] ?? 'เงินเดือน') ?></h4><strong>ประจำเดือน <?= Html::encode($periodLabel) ?></strong></div></div></header>
<section class="row g-3 mb-4"><div class="col-md-7"><div class="h-100 rounded-3 bg-body-tertiary p-3"><div class="small fw-semibold text-primary mb-2">ข้อมูลผู้รับเงิน</div><div class="row g-2"><div class="col-12"><span class="text-body-secondary small">ชื่อ–นามสกุล</span><strong class="d-block"><?= Html::encode($employee['full_name'] ?? 'ไม่ระบุชื่อ') ?></strong></div><div class="col-sm-6"><span class="text-body-secondary small">เลขประชาชน</span><strong class="d-block font-monospace"><?= Html::encode($employee['cid'] ?? '—') ?></strong></div><div class="col-sm-6"><span class="text-body-secondary small">บัญชีรับเงิน</span><strong class="d-block"><?= !empty($employee['account_last4']) ? Html::encode(trim(($employee['bank_code'] ?? '') . ' •••• ' . $employee['account_last4'])) : '—' ?></strong></div></div></div></div><div class="col-md-5"><div class="h-100 rounded-3 border p-3"><div class="small fw-semibold text-primary mb-2">ข้อมูลรอบจ่าย</div><dl class="row small mb-0"><dt class="col-6 fw-normal text-body-secondary">ตั้งแต่</dt><dd class="col-6 text-end fw-semibold"><?= Html::encode($formatThaiDate($row['date_start'] ?? null)) ?></dd><dt class="col-6 fw-normal text-body-secondary">ถึงวันที่</dt><dd class="col-6 text-end fw-semibold"><?= Html::encode($formatThaiDate($row['date_end'] ?? null)) ?></dd><dt class="col-6 fw-normal text-body-secondary">วันที่จ่าย</dt><dd class="col-6 text-end fw-semibold mb-0"><?= Html::encode($formatThaiDate($row['pay_date'] ?? null)) ?></dd></dl></div></div></section>
<section class="table-responsive mb-3"><table class="table table-bordered align-middle payslip-lines mb-0"><thead class="table-light"><tr><th>รายรับ</th><th class="text-end">จำนวนเงิน (บาท)</th><th>รายการหัก</th><th class="text-end">จำนวนเงิน (บาท)</th></tr></thead><tbody><?php $earnings = $calculation['earnings'] ?? []; $deductions = $calculation['deductions'] ?? []; $lineCount = max(count($earnings), count($deductions), 1); for ($index = 0; $index < $lineCount; $index++): $earning = $earnings[$index] ?? null; $deduction = $deductions[$index] ?? null; ?><tr><td><?= $earning ? Html::encode($earning['name']) : '' ?></td><td class="text-end"><?= $earning ? number_format($earning['amount'], 2) : '' ?></td><td><?= $deduction ? Html::encode($deduction['name']) : '' ?></td><td class="text-end"><?= $deduction ? number_format($deduction['amount'], 2) : '' ?></td></tr><?php endfor; ?></tbody><tfoot class="table-light fw-semibold"><tr><td>รวมรายรับ</td><td class="text-end"><?= number_format($row['gross_amount'], 2) ?></td><td>รวมรายการหัก</td><td class="text-end"><?= number_format($row['deduction_amount'], 2) ?></td></tr></tfoot></table></section>
<div class="rounded-3 bg-primary-subtle text-primary-emphasis p-3 d-flex justify-content-between align-items-center"><strong>เงินรับสุทธิ</strong><strong class="fs-4"><?= number_format($row['net_amount'], 2) ?> บาท</strong></div>
<footer class="border-top mt-4 pt-3 row g-3 small"><div class="col-sm-7"><span class="text-body-secondary d-block">ออกโดย</span><strong><?= Html::encode($issuerName !== '' ? $issuerName : 'ไม่พบข้อมูลผู้สร้างรอบ') ?></strong><div class="text-body-secondary mt-1">วันที่ออกเอกสาร <?= Html::encode($issuedDate) ?></div></div><div class="col-sm-5 text-sm-center"><div class="payslip-signature-line mt-4 border-top pt-1 text-body-secondary">ลายมือชื่อผู้รับเงิน</div></div></footer>
</div></article>
