<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
$this->title = 'รายชื่อ: ' . $selectedItem['name'];
$this->beginBlock('page-title'); ?><div class="d-flex align-items-center gap-2"><i class="bi bi-people fs-4"></i><h4 class="mb-0"><?= Html::encode($this->title) ?></h4></div><?php $this->endBlock();
$this->beginBlock('sub-title'); ?>ตรวจสอบรายชื่อและจำนวนเงินของรายการนี้<?php $this->endBlock();
$this->beginBlock('page-action'); echo $this->render('@app/modules/finance/menu',['active'=>'payroll']); $this->endBlock();
?>
<?= $this->render('_menu',['active'=>$group==='compensation'?'compensation-income':($group==='deduction'?'monthly-expense':'monthly-income')]) ?>
<div aria-live="polite"><?php foreach(['success'=>'success','error'=>'danger'] as $flash=>$class):if(!Yii::$app->session->hasFlash($flash))continue;?><div class="alert alert-<?= $class ?>"><?= Html::encode(Yii::$app->session->getFlash($flash)) ?></div><?php endforeach;?></div>
<section class="card shadow-sm">
<div class="card-header bg-body px-3 px-md-4 py-3 d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h5 class="mb-1"><?= Html::encode($selectedItem['name']) ?></h5><p class="mb-0 text-body-secondary"><?= number_format($pagination->totalCount) ?> คน · ยอดรวม <?= number_format($summaries[$itemTypeId]['total'] ?? 0,2) ?> บาท · ลากแถวหรือแก้เลขลำดับให้ตรงกับเอกสาร</p></div><div class="d-flex flex-wrap gap-2"><?= Html::a('กลับหน้ารายการ',['employee-items','group'=>$group],['class'=>'btn btn-outline-secondary']) ?><?= Html::a('<i class="bi bi-person-plus me-1"></i>เพิ่มรายชื่อ',['add-item-employees','group'=>$group,'item_type_id'=>$itemTypeId],['class'=>'btn btn-primary']) ?></div></div>
<div class="card-body border-bottom"><?= Html::beginForm(['employee-items'],'get',['class'=>'d-flex gap-2']) ?><input type="hidden" name="group" value="<?= Html::encode($group) ?>"><input type="hidden" name="item_type_id" value="<?= (int)$itemTypeId ?>"><input class="form-control" name="q" value="<?= Html::encode($q) ?>" placeholder="ค้นหาชื่อหรือเลขประชาชน"><button class="btn btn-outline-primary" type="submit">ค้นหา</button><?= Html::endForm() ?></div>
<?= Html::beginForm(['save-item-amounts'],'post') ?><input type="hidden" name="item_type_id" value="<?= (int)$itemTypeId ?>"><input type="hidden" name="group" value="<?= Html::encode($group) ?>">
<div class="table-responsive"><table class="table table-hover align-middle mb-0 payroll-employee-table"><thead><tr><th class="text-center payroll-order-cell">ลำดับ</th><th>ชื่อ–เลขประชาชน</th><th>ตำแหน่ง</th><th>หน่วยงาน</th><th>ประเภทบุคลากร</th><th>สถานะ</th><th>เลขบัญชีธนาคาร</th><th class="text-end payroll-money-cell">จำนวนเงิน</th><th class="text-end payroll-action-cell">จัดการ</th></tr></thead><tbody id="employee-order-list">
<?php foreach($employeeItems as $item):?><tr data-row-id="<?= (int)$item['id'] ?>"><td class="payroll-order-cell"><div class="d-flex align-items-center gap-1"><button class="btn btn-sm btn-outline-secondary drag-handle" type="button" draggable="true" title="ลากเพื่อจัดลำดับ" aria-label="ลาก <?= Html::encode($item['employee_name']) ?> เพื่อจัดลำดับ"><i class="bi bi-grip-vertical" aria-hidden="true"></i></button><input class="form-control form-control-sm text-center order-input payroll-order-input" type="number" min="1" name="orders[<?= (int)$item['id'] ?>]" value="<?= (int)$item['document_order'] ?>" required aria-label="ลำดับของ <?= Html::encode($item['employee_name']) ?>"></div></td><td><strong><?= Html::encode($item['employee_name']) ?></strong><div class="small text-body-secondary font-monospace"><?= Html::encode($item['cid']?:'ไม่พบเลขประชาชน') ?></div></td><td><?= Html::encode($item['position']) ?></td><td><?= Html::encode($item['department']) ?></td><td><?= Html::encode($item['employee_type']) ?></td><td><span class="badge <?= $item['employment_status']==='ปฏิบัติงาน'?'bg-success-subtle text-success-emphasis':'bg-secondary-subtle text-secondary-emphasis' ?>"><?= Html::encode($item['employment_status']) ?></span></td><td class="text-nowrap"><?= Html::encode($item['bank']) ?></td><td class="payroll-money-cell"><input class="form-control form-control-sm text-end money-input payroll-money-input" type="text" inputmode="decimal" value="<?= number_format($item['amount'],2) ?>" required data-hidden-id="amount-<?= (int)$item['id'] ?>" aria-label="จำนวนเงินของ <?= Html::encode($item['employee_name']) ?>"><input type="hidden" id="amount-<?= (int)$item['id'] ?>" name="amounts[<?= (int)$item['id'] ?>]" value="<?= number_format($item['amount'],2,'.','') ?>"></td><td class="text-end"><button class="btn btn-sm btn-outline-danger remove-item" type="button" title="เอาชื่อออก" aria-label="เอา <?= Html::encode($item['employee_name']) ?> ออกจากรายการ" data-action="<?= Html::encode(Yii::$app->urlManager->createUrl(['finance/payroll/remove-employee-item'])) ?>" data-id="<?= (int)$item['id'] ?>" data-name="<?= Html::encode($item['employee_name']) ?>"><i class="bi bi-trash" aria-hidden="true"></i></button></td></tr><?php endforeach;?>
<?php if(!$employeeItems):?><tr><td colspan="9" class="text-center text-body-secondary py-5">ไม่พบรายชื่อในรายการนี้</td></tr><?php endif;?></tbody></table></div>
<div class="card-footer bg-body d-flex align-items-center gap-3"><?= LinkPager::widget(['pagination'=>$pagination,'options'=>['class'=>'pagination mb-0'],'linkContainerOptions'=>['class'=>'page-item'],'linkOptions'=>['class'=>'page-link']]) ?><button class="btn btn-primary ms-auto" type="submit">บันทึก</button></div><?= Html::endForm() ?>
</section>

<form id="remove-form" method="post" class="d-none"><input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->csrfToken ?>"><input type="hidden" name="id"><input type="hidden" name="item_type_id" value="<?= (int)$itemTypeId ?>"><input type="hidden" name="group" value="<?= Html::encode($group) ?>"></form>
<?php $this->registerJs(<<<'JS'
function formatPayrollMoney(input){var value=Number(String(input.value).replace(/,/g,''));if(Number.isFinite(value)){input.value=value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});document.getElementById(input.dataset.hiddenId).value=value.toFixed(2);}}
document.querySelectorAll('.money-input').forEach(function(input){formatPayrollMoney(input);input.addEventListener('input',function(){var value=String(input.value).replace(/,/g,'');if(!isNaN(value)&&value!=='')document.getElementById(input.dataset.hiddenId).value=value;});input.addEventListener('blur',function(){formatPayrollMoney(input);});});
document.querySelectorAll('.remove-item').forEach(function(button){button.addEventListener('click',function(){if(!confirm('ยืนยันนำ '+button.dataset.name+' ออกจากรายการนี้?'))return;var form=document.getElementById('remove-form');form.action=button.dataset.action;form.querySelector('[name="id"]').value=button.dataset.id;form.submit();});});
var orderList=document.getElementById('employee-order-list'),dragged=null;if(orderList){orderList.querySelectorAll('tr[data-row-id]').forEach(function(row){var handle=row.querySelector('.drag-handle');handle.addEventListener('dragstart',function(){dragged=row;row.classList.add('opacity-50');});handle.addEventListener('dragend',function(){row.classList.remove('opacity-50');dragged=null;});row.addEventListener('dragover',function(event){event.preventDefault();if(!dragged||dragged===row)return;var box=row.getBoundingClientRect();orderList.insertBefore(dragged,event.clientY<box.top+box.height/2?row:row.nextSibling);var rows=Array.from(orderList.querySelectorAll('tr[data-row-id]')),start=Math.min.apply(null,rows.map(function(r){return Number(r.querySelector('.order-input').value)||1;}));rows.forEach(function(r,index){r.querySelector('.order-input').value=start+index;});});});}
JS); ?>
<?php $this->registerCss('.payroll-employee-table{min-width:1180px}.payroll-order-cell{width:5.5rem;min-width:5.5rem}.payroll-order-input{width:3rem;min-width:3rem;padding-left:.25rem;padding-right:.25rem}.payroll-money-cell{width:10rem;min-width:10rem}.payroll-money-input{width:9rem}.payroll-action-cell{width:4.5rem;min-width:4.5rem}'); ?>
