<?php

$sql = "SELECT i.RECORD_HEAD,i.RECORD_HEAD_USE,go.RECORD_GO_NAME,l.LOCATION_ORG_NAME,
v.RECORD_VEHICLE_NAME,
i.DATE_GO,
i.DATE_BACK,
i.DATE_TRAVEL_GO,
i.DATE_TRAVEL_BACK
FROM `grecord_index` i
LEFT JOIN grecord_go go ON go.RECORD_GO_ID = i.RECORD_GO_ID
LEFT JOIN grecord_org_location l ON l.LOCATION_ID = i.RECORD_LOCATION_ID
LEFT JOIN grecord_vehicle v ON v.RECORD_VEHICLE_ID = i.RECORD_VEHICLE_ID;";