<?php

use app\modules\filemanager\components\FileManagerHelper;
use app\modules\housing\models\AssetAssignment;
use app\modules\housing\models\Checkout;
use yii\helpers\Html;

$o=$model->occupancy;
$location=implode(' / ',array_filter([$o?->unit?->building?->name,$o?->unit?->floor?->name,$o?->unit?->name,$o?->room?->name]));
$this->title='เอกสารส่งคืน '.$model->checkout_no;
$this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock();
$this->beginBlock('page-action'); ?><?= $this->render('../_menu',['active'=>'checkout']) ?><?php $this->endBlock();
?>
<div class="container-fluid py-3" style="max-width:1120px">
<?php foreach(['success','warning','error'] as $type):if(Yii::$app->session->hasFlash($type)):?><div class="alert alert-<?= $type==='error'?'danger':$type ?>"><?= Html::encode(Yii::$app->session->getFlash($type)) ?></div><?php endif;endforeach;?>
<div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><?= Html::a('กลับไปรายการ',['index'],['class'=>'btn btn-outline-secondary']) ?><div class="d-flex gap-2"><?php if($model->status===Checkout::STATUS_REQUESTED):?><?= Html::a('บันทึกผลตรวจ',['prepare','id'=>$model->id],['class'=>'btn btn-primary']) ?><?php endif;?><?= Html::a('พิมพ์เอกสาร',['print','id'=>$model->id],['class'=>'btn btn-outline-secondary','target'=>'_blank']) ?></div></div>
<div class="row g-3"><div class="col-lg-8">
<section class="card shadow-sm mb-3"><div class="card-header bg-body d-flex justify-content-between"><strong>ข้อมูลการส่งคืน</strong><span class="badge bg-warning-subtle text-warning-emphasis"><?= Html::encode(Checkout::statusOptions()[$model->status]) ?></span></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">ผู้ส่งคืน</dt><dd class="col-sm-8"><?= Html::encode($model->resident_name) ?></dd><dt class="col-sm-4">บ้านพัก/ห้องพัก</dt><dd class="col-sm-8"><?= Html::encode($location) ?></dd><dt class="col-sm-4">วันที่ต้องการคืน</dt><dd class="col-sm-8"><?= Yii::$app->formatter->asDate($model->requested_date,'php:d/m/Y') ?></dd><dt class="col-sm-4">วันที่ตรวจรับคืน</dt><dd class="col-sm-8"><?= $model->checkout_date?Yii::$app->formatter->asDate($model->checkout_date,'php:d/m/Y'):'ยังไม่ตรวจ' ?></dd><dt class="col-sm-4">เหตุผล</dt><dd class="col-sm-8"><?= nl2br(Html::encode($model->move_out_reason)) ?></dd><dt class="col-sm-4">มิเตอร์ไฟฟ้า / น้ำ</dt><dd class="col-sm-8"><?= $model->electric_meter_value??'—' ?> / <?= $model->water_meter_value??'—' ?></dd><dt class="col-sm-4">ยอดค้างชำระ ณ วันตรวจ</dt><dd class="col-sm-8 fw-semibold <?= (float)$model->outstanding_amount>0?'text-danger':'text-success' ?>"><?= Yii::$app->formatter->asDecimal($model->outstanding_amount,2) ?> บาท</dd></dl></div></section>
<section class="card shadow-sm mb-3"><div class="card-header bg-body fw-semibold">อุปกรณ์และของใช้</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>รายการ</th><th>จำนวน</th><th>สภาพ</th><th>หมายเหตุ</th></tr></thead><tbody><?php foreach($model->assetItems() as $item):?><tr><td><?= Html::encode($item['item_name']) ?></td><td><?= Html::encode($item['quantity'].' '.$item['unit_name']) ?></td><td><?= Html::encode(AssetAssignment::conditionOptions()[$item['condition']]??$item['condition']) ?></td><td><?= Html::encode($item['note']?:'—') ?></td></tr><?php endforeach;?><?php if($model->assetItems()===[]):?><tr><td colspan="4" class="text-center text-body-secondary py-3">ไม่มีรายการอุปกรณ์</td></tr><?php endif;?></tbody></table></div></section>
<section class="card shadow-sm"><div class="card-header bg-body fw-semibold">สภาพและรูปถ่าย</div><div class="card-body"><p><?= nl2br(Html::encode($model->condition_note?:'ยังไม่มีบันทึกผลตรวจ')) ?></p><?php if($photos):?><div class="row g-2"><?php foreach($photos as $photo):?><div class="col-6 col-md-4"><img src="<?= Html::encode(FileManagerHelper::getImg($photo->id)) ?>" class="w-100 rounded border" style="aspect-ratio:4/3;object-fit:cover" alt="ภาพสภาพวันส่งคืน"></div><?php endforeach;?></div><?php endif;?></div></section>
</div><aside class="col-lg-4"><div class="card shadow-sm"><div class="card-header bg-body fw-semibold">การลงนาม</div><div class="card-body"><div class="mb-3"><small class="text-body-secondary d-block">ผู้ส่งคืน</small><strong><?= Html::encode($model->resident_name) ?></strong><div class="small <?= $model->resident_signed_at?'text-success':'text-body-secondary' ?>"><?= $model->resident_signed_at?'ลงนามแล้ว '.Yii::$app->formatter->asDatetime($model->resident_signed_at,'php:d/m/Y H:i'):'ยังไม่ลงนาม' ?></div></div><div class="mb-3"><small class="text-body-secondary d-block">ผู้ตรวจรับคืน</small><strong><?= Html::encode($model->inspected_by_name?:'ยังไม่กำหนด') ?></strong><div class="small <?= $model->inspector_signed_at?'text-success':'text-body-secondary' ?>"><?= $model->inspector_signed_at?'ลงนามแล้ว '.Yii::$app->formatter->asDatetime($model->inspector_signed_at,'php:d/m/Y H:i'):'ยังไม่ลงนาม' ?></div></div>
<?php if($model->status===Checkout::STATUS_AWAITING_STAFF):?><?= Html::beginForm(['sign-inspector','id'=>$model->id],'post',['class'=>'d-grid gap-3']) ?><label class="form-check"><input class="form-check-input" type="checkbox" name="inspector_ack" value="1" required><span class="form-check-label">ตรวจรับบ้านพัก อุปกรณ์ และข้อมูลมิเตอร์ครบแล้ว</span></label><button class="btn btn-primary">ลงนามรับคืนและปิดการเข้าพัก</button><?= Html::endForm() ?><?php elseif($model->status===Checkout::STATUS_COMPLETED):?><div class="alert alert-success mb-0">ส่งคืนและปิดการเข้าพักเรียบร้อยแล้ว</div><?php else:?><div class="alert alert-info mb-0"><?= $model->status===Checkout::STATUS_REQUESTED?'กรุณาบันทึกผลตรวจก่อน':'รอผู้พักตรวจเอกสารและลงนามส่งคืน' ?></div><?php endif;?>
</div></div></aside></div></div>
