<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$labels=['indicator'=>'ตัวชี้วัด','value'=>'ค่าเป้าหมายรายปี','factor'=>'ปัจจัยความสำเร็จ/RCA','measure'=>'มาตรการ','program'=>'แผนงานหลัก'];
$this->title=($model->isNewRecord?'เพิ่ม':'แก้ไข').$labels[$type];
$this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock();
$this->beginBlock('page-action'); ?><?= $this->render('../_menu',['active'=>$type==='program'?'program':'indicator']) ?><?php $this->endBlock();
$form=ActiveForm::begin();
?>
<div class="mb-4"><h2 class="h5 mb-1"><?= Html::encode($this->title) ?></h2><p class="text-muted mb-0"><?= Html::encode($plan->name) ?> · รุ่น <?= (int)$plan->version ?></p></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="row g-3">
<?php if($type==='indicator'): ?><div class="col-12 col-md-4"><?= $form->field($model,'code')->textInput() ?></div><div class="col-12 col-md-4"><?= $form->field($model,'level')->dropDownList($model::levelList()) ?></div><div class="col-12 col-md-4"><?= $form->field($model,'unit')->textInput() ?></div><div class="col-12"><?= $form->field($model,'goal_id')->dropDownList($goals,['prompt'=>'ไม่ผูกเป้าประสงค์']) ?></div><div class="col-12"><?= $form->field($model,'name')->textarea(['rows'=>3]) ?></div><div class="col-12"><?= $form->field($model,'calculation')->textarea(['rows'=>2]) ?></div>
<?php elseif($type==='value'): ?><div class="col-12 col-md-3"><?= $form->field($model,'fiscal_year')->textInput(['type'=>'number']) ?></div><div class="col-12 col-md-3"><?= $form->field($model,'operator')->dropDownList(['>='=>'ไม่น้อยกว่า','<='=>'ไม่เกิน','='=>'เท่ากับ']) ?></div><div class="col-12 col-md-3"><?= $form->field($model,'baseline_value')->textInput(['type'=>'number','step'=>'any']) ?></div><div class="col-12 col-md-3"><?= $form->field($model,'target_value')->textInput(['type'=>'number','step'=>'any']) ?></div><div class="col-12 col-md-3"><?= $form->field($model,'actual_value')->textInput(['type'=>'number','step'=>'any']) ?></div><div class="col-12"><?= $form->field($model,'note')->textarea(['rows'=>2]) ?></div>
<?php elseif($type==='measure'): ?><div class="col-12 col-md-4"><?= $form->field($model,'code')->textInput() ?></div><div class="col-12 col-md-4"><?= $form->field($model,'fiscal_year')->textInput(['type'=>'number']) ?></div><div class="col-12"><?= $form->field($model,'name')->textarea(['rows'=>3]) ?></div>
<?php elseif($type==='factor'): ?><div class="col-12 col-md-4"><?= $form->field($model,'code')->textInput() ?></div><div class="col-12 col-md-4"><?= $form->field($model,'factor_type')->dropDownList(['success_factor'=>'ปัจจัยความสำเร็จ','rca'=>'RCA']) ?></div><div class="col-12"><?= $form->field($model,'name')->textarea(['rows'=>3]) ?></div>
<?php else: ?><div class="col-12 col-md-4"><?= $form->field($model,'code')->textInput() ?></div><div class="col-12 col-md-4"><?= $form->field($model,'fiscal_year')->textInput(['type'=>'number']) ?></div><div class="col-12"><?= $form->field($model,'measure_id')->dropDownList($measures,['prompt'=>'ไม่ผูกมาตรการ']) ?></div><div class="col-12"><?= $form->field($model,'name')->textarea(['rows'=>3]) ?></div><div class="col-12"><?= $form->field($model,'owner_text')->textInput(['maxlength'=>true]) ?></div><?php endif; ?>
<?php if($type!=='value'): ?><div class="col-6 col-md-2"><?= $form->field($model,'sort_order')->textInput(['type'=>'number','min'=>0]) ?></div><div class="col-12"><?= $form->field($model,'is_active')->checkbox() ?></div><?php endif; ?>
</div></div><div class="card-footer bg-body d-flex justify-content-between p-3"><?= Html::a('ยกเลิก',['index','type'=>$type,'planId'=>$plan->id],['class'=>'btn btn-outline-secondary']) ?><?= Html::submitButton('บันทึก',['class'=>'btn btn-primary']) ?></div></div><?php ActiveForm::end(); ?>
