<?php
use app\components\ThaiDateHelper;
use app\modules\iacRisk\services\Pk5Service;
use yii\helpers\Html;
$groups=[];foreach($rows as $row){$id=(int)$row->org_unit_id;if(!isset($groups[$id]))$groups[$id]=['id'=>$id,'name'=>$row->orgUnit?->name?:'หน่วยงาน #'.$id,'rows'=>[]];$groups[$id]['rows'][]=$row;}
$periodName=$period?->name?:'รอบรายงาน';$periodRange=$period?ThaiDateHelper::formatThaiDateRange($period->start_date,$period->end_date,'long'):'';
?>
<style>body{font-family:thsarabunnew;font-size:11pt;color:#000}.header{text-align:center;line-height:1.15}.unit{font-size:14pt;font-weight:bold}.report-title{font-size:13pt}.period{font-size:12pt}.form-code{text-align:right;font-weight:bold;font-size:12pt;margin-bottom:1mm}.report{width:100%;border-collapse:collapse;table-layout:fixed}.report th,.report td{border:.25mm solid #000;padding:1.2mm;vertical-align:top;line-height:1.1}.report th{text-align:center;font-weight:bold;background:#ddd}.signature{width:45%;margin-left:52%;margin-top:8mm;text-align:center;font-size:12pt}.signature img{max-width:38mm;max-height:15mm}.signature div{margin-top:1mm}.page-break{page-break-before:always}</style>
<?php $first=true;foreach($groups as $group): ?><?php if(!$first): ?><div class="page-break"></div><?php endif;$first=false;$signer=$signers[$group['id']]??[]; ?>
<div class="header"><div class="unit">หน่วยงาน<?= Html::encode($group['name']) ?> <?= Html::encode($hospitalName) ?></div><div class="report-title">รายงานการประเมินผลการควบคุมภายใน</div><div class="period">สำหรับระยะเวลาการดำเนินงานสิ้นสุด <?= Html::encode($periodRange) ?></div></div><div class="form-code">ปค.5 หน่วยงานย่อย</div>
<table class="report"><thead><tr><th style="width:16%">(3)<br>ภารกิจตามกฎหมายที่จัดตั้งหน่วยงานของรัฐ หรือภารกิจตามแผนการดำเนินการ หรือภารกิจอื่น ๆ ที่สำคัญของหน่วยงานของรัฐ<br>วัตถุประสงค์</th><th style="width:14%">(4)<br>ความเสี่ยง</th><th style="width:14%">(5)<br>การควบคุมภายในที่มีอยู่</th><th style="width:12%">(6)<br>การประเมินผล<br>การควบคุมภายใน</th><th style="width:14%">(7)<br>ความเสี่ยง<br>ที่ยังมีอยู่</th><th style="width:16%">(8)<br>การปรับปรุง<br>การควบคุมภายใน</th><th style="width:14%">(9)<br>หน่วยงาน/บุคคล<br>ที่รับผิดชอบ</th></tr></thead><tbody><?php foreach($group['rows'] as $row): ?><tr><td><?= nl2br(Html::encode($row->mission_objective?:'—')) ?></td><td><?= nl2br(Html::encode($row->risk_name)) ?></td><td><?= nl2br(Html::encode($row->existing_control?:'—')) ?></td><td><?= Html::encode(Pk5Service::adequacyLabel($row->adequacy)) ?></td><td><?= nl2br(Html::encode($row->residual_risk?:'—')) ?></td><td><?= nl2br(Html::encode($row->improvement_plan?:'—')) ?></td><td><?= nl2br(Html::encode($row->responsible_person?:'—')) ?></td></tr><?php endforeach; ?></tbody></table>
<div class="signature"><div>ลงชื่อ</div><?php if(!empty($signer['signature'])): ?><div><img src="<?= Html::encode($signer['signature']) ?>" alt="ลายเซ็น"></div><?php else: ?><div>..............................................................</div><?php endif; ?><div>(<?= Html::encode($signer['name']??'หัวหน้าหน่วยงาน') ?>)</div><div>ตำแหน่ง <?= Html::encode($signer['position']??'หัวหน้าหน่วยงาน') ?></div><div>วันที่ <?= $period?Html::encode(ThaiDateHelper::formatThaiDate($period->end_date,'long')):'....................................' ?></div></div>
<?php endforeach; ?>
