<?php
use app\components\ThaiDateHelper;
use app\modules\iacRisk\models\RiskFollowup;
use yii\helpers\Html;
$groups=[];foreach($items as $item){$id=(int)$item->org_unit_id;if(!isset($groups[$id]))$groups[$id]=['name'=>$item->orgUnit?->name?:'หน่วยงาน #'.$id,'items'=>[]];$groups[$id]['items'][]=$item;}$symbols=RiskFollowup::statusSymbols();
?>
<style>body{font-family:thsarabunnew;font-size:10.5pt;color:#000}.header{text-align:center;line-height:1.15}.header .hospital{font-size:14pt;font-weight:bold}.header .title{font-size:13pt;font-weight:bold}.form-code{text-align:right;font-size:12pt;font-weight:bold}.report{width:100%;border-collapse:collapse;table-layout:fixed}.report th,.report td{border:.25mm solid #000;padding:1.1mm;vertical-align:top;line-height:1.1}.report th{text-align:center;background:#dce6f1;font-weight:bold}.unit td{background:#e7f1dc;font-weight:bold;font-size:11pt}.status{text-align:center;font-size:16pt}.legend{margin-top:6mm;width:45%;font-size:11pt}.signature{width:43%;margin-left:55%;margin-top:7mm;text-align:center;font-size:11pt}.signature img{max-width:38mm;max-height:15mm}</style>
<div class="form-code">แบบติดตาม ปค.5</div><div class="header"><div class="hospital"><?= Html::encode($hospitalName) ?></div><div class="title">รายงานการประเมินผลการควบคุมภายใน</div><div>สำหรับระยะเวลาการดำเนินงานสิ้นสุด <?= Html::encode(ThaiDateHelper::formatThaiDate($period->end_date,'long')) ?></div></div>
<table class="report"><thead><tr><th style="width:18%">(3)<br>ภารกิจตามกฎหมายที่จัดตั้งหน่วยงานของรัฐ หรือภารกิจตามแผนการดำเนินการ หรือภารกิจอื่น ๆ ที่สำคัญของหน่วยงานของรัฐ/วัตถุประสงค์</th><th style="width:13%">(4)<br>การควบคุมภายในที่มีอยู่</th><th style="width:15%">(5)<br>ความเสี่ยงที่ยังมีอยู่</th><th style="width:14%">(6)<br>การปรับปรุงการควบคุมภายใน</th><th style="width:14%">(7)<br>หน่วยงานที่รับผิดชอบ</th><th style="width:11%">(8)<br>สถานะดำเนินการ</th><th style="width:15%">(9)<br>วิธีติดตามและสรุปผลการประเมิน<br>ข้อคิดเห็น</th></tr></thead><tbody><?php foreach($groups as $group): ?><tr class="unit"><td colspan="7"><?= Html::encode($group['name']) ?></td></tr><?php foreach($group['items'] as $item): ?><tr><td><?= nl2br(Html::encode($item->mission_objective?:'—')) ?></td><td><?= nl2br(Html::encode($item->existing_control?:'—')) ?></td><td><?= nl2br(Html::encode($item->residual_risk?:'—')) ?></td><td><?= nl2br(Html::encode($item->improvement_plan)) ?></td><td><?= nl2br(Html::encode($item->responsible_person?:'—')) ?></td><td class="status"><?= Html::encode($symbols[$item->status_code]??'X') ?></td><td><?= nl2br(Html::encode(implode("\n",array_filter([$item->followup_method,$item->result_summary,$item->comment]))?:'—')) ?></td></tr><?php endforeach; ?><?php endforeach; ?></tbody></table>
<div class="legend"><strong>สถานะดำเนินการ</strong><br>☆ = ดำเนินการแล้ว เสร็จตามกำหนด<br>/ = ดำเนินการแล้ว เสร็จล่าช้ากว่ากำหนด<br>X = ยังไม่ดำเนินการ<br>O = อยู่ระหว่างดำเนินการ</div><div class="signature"><div>ลงชื่อ</div><?php if($signature): ?><div><img src="<?= Html::encode($signature) ?>" alt="ลายเซ็น"></div><?php else: ?><div>..............................................................</div><?php endif; ?><div>(<?= Html::encode($director['fullname']?:'ผู้อำนวยการโรงพยาบาล') ?>)</div><div>ตำแหน่ง <?= Html::encode($director['position_name']?:'ผู้อำนวยการโรงพยาบาล') ?></div><div>วันที่ <?= Html::encode(ThaiDateHelper::formatThaiDate($period->end_date,'long')) ?></div></div>
