<?php
use app\modules\iacRisk\models\Csa;use yii\helpers\Html;
$this->title='CSA: '.$model->process_name_snapshot;$labels=Csa::statusLabels();
?>
<?php $this->beginBlock('page-title'); ?>CSA<?php $this->endBlock(); ?>
<?php $this->beginBlock('sub-title'); ?><?= Html::encode($model->process_name_snapshot) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('page-action'); ?><div class="d-flex gap-2"><?= Html::a('กลับรายการ CSA',['csa'],['class'=>'btn btn-outline-secondary']) ?><?= Html::a('<i class="bi bi-file-earmark-pdf me-1"></i> Flow chart PDF',['csa-flowchart-pdf','id'=>$model->id],['class'=>'btn btn-outline-primary','target'=>'_blank','rel'=>'noopener']) ?></div><?php $this->endBlock(); ?>
<div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'csa','context'=>$context]) ?></div>
<?php if($model->return_note): ?><div class="alert alert-danger"><div class="fw-semibold">เหตุผลที่ส่งกลับแก้ไข</div><div class="mt-1"><?= nl2br(Html::encode($model->return_note)) ?></div></div><?php endif; ?>
<section class="card bg-body border shadow-sm mb-3"><div class="card-body"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h2 class="h6 fw-semibold mb-1">ความพร้อมและการรับรอง</h2><div class="small text-body-secondary">มี <?= (int)$readiness['step_count'] ?> ขั้นตอน · <?= (int)$readiness['risk_count'] ?> ความเสี่ยง</div></div><div class="d-flex flex-wrap gap-2"><?php if($canConfirm): ?><?= Html::beginForm(['confirm-csa','id'=>$model->id],'post',['class'=>'d-inline']) ?><?= Html::submitButton('ผู้จัดทำยืนยัน',['class'=>'btn btn-primary','disabled'=>!$readiness['ready'],'data-confirm'=>'ยืนยันว่าข้อมูล CSA ครบถ้วน?']) ?><?= Html::endForm() ?><?php endif; ?><?php if($canSendHead): ?><?= Html::beginForm(['send-csa-head','id'=>$model->id],'post',['class'=>'d-inline']) ?><?= Html::submitButton('ส่งหัวหน้าหน่วยงาน',['class'=>'btn btn-primary','data-confirm'=>'ส่งให้หัวหน้าหน่วยงานรับรอง?']) ?><?= Html::endForm() ?><?php endif; ?><?php if($canHeadAct): ?><?= Html::beginForm(['approve-csa','id'=>$model->id],'post',['class'=>'d-inline']) ?><?= Html::submitButton('รับรอง CSA',['class'=>'btn btn-success','data-confirm'=>'รับรองและล็อก CSA ฉบับนี้?']) ?><?= Html::endForm() ?><button class="btn btn-outline-danger" type="button" data-bs-toggle="collapse" data-bs-target="#return-csa">ส่งกลับแก้ไข</button><?php endif; ?></div></div><?php if(!$readiness['ready']&&in_array($model->status,[Csa::STATUS_DRAFT,Csa::STATUS_RETURNED],true)): ?><div class="alert alert-warning mt-3 mb-0"><div class="fw-semibold">ยังยืนยันไม่ได้</div><ul class="mb-0 mt-2"><?php foreach($readiness['errors'] as $error): ?><li><?= Html::encode($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?><?php if($canHeadAct): ?><div class="collapse mt-3" id="return-csa"><form method="post" action="<?= \yii\helpers\Url::to(['return-csa','id'=>$model->id]) ?>"><input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->csrfToken ?>"><label class="form-label fw-semibold">เหตุผลที่ส่งกลับ</label><?= Html::textarea('return_note','',['class'=>'form-control','rows'=>2,'required'=>true]) ?><div class="d-flex justify-content-end mt-2"><?= Html::submitButton('ยืนยันส่งกลับ',['class'=>'btn btn-danger']) ?></div></form></div><?php endif; ?></div></section>
<section class="card bg-body border shadow-sm mb-3"><div class="card-header bg-body-tertiary border-bottom d-flex justify-content-between gap-3"><div><h2 class="h5 fw-semibold mb-1"><?= Html::encode($model->process_name_snapshot) ?></h2><p class="small text-body-secondary mb-0">Snapshot จาก Service Profile · CSA Revision <?= (int)$model->revision_no ?></p></div><span class="badge bg-primary-subtle text-primary-emphasis align-self-start"><?= Html::encode($labels[$model->status]??$model->status) ?></span></div><div class="card-body"><?php if($canEdit): ?><form method="post" action="<?= \yii\helpers\Url::to(['save-csa-snapshot','id'=>$model->id]) ?>"><input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->csrfToken ?>"><div class="row g-3"><div class="col-12"><label class="form-label fw-semibold">ชื่อกระบวนงานที่ใช้ใน CSA</label><?= Html::textInput('process_name_snapshot',$model->process_name_snapshot,['class'=>'form-control','maxlength'=>500,'required'=>true]) ?></div><div class="col-12"><label class="form-label fw-semibold">วัตถุประสงค์ที่ใช้ใน CSA</label><?= Html::textarea('objective_snapshot',$model->objective_snapshot,['class'=>'form-control','rows'=>3]) ?></div></div><div class="d-flex justify-content-end mt-3"><?= Html::submitButton('บันทึก snapshot',['class'=>'btn btn-outline-primary']) ?></div></form><?php else: ?><div class="small text-body-secondary mb-1">วัตถุประสงค์</div><div><?= nl2br(Html::encode($model->objective_snapshot?:'—')) ?></div><?php endif; ?></div></section>
<section class="card bg-body border shadow-sm"><div class="card-header bg-body-tertiary border-bottom d-flex flex-column flex-sm-row justify-content-between gap-3"><div><h2 class="h5 fw-semibold mb-1">ขั้นตอนการปฏิบัติงาน</h2><p class="small text-body-secondary mb-0">ขั้นตอนทั้งหมดใช้สร้าง Flow chart รวมทั้งขั้นตอนที่ไม่มีความเสี่ยง</p></div><?php if($canEdit): ?><button class="btn btn-primary align-self-start" type="button" data-bs-toggle="collapse" data-bs-target="#add-csa-step"><i class="bi bi-plus-lg me-1"></i> เพิ่มขั้นตอน</button><?php endif; ?></div>
<?php if($canEdit): ?><div class="collapse border-bottom" id="add-csa-step"><div class="card-body bg-body-tertiary"><?= $this->render('_step_form',['csa'=>$model,'step'=>null]) ?></div></div><?php endif; ?>
<div class="list-group list-group-flush"><?php foreach($model->steps as $step): ?><article class="list-group-item bg-body p-3 p-md-4"><div class="d-flex justify-content-between gap-3"><div class="d-flex gap-3"><span class="badge text-bg-primary rounded-pill align-self-start"><?= (int)($step->sequence/10) ?></span><div><h3 class="h6 fw-semibold mb-1"><?= Html::encode($step->name) ?></h3><div class="small text-body-secondary"><?= Html::encode($step->responsible?:'ไม่ระบุผู้รับผิดชอบ') ?><?php if($step->duration): ?> · <?= Html::encode($step->duration) ?><?php endif; ?></div></div></div><?php if($canEdit): ?><div class="dropdown"><button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown">จัดการ</button><ul class="dropdown-menu dropdown-menu-end"><li><button class="dropdown-item" type="button" data-bs-toggle="collapse" data-bs-target="#edit-step-<?= (int)$step->id ?>">แก้ไขขั้นตอน</button></li><li><button class="dropdown-item" type="button" data-bs-toggle="collapse" data-bs-target="#add-risk-<?= (int)$step->id ?>">เพิ่มความเสี่ยง</button></li><li><hr class="dropdown-divider"></li><li><?= Html::a('ลบขั้นตอน',['delete-step','id'=>$step->id],['class'=>'dropdown-item text-danger','data-method'=>'post','data-confirm'=>'ลบขั้นตอนนี้พร้อมความเสี่ยงทั้งหมด?']) ?></li></ul></div><?php endif; ?></div><?php if($step->detail): ?><p class="mt-3 mb-1"><?= nl2br(Html::encode($step->detail)) ?></p><?php endif; ?><?php if($step->control_point): ?><div class="alert alert-info mt-3 mb-0"><strong>จุดควบคุม:</strong> <?= nl2br(Html::encode($step->control_point)) ?></div><?php endif; ?>
<?php if($canEdit): ?><div class="collapse mt-3" id="edit-step-<?= (int)$step->id ?>"><div class="border rounded-3 p-3 bg-body-tertiary"><?= $this->render('_step_form',['csa'=>$model,'step'=>$step]) ?></div></div><div class="collapse mt-3" id="add-risk-<?= (int)$step->id ?>"><div class="border rounded-3 p-3 bg-body-tertiary"><?= $this->render('_risk_form',['step'=>$step,'risk'=>null]) ?></div></div><?php endif; ?>
<div class="d-flex flex-column gap-3 mt-3"><?php foreach($step->risks as $risk): ?><section class="border rounded-3 p-3"><div class="d-flex justify-content-between gap-3"><div><div class="small text-danger-emphasis fw-semibold">ความเสี่ยง <?= (int)($risk->sequence/10) ?></div><h4 class="h6 fw-semibold mt-1 mb-0"><?= Html::encode($risk->name) ?></h4></div><span class="badge <?= $risk->adequacy==='adequate'?'bg-success-subtle text-success-emphasis':($risk->adequacy==='inadequate'?'bg-danger-subtle text-danger-emphasis':'bg-secondary-subtle text-secondary-emphasis') ?> align-self-start"><?= Html::encode(\app\modules\iacRisk\models\CsaRisk::adequacyLabels()[$risk->adequacy]??$risk->adequacy) ?></span></div><div class="row g-3 mt-1"><div class="col-md-6"><div class="small text-body-secondary">สาเหตุ</div><div><?= nl2br(Html::encode($risk->cause?:'—')) ?></div></div><div class="col-md-6"><div class="small text-body-secondary">ผลกระทบ</div><div><?= nl2br(Html::encode($risk->impact?:'—')) ?></div></div></div><?php if($risk->likelihood_score&&$risk->impact_score): ?><div class="small mt-3">คะแนน 5×5: <strong><?= (int)$risk->likelihood_score ?> × <?= (int)$risk->impact_score ?> = <?= (int)$risk->likelihood_score*(int)$risk->impact_score ?></strong></div><?php endif; ?><?php foreach($risk->controls as $control): ?><div class="alert alert-secondary mt-3 mb-0"><strong>การควบคุมที่มีอยู่:</strong> <?= nl2br(Html::encode($control->description)) ?></div><?php endforeach; ?><?php if($risk->adequacy==='inadequate'): ?><?php foreach($risk->plans as $plan): ?><div class="alert alert-warning mt-3 mb-0"><strong>แผนแก้ไข:</strong> <?= nl2br(Html::encode($plan->action)) ?><div class="small mt-1">ผู้รับผิดชอบ <?= Html::encode($plan->responsible) ?> · กำหนด <?= Yii::$app->formatter->asDate($plan->due_date) ?></div></div><?php endforeach; ?><?php endif; ?><?php if($canEdit): ?><div class="d-flex justify-content-end gap-2 mt-3"><button class="btn btn-sm btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#edit-risk-<?= (int)$risk->id ?>">แก้ไข</button><?= Html::a('ลบ',['delete-risk','id'=>$risk->id],['class'=>'btn btn-sm btn-outline-danger','data-method'=>'post','data-confirm'=>'ลบความเสี่ยงนี้?']) ?></div><div class="collapse mt-3" id="edit-risk-<?= (int)$risk->id ?>"><div class="bg-body-tertiary border rounded-3 p-3"><?= $this->render('_risk_form',['step'=>$step,'risk'=>$risk]) ?></div></div><?php endif; ?></section><?php endforeach; ?><?php if(!$step->risks): ?><div class="small text-body-secondary">ขั้นตอนนี้ยังไม่มีความเสี่ยง และจะยังคงแสดงใน Flow chart</div><?php endif; ?></div></article><?php endforeach; ?><?php if(!$model->steps): ?><div class="list-group-item bg-body text-center py-5 text-body-secondary">ยังไม่มีขั้นตอนการปฏิบัติงาน</div><?php endif; ?></div></section>
<?php
$riskError=(string)Yii::$app->request->get('risk_error_id','');$openStep=(int)Yii::$app->request->get('open_step_id',0);
$this->registerJs(<<<JS
document.querySelectorAll('.csa-risk-form').forEach(function(form){var select=form.querySelector('.js-adequacy');function sync(){var required=select&&select.value==='inadequate';form.querySelectorAll('.js-plan-required').forEach(function(field){field.required=required;});var residual=form.querySelector('.js-residual-risk');if(residual)residual.required=required;}select?.addEventListener('change',sync);sync();});
JS);
if($riskError!==''){$target=$riskError==='new'?'add-risk-'.$openStep:'edit-risk-'.(int)$riskError;$this->registerJs("document.getElementById(".\yii\helpers\Json::htmlEncode($target).")?.classList.add('show');");}
?>
