<?php
use app\modules\iacRisk\models\Csa;
use app\modules\serviceProfile\models\ServiceProfile;
use yii\helpers\Html;
$this->title='CSA';$labels=Csa::statusLabels();
?>
<?php $this->beginBlock('page-title'); ?>CSA<?php $this->endBlock(); ?>
<?php $this->beginBlock('sub-title'); ?>เลือกเฉพาะกระบวนงานที่ต้องการวิเคราะห์ความเสี่ยง<?php $this->endBlock(); ?>
<?= $this->render('_context',['context'=>$context]) ?><div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'csa','context'=>$context]) ?></div>
<section class="card bg-body border shadow-sm"><div class="card-header bg-body-tertiary border-bottom py-3"><h2 class="h5 fw-semibold mb-1">กระบวนงานสำหรับทำ CSA</h2><p class="small text-body-secondary mb-0">หนึ่งกระบวนงานมีหนึ่ง CSA ต่อปีงบประมาณ ชื่อและวัตถุประสงค์จะถูกเก็บเป็น snapshot เมื่อเริ่ม</p></div><div class="card-body p-0"><div class="d-none d-lg-block"><table class="table align-middle mb-0"><thead><tr><th>หน่วยงาน</th><th>กระบวนงาน</th><th>วัตถุประสงค์</th><th>CSA</th><th class="text-end">จัดการ</th></tr></thead><tbody>
<?php foreach($processes as $process): ?><?php $csa=$csaByProcess[(int)$process->process_id]??null;$profile=$process->profile;$eligible=$profile&&in_array($profile->status,[ServiceProfile::STATUS_DRAFT,ServiceProfile::STATUS_RETURNED],true); ?><tr><td><?= Html::encode($profile?->owner_name_snapshot??'-') ?></td><td class="fw-semibold"><?= Html::encode($process->name) ?></td><td><?= Html::encode($process->objective?:'—') ?></td><td><?php if($csa): ?><span class="badge bg-primary-subtle text-primary-emphasis"><?= Html::encode($labels[$csa->status]??$csa->status) ?></span><?php else: ?><span class="text-body-secondary">ยังไม่เลือกทำ</span><?php endif; ?></td><td class="text-end"><?php if($csa): ?><?= Html::a('เปิด CSA',['csa-view','id'=>$csa->id],['class'=>'btn btn-sm btn-outline-primary']) ?><?php elseif($eligible): ?><?= Html::beginForm(['create-csa','process_version_id'=>$process->id],'post',['class'=>'d-inline']) ?><?= Html::submitButton('เลือกทำ CSA',['class'=>'btn btn-sm btn-primary','data-confirm'=>'เริ่ม CSA และเก็บ snapshot ของกระบวนงานนี้?']) ?><?= Html::endForm() ?><?php else: ?><span class="small text-body-secondary">Service Profile ไม่อยู่ระหว่างทบทวน</span><?php endif; ?></td></tr><?php endforeach; ?>
<?php if(!$processes): ?><tr><td colspan="5" class="text-center py-5 text-body-secondary">ไม่มีกระบวนงานในขอบเขตที่เลือก</td></tr><?php endif; ?>
</tbody></table></div><div class="d-lg-none list-group list-group-flush"><?php foreach($processes as $process): ?><?php $csa=$csaByProcess[(int)$process->process_id]??null; ?><div class="list-group-item bg-body p-3"><div class="small text-body-secondary"><?= Html::encode($process->profile?->owner_name_snapshot??'-') ?></div><div class="fw-semibold mt-1"><?= Html::encode($process->name) ?></div><div class="small text-body-secondary mt-1"><?= Html::encode($process->objective?:'ยังไม่ระบุวัตถุประสงค์') ?></div><?php if($csa): ?><?= Html::a('เปิด CSA',['csa-view','id'=>$csa->id],['class'=>'btn btn-sm btn-outline-primary mt-3']) ?><?php endif; ?></div><?php endforeach; ?></div></div></section>
