<?php
use yii\helpers\Html;
use app\modules\iacRisk\services\ContextService;
$this->title='ปค.1';
?>
<?php $this->beginBlock('page-title'); ?>ปค.1<?php $this->endBlock(); ?><?php $this->beginBlock('sub-title'); ?>หนังสือรับรองการประเมินผลการควบคุมภายใน<?php $this->endBlock(); ?>
<?= $this->render('_context',['context'=>$context]) ?><div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'pk1','context'=>$context]) ?></div>
<?php if(!$model): ?><section class="card border shadow-sm"><div class="card-body text-center py-5"><h2 class="h5">ยังไม่มีหนังสือรับรอง ปค.1 ของปีงบประมาณนี้</h2><?php if($canEdit): ?><?= Html::beginForm(array_merge(['create-pk1'],ContextService::query($context)),'post') ?><?= Html::submitButton('เริ่มจัดทำ ปค.1',['class'=>'btn btn-primary mt-3']) ?><?= Html::endForm() ?><?php else: ?><p class="text-body-secondary">รอทีมประสานจัดทำเอกสารระดับองค์กร</p><?php endif; ?></div></section><?php endif; ?>
<?php if($model): ?>
<?php $signatureType=$model->signature_type?:'system';$systemSignatureUrl=$model->signer?->SignatureShow(); ?>
<section class="card border shadow-sm"><div class="card-header bg-body-tertiary d-flex justify-content-between gap-3"><div><h2 class="h5 mb-1">หนังสือรับรองการประเมินผลการควบคุมภายใน</h2><span class="small text-body-secondary">ปีงบประมาณ <?= (int)$model->fiscal_year ?> · ฉบับร่างระดับองค์กร</span></div><div class="d-flex gap-2"><?= Html::a('<i class="bi bi-file-earmark-word me-1"></i> Word',['pk1-docx','id'=>$model->id],['class'=>'btn btn-outline-primary']) ?><?= Html::a('<i class="bi bi-file-earmark-pdf me-1"></i> PDF',['pk1-pdf','id'=>$model->id],['class'=>'btn btn-outline-danger','target'=>'_blank','rel'=>'noopener']) ?></div></div>
<div class="card-body"><?= Html::beginForm(array_merge(['save-pk1','id'=>$model->id],ContextService::query($context)),'post',['id'=>'pk1-form']) ?>
<label class="form-label fw-semibold">เรียน</label><?= Html::textInput('recipient',$model->recipient,['class'=>'form-control mb-3','disabled'=>!$canEdit]) ?>
<label class="form-label fw-semibold">ข้อความรับรองการประเมิน</label><?= Html::textarea('assessment_text',$model->assessment_text,['class'=>'form-control mb-3','rows'=>5,'disabled'=>!$canEdit]) ?>
<label class="form-label fw-semibold">ข้อสรุปผลการประเมิน</label><?= Html::textarea('conclusion_text',$model->conclusion_text,['class'=>'form-control mb-3','rows'=>5,'disabled'=>!$canEdit]) ?>
<label class="form-label fw-semibold">จุดอ่อนของการควบคุมหรือความเสี่ยงที่ยังมีอยู่ (ถ้ามี)</label><?= Html::textarea('weakness_text',$model->weakness_text,['class'=>'form-control','rows'=>4,'disabled'=>!$canEdit]) ?>
<div class="row g-3 mt-2"><div class="col-md-6"><label class="form-label fw-semibold">ชื่อผู้ลงนาม</label><?= Html::textInput('signer_name',$model->signer_name,['class'=>'form-control','disabled'=>!$canEdit]) ?></div><div class="col-md-6"><label class="form-label fw-semibold">ตำแหน่ง</label><?= Html::textInput('signer_position',$model->signer_position,['class'=>'form-control','disabled'=>!$canEdit]) ?></div></div>
<div class="mt-4"><label class="form-label fw-semibold">ลายเซ็นผู้อำนวยการ</label><div class="d-flex gap-2 mb-3"><button type="button" class="btn btn-sm <?= $signatureType==='canvas'?'btn-primary':'btn-outline-primary' ?> pk1-sig-tab" data-type="canvas" <?= !$canEdit?'disabled':'' ?>><i class="bi bi-pen me-1"></i> เซ็นสด</button><button type="button" class="btn btn-sm <?= $signatureType==='system'?'btn-primary':'btn-outline-primary' ?> pk1-sig-tab" data-type="system" <?= !$canEdit?'disabled':'' ?>><i class="bi bi-person-badge me-1"></i> ลายเซ็นระบบ</button></div>
<div id="pk1-canvas-panel" class="<?= $signatureType==='system'?'d-none':'' ?>"><div class="border rounded bg-white overflow-hidden" style="touch-action:none;max-width:560px"><canvas id="pk1-canvas" width="560" height="180" style="display:block;width:100%;height:180px;cursor:crosshair"></canvas></div><button type="button" id="pk1-clear" class="btn btn-sm btn-outline-secondary mt-2" <?= !$canEdit?'disabled':'' ?>><i class="bi bi-eraser me-1"></i> ล้างลายเซ็น</button></div>
<div id="pk1-system-panel" class="<?= $signatureType==='canvas'?'d-none':'' ?>"><?php if($systemSignatureUrl): ?><div class="border rounded bg-body-tertiary p-3 d-inline-block"><img src="<?= Html::encode($systemSignatureUrl) ?>" style="max-width:300px;max-height:120px" alt="ลายเซ็นระบบ"></div><?php else: ?><div class="alert alert-warning d-inline-flex py-2 px-3">ไม่พบลายเซ็นผู้อำนวยการในระบบ กรุณาเลือกเซ็นสด</div><?php endif; ?></div>
<?= Html::hiddenInput('signature_type',$signatureType,['id'=>'pk1-signature-type']) ?><?= Html::hiddenInput('signature_data',$model->signature_data?:'',['id'=>'pk1-signature-data']) ?></div>
<?php if($canEdit): ?><div class="d-flex justify-content-end mt-3"><?= Html::submitButton('บันทึกฉบับร่าง',['class'=>'btn btn-primary']) ?></div><?php endif; ?><?= Html::endForm() ?></div></section>
<?php
$existing=json_encode($model->signature_data?:'');
$this->registerJs(<<<JS
(function(){const c=document.getElementById('pk1-canvas');if(!c)return;const x=c.getContext('2d');let draw=false,dirty=false;function p(e){const r=c.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*c.width/r.width,y:(t.clientY-r.top)*c.height/r.height}}function start(e){draw=true;dirty=true;const q=p(e);x.beginPath();x.moveTo(q.x,q.y);e.preventDefault()}function move(e){if(!draw)return;const q=p(e);x.lineWidth=2;x.lineCap='round';x.strokeStyle='#111';x.lineTo(q.x,q.y);x.stroke();e.preventDefault()}c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);window.addEventListener('mouseup',()=>draw=false);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',()=>draw=false);const old=$existing;if(old){const i=new Image();i.onload=()=>x.drawImage(i,0,0,c.width,c.height);i.src=old}document.querySelectorAll('.pk1-sig-tab').forEach(b=>b.addEventListener('click',function(){const t=this.dataset.type;document.getElementById('pk1-signature-type').value=t;document.getElementById('pk1-canvas-panel').classList.toggle('d-none',t!=='canvas');document.getElementById('pk1-system-panel').classList.toggle('d-none',t!=='system');document.querySelectorAll('.pk1-sig-tab').forEach(v=>{v.classList.toggle('btn-primary',v===this);v.classList.toggle('btn-outline-primary',v!==this)})}));document.getElementById('pk1-clear').addEventListener('click',()=>{x.clearRect(0,0,c.width,c.height);dirty=true;document.getElementById('pk1-signature-data').value=''});document.getElementById('pk1-form').addEventListener('submit',()=>{if(document.getElementById('pk1-signature-type').value==='canvas'&&dirty)document.getElementById('pk1-signature-data').value=c.toDataURL('image/png')})})();
JS);
?>
<?php endif; ?>
