<?php
use app\modules\iacRisk\models\CsaRisk;
use app\modules\iacRisk\services\ContextService;
use app\modules\iacRisk\services\Pk5Service;
use yii\helpers\Html;
$this->title='ปค.5';$groups=[];foreach($rows as $row){$id=(int)$row->org_unit_id;if(!isset($groups[$id]))$groups[$id]=['name'=>$row->orgUnit?->name?:'หน่วยงาน #'.$id,'rows'=>[]];$groups[$id]['rows'][]=$row;}
?>
<?php $this->beginBlock('page-title'); ?>ปค.5<?php $this->endBlock(); ?><?php $this->beginBlock('sub-title'); ?>รายงานการประเมินผลการควบคุมภายใน<?php $this->endBlock(); ?>
<?= $this->render('_context',['context'=>$context]) ?><div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'pk5','context'=>$context]) ?></div>
<div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h2 class="h5 mb-1">แบบ ปค.5 ปีงบประมาณ <?= Html::encode($context['fiscalYear']?->fiscal_year?:'-') ?></h2><p class="text-body-secondary mb-0"><?= (int)$context['orgUnitId']?'รายหน่วยงาน':'ภาพรวมทุกหน่วยงาน' ?> · รวม <?= count($rows) ?> ความเสี่ยง</p></div><div class="d-flex gap-2"><?php if(!$errors&&$rows): ?><?= Html::a('<i class="bi bi-eye me-1"></i> PDF ตัวอย่าง',array_merge(['pk5-pdf'],ContextService::query($context)),['class'=>'btn btn-outline-danger','target'=>'_blank','rel'=>'noopener']) ?><?= Html::a('ไปสร้าง Snapshot',array_merge(['reports'],ContextService::query($context)),['class'=>'btn btn-primary']) ?><?php else: ?><button class="btn btn-outline-danger" disabled><i class="bi bi-eye me-1"></i> PDF ตัวอย่าง</button><?php endif; ?></div></div>
<?php if($errors): ?><div class="alert alert-warning"><div class="fw-semibold mb-1">ยังไม่สามารถส่งออก PDF ได้</div><ul class="mb-0"><?php foreach($errors as $error): ?><li><?= Html::encode($error) ?></li><?php endforeach; ?></ul><div class="mt-2 small">กรุณาแก้ไขที่ CSA ต้นทาง หรือบัญชีความเสี่ยงสำหรับรายการนอกกระบวนงาน</div></div><?php endif; ?>
<?php foreach($groups as $group): ?><section class="card border shadow-sm mb-3"><div class="card-header bg-body-tertiary d-flex justify-content-between"><h3 class="h6 fw-semibold mb-0"><?= Html::encode($group['name']) ?></h3><span class="badge bg-primary-subtle text-primary-emphasis"><?= count($group['rows']) ?> รายการ</span></div><div class="table-responsive"><table class="table table-bordered align-top mb-0" style="min-width:1400px"><thead><tr><th style="width:16%">ภารกิจ/วัตถุประสงค์</th><th style="width:14%">ความเสี่ยง</th><th style="width:14%">การควบคุมที่มีอยู่</th><th style="width:12%">การประเมินผล</th><th style="width:14%">ความเสี่ยงที่ยังมีอยู่</th><th style="width:16%">การปรับปรุง</th><th style="width:14%">ผู้รับผิดชอบ</th></tr></thead><tbody><?php foreach($group['rows'] as $row): ?><tr><td><?= nl2br(Html::encode($row->mission_objective?:'—')) ?></td><td><?= nl2br(Html::encode($row->risk_name)) ?></td><td><?= nl2br(Html::encode($row->existing_control?:'—')) ?></td><td><span class="badge <?= $row->adequacy===CsaRisk::ADEQUACY_INADEQUATE?'bg-warning text-dark':'bg-success-subtle text-success-emphasis' ?>"><?= Html::encode(Pk5Service::adequacyLabel($row->adequacy)) ?></span></td><td><?= nl2br(Html::encode($row->residual_risk?:'—')) ?></td><td class="<?= $row->adequacy===CsaRisk::ADEQUACY_INADEQUATE&&!$row->improvement_plan?'table-warning':'' ?>"><?= nl2br(Html::encode($row->improvement_plan?:'—')) ?></td><td><?= nl2br(Html::encode($row->responsible_person?:'—')) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endforeach; ?>
<?php if(!$rows): ?><div class="card border shadow-sm"><div class="card-body text-center py-5 text-body-secondary">ยังไม่มีข้อมูลความเสี่ยงสำหรับจัดทำ ปค.5</div></div><?php endif; ?>
