<?php
use app\modules\iacRisk\models\CsaRisk;
use app\modules\iacRisk\models\RiskRegister;
use app\modules\iacRisk\services\RiskMatrixService;
use app\modules\iacRisk\services\ContextService;
use yii\helpers\Html;
$this->title='บัญชีความเสี่ยง';$adequacyLabels=CsaRisk::adequacyLabels();$groups=[];
foreach($models as $item){$unitId=(int)$item->org_unit_id;if(!isset($groups[$unitId]))$groups[$unitId]=['name'=>$item->orgUnit?->name?:'หน่วยงาน #'.$unitId,'items'=>[]];$groups[$unitId]['items'][]=$item;}
?>
<?php $this->beginBlock('page-title'); ?>บัญชีความเสี่ยง<?php $this->endBlock(); ?>
<?php $this->beginBlock('sub-title'); ?>บัญชีความเสี่ยงรายปี แยกตามหน่วยงาน<?php $this->endBlock(); ?>
<?= $this->render('_context',['context'=>$context]) ?><div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'risks','context'=>$context]) ?></div>
<form method="get" class="card bg-body border shadow-sm mb-3"><div class="card-body"><div class="row g-3 align-items-end"><?php foreach(ContextService::query($context) as $name=>$value): ?><?= Html::hiddenInput($name,$value) ?><?php endforeach; ?><div class="col-12 col-md-5 col-lg-3"><label class="form-label fw-semibold" for="risk-level-filter">ระดับความเสี่ยง</label><?= Html::dropDownList('risk_level',$riskLevel,RiskMatrixService::levelOptions(),['id'=>'risk-level-filter','class'=>'form-select','prompt'=>'ทุกระดับ']) ?></div><div class="col-12 col-md-auto"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-funnel me-1"></i> กรองข้อมูล</button></div><?php if($riskLevel!==''): ?><div class="col-12 col-md-auto"><?= Html::a('ล้างตัวกรอง',array_merge(['risks'],ContextService::query($context)),['class'=>'btn btn-link']) ?></div><?php endif; ?></div></div></form>
<?php if($canEdit): ?><section class="card bg-body border shadow-sm mb-3"><div class="card-header bg-body-tertiary border-bottom d-flex justify-content-between align-items-center gap-3"><div><h2 class="h6 fw-semibold mb-1">ความเสี่ยงนอกกระบวนงาน</h2><p class="small text-body-secondary mb-0">ใช้สำหรับความเสี่ยงที่ไม่ได้มาจาก CSA</p></div><button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#add-manual-risk"><i class="bi bi-plus-lg me-1"></i> เพิ่มความเสี่ยง</button></div><div class="collapse" id="add-manual-risk"><div class="card-body"><?= $this->render('_manual_risk_form',['model'=>null,'context'=>$context]) ?></div></div></section>
<?php elseif(($context['canScopeAllUnits']??false)&&!(int)$context['orgUnitId']): ?><div class="alert alert-info">หากต้องการเพิ่มความเสี่ยงนอกกระบวนงาน กรุณาเลือกหน่วยงานจากตัวกรองด้านบนก่อน</div><?php endif; ?>
<div class="d-flex flex-column gap-3">
<?php foreach($groups as $unitId=>$group): ?><section class="card bg-body border shadow-sm"><div class="card-header bg-body-tertiary border-bottom py-3 d-flex flex-column flex-md-row justify-content-between gap-2"><div><h2 class="h5 fw-semibold mb-1"><?= Html::encode($group['name']) ?></h2><p class="small text-body-secondary mb-0">บัญชีความเสี่ยงของหน่วยงาน ปีงบประมาณ <?= Html::encode($context['fiscalYear']?->fiscal_year?:'-') ?></p></div><span class="badge bg-primary-subtle text-primary-emphasis align-self-start"><?= count($group['items']) ?> รายการ</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th style="width:3rem">ลำดับ</th><th>ความเสี่ยง</th><th>ที่มา</th><th>คะแนน</th><th>ระดับความเสี่ยง</th><th>การควบคุม</th><th class="text-end">จัดการ</th></tr></thead><tbody>
<?php foreach($group['items'] as $index=>$model): ?><?php $level=RiskMatrixService::evaluate($model->likelihood_score,$model->impact_score); ?><tr><td class="text-body-secondary"><?= $index+1 ?></td><td><div class="fw-semibold"><?= Html::encode($model->risk_name) ?></div><?php if($model->cause): ?><div class="small text-body-secondary text-truncate" style="max-width:32rem">สาเหตุ: <?= Html::encode($model->cause) ?></div><?php endif; ?></td><td><?php if($model->source_type===RiskRegister::SOURCE_CSA): ?><span class="badge bg-info-subtle text-info-emphasis">จากกระบวนงาน</span><?php if($model->csa): ?><div class="small mt-1"><?= Html::encode($model->csa->process_name_snapshot) ?></div><?php endif; ?><?php else: ?><span class="badge bg-secondary-subtle text-secondary-emphasis">นอกกระบวนงาน</span><?php endif; ?></td><td class="fw-semibold"><?= $level?(int)$model->likelihood_score.' × '.(int)$model->impact_score.' = '.(int)$level['score']:'—' ?></td><td><?= $level?'<span class="badge '.$level['badge'].'">'.Html::encode($level['label']).'</span>':'<span class="text-body-secondary">ยังไม่ประเมิน</span>' ?></td><td><?= Html::encode($adequacyLabels[$model->adequacy]??'ยังไม่ระบุ') ?></td><td class="text-end text-nowrap"><?php if($model->isFromCsa()&&$model->csa_id): ?><?= Html::a('เปิด CSA',['csa-view','id'=>$model->csa_id],['class'=>'btn btn-sm btn-outline-primary']) ?><?php elseif($canEdit): ?><button class="btn btn-sm btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#edit-risk-<?= (int)$model->id ?>">แก้ไข</button> <?= Html::a('ลบ',['delete-manual-risk','id'=>$model->id],['class'=>'btn btn-sm btn-outline-danger','data-method'=>'post','data-confirm'=>'ลบความเสี่ยงนอกกระบวนงานรายการนี้?']) ?><?php endif; ?></td></tr>
<?php if($model->source_type===RiskRegister::SOURCE_MANUAL&&$canEdit): ?><tr class="collapse" id="edit-risk-<?= (int)$model->id ?>"><td colspan="7" class="bg-body-tertiary p-3"><?= $this->render('_manual_risk_form',['model'=>$model,'context'=>$context]) ?></td></tr><?php endif; ?><?php endforeach; ?>
</tbody></table></div></section><?php endforeach; ?>
<?php if(!$groups): ?><section class="card bg-body border shadow-sm"><div class="card-body text-center py-5 text-body-secondary">ยังไม่มีความเสี่ยงในบัญชีของขอบเขตที่เลือก</div></section><?php endif; ?></div>
