<?php
use app\modules\iacRisk\models\RiskFollowup;
use app\modules\iacRisk\services\ContextService;
use app\modules\iacRisk\services\AccessService;
use yii\helpers\Html;
$canExport=$canExport&&(new AccessService())->canExportOrganizationReports();
$this->title='ติดตามผล';$firstItem=$items[0]??null;$groups=[];foreach($items as $item){$id=(int)$item->org_unit_id;if(!isset($groups[$id]))$groups[$id]=['name'=>$item->orgUnit?->name?:'หน่วยงาน #'.$id,'items'=>[]];$groups[$id]['items'][]=$item;}
?>
<?php $this->beginBlock('page-title'); ?>ติดตามผล<?php $this->endBlock(); ?><?php $this->beginBlock('sub-title'); ?>ติดตามแผนปรับปรุงการควบคุมภายในจาก ปค.5<?php $this->endBlock(); ?>
<?= $this->render('_context',['context'=>$context]) ?><div class="mb-3"><?= $this->render('@app/modules/iacRisk/menu',['active'=>'tracking','context'=>$context]) ?></div>
<div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h2 class="h5 mb-1">แบบติดตาม ปค.5</h2><p class="text-body-secondary mb-0">แสดงเฉพาะรายการที่มีแผนปรับปรุง · <?= Html::encode(($context['fiscalYear']?->fiscal_year?:'-').' / '.($firstItem?->period?->name?:'รอบรายงาน')) ?></p></div><div class="d-flex gap-2"><?php if($canExport): ?><?= Html::a('<i class="bi bi-file-earmark-pdf me-1"></i> PDF รวมองค์กร',array_merge(['tracking-pdf'],ContextService::query($context)),['class'=>'btn btn-danger','target'=>'_blank','rel'=>'noopener']) ?><?php endif; ?><?php if($canEdit&&!$items): ?><?= Html::beginForm(array_merge(['create-followup'],ContextService::query($context)),'post') ?><?= Html::submitButton('เริ่มติดตามรอบนี้',['class'=>'btn btn-primary','data-confirm'=>'ยืนยันดึงรายการที่มีแผนปรับปรุงจาก ปค.5?']) ?><?= Html::endForm() ?><?php endif; ?></div></div>
<?php if(!$items&&!$canEdit): ?><div class="alert alert-info">ยังไม่มีข้อมูลติดตามในรอบที่เลือก</div><?php endif; ?>
<?php if($items): ?><?= $canEdit?Html::beginForm(array_merge(['save-followup'],ContextService::query($context)),'post'):'' ?><?php foreach($groups as $group): ?><section class="card border shadow-sm mb-3"><div class="card-header bg-body-tertiary"><h3 class="h6 fw-semibold mb-0"><?= Html::encode($group['name']) ?></h3></div><div class="table-responsive"><table class="table table-bordered align-top mb-0" style="min-width:1500px"><thead><tr><th style="width:15%">(3) ภารกิจ/วัตถุประสงค์</th><th style="width:13%">(4) การควบคุมภายในที่มีอยู่</th><th style="width:13%">(5) ความเสี่ยงที่ยังมีอยู่</th><th style="width:14%">(6) การปรับปรุงการควบคุมภายใน</th><th style="width:12%">(7) หน่วยงานที่รับผิดชอบ</th><th style="width:13%">(8) สถานะดำเนินการ</th><th style="width:20%">(9) วิธีติดตาม/สรุปผล/ข้อคิดเห็น</th></tr></thead><tbody><?php foreach($group['items'] as $item): ?><tr><td><?= nl2br(Html::encode($item->mission_objective?:'—')) ?></td><td><?= nl2br(Html::encode($item->existing_control?:'—')) ?></td><td><?= nl2br(Html::encode($item->residual_risk?:'—')) ?></td><td><?= nl2br(Html::encode($item->improvement_plan)) ?></td><td><?= nl2br(Html::encode($item->responsible_person?:'—')) ?></td><td><?php if($canEdit): ?><?= Html::dropDownList("followups[$item->id][status_code]",$item->status_code,RiskFollowup::statusLabels(),['class'=>'form-select']) ?><?php else: ?><?= Html::encode(RiskFollowup::statusLabels()[$item->status_code]??$item->status_code) ?><?php endif; ?></td><td><?php if($canEdit): ?><label class="small text-body-secondary">วิธีติดตาม</label><?= Html::textarea("followups[$item->id][followup_method]",$item->followup_method,['class'=>'form-control mb-2','rows'=>2]) ?><label class="small text-body-secondary">สรุปผลการประเมิน</label><?= Html::textarea("followups[$item->id][result_summary]",$item->result_summary,['class'=>'form-control mb-2','rows'=>2]) ?><label class="small text-body-secondary">ข้อคิดเห็น</label><?= Html::textarea("followups[$item->id][comment]",$item->comment,['class'=>'form-control','rows'=>2]) ?><?php else: ?><?= nl2br(Html::encode(implode("\n",array_filter([$item->followup_method,$item->result_summary,$item->comment]))?:'—')) ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endforeach; ?><?php if($canEdit): ?><div class="sticky-bottom bg-body border rounded shadow-sm p-3 d-flex justify-content-end"><?= Html::submitButton('บันทึกผลติดตาม',['class'=>'btn btn-primary']) ?></div><?= Html::endForm() ?><?php endif; ?><?php endif; ?>
