<?php

namespace app\modules\am\services;

use Yii;
use yii\web\Response;

/**
 * Export reports to CSV (Excel-compatible) or trigger PDF via response headers.
 * PDF can be generated by browser print or by mpdf in caller.
 */
class ReportExportService
{
    /**
     * Send CSV download response (Excel-compatible UTF-8 BOM).
     * @param string $filename e.g. asset-register-2024.csv
     * @param array[] $rows array of associative arrays
     * @param string[]|null $headers optional column headers; if null, taken from first row keys
     */
    public static function sendCsv(string $filename, array $rows, ?array $headers = null): void
    {
        if (empty($rows) && $headers === null) {
            $headers = [];
        }
        if ($headers === null) {
            $headers = array_keys(reset($rows));
        }

        Yii::$app->response->format = Response::FORMAT_RAW;
        Yii::$app->response->headers->set('Content-Type', 'text/csv; charset=UTF-8');
        Yii::$app->response->headers->set('Content-Disposition', 'attachment; filename="' . addslashes($filename) . '"');

        $out = fopen('php://output', 'w');
        fprintf($out, "\xEF\xBB\xBF"); // UTF-8 BOM for Excel
        fputcsv($out, $headers);
        foreach ($rows as $row) {
            $line = [];
            foreach ($headers as $h) {
                $line[] = $row[$h] ?? '';
            }
            fputcsv($out, $line);
        }
        fclose($out);
        if (Yii::$app->request->isAjax === false) {
            Yii::$app->end();
        }
    }
}
