<?php
use yii\helpers\Html;
use yii\helpers\Url;
$thaiMonths = [1 => 'มกราคม', 2 => 'กุมภาพันธ์', 3 => 'มีนาคม', 4 => 'เมษายน', 5 => 'พฤษภาคม', 6 => 'มิถุนายน', 7 => 'กรกฎาคม', 8 => 'สิงหาคม', 9 => 'กันยายน', 10 => 'ตุลาคม', 11 => 'พฤศจิกายน', 12 => 'ธันวาคม'];
$formatPeriod = static function ($code) use ($thaiMonths): string { $parts = explode('-', (string) $code); return ($thaiMonths[(int) ($parts[1] ?? 0)] ?? $code) . ' ' . ((int) ($parts[0] ?? 0) + 543); };
?>
<section class="card border-0 shadow-sm rounded-4 overflow-hidden">
<div class="card-header bg-body border-bottom p-3 p-md-4"><div class="d-flex align-items-center gap-3"><span class="d-grid place-items-center rounded-3 bg-primary bg-opacity-10 text-primary" style="width:42px;height:42px"><i class="bi bi-wallet2 fs-5" aria-hidden="true"></i></span><div><h5 class="mb-1">เงินเดือนและค่าตอบแทนของฉัน</h5><p class="small text-body-secondary mb-0">ดูรายการรับ รายการหัก เงินสุทธิ และสลิปส่วนบุคคล</p></div></div></div>
<?php if ($rows): ?><div class="table-responsive"><table class="table table-hover align-middle mb-0 self-payroll-table"><thead><tr><th>รอบ</th><th>ประเภท</th><th class="text-end">รายรับ</th><th class="text-end">รายการหัก</th><th class="text-end">รับสุทธิ</th><th class="text-end">สลิป</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><strong><?= Html::encode($formatPeriod($row['period_code'])) ?></strong></td><td><span class="badge text-bg-light border"><?= Html::encode($types[$row['period_type']] ?? $row['period_type']) ?></span></td><td class="text-end"><?= number_format((float) $row['gross_amount'], 2) ?></td><td class="text-end"><?= number_format((float) $row['deduction_amount'], 2) ?></td><td class="text-end fw-semibold"><?= number_format((float) $row['net_amount'], 2) ?></td><td class="text-end"><?= Html::a('<i class="bi bi-receipt me-1" aria-hidden="true"></i>ดูสลิป', ['/profile/payroll-slip', 'id' => $row['id']], ['class' => 'btn btn-sm btn-outline-primary js-self-payslip', 'data-name' => $formatPeriod($row['period_code'])]) ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="card-body py-5 text-center"><i class="bi bi-receipt fs-1 text-body-secondary" aria-hidden="true"></i><strong class="d-block mt-2">ยังไม่มีข้อมูลเงินเดือนหรือค่าตอบแทน</strong><span class="small text-body-secondary">ข้อมูลจะแสดงเมื่อฝ่ายการเงินสร้างรอบและประมวลผลแล้ว</span></div><?php endif; ?>
</section>
<div class="modal fade" id="self-payslip-modal" tabindex="-1" aria-labelledby="self-payslip-title" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title" id="self-payslip-title"><i class="bi bi-receipt me-2"></i>สลิปของฉัน</h5><div class="small text-body-secondary" id="self-payslip-period"></div></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body bg-body-tertiary p-4" id="self-payslip-body"></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">ปิด</button><button class="btn btn-primary" type="button" id="self-payslip-print"><i class="bi bi-printer me-1"></i>พิมพ์</button></div></div></div></div>
<?php
$this->registerCss('.self-payroll-table{min-width:720px}.self-payroll-table td:nth-child(n+3){font-variant-numeric:tabular-nums}.place-items-center{place-items:center}.payslip-preview-sheet{background:#fff;max-width:960px;margin:auto}.payslip-preview-sheet td,.payslip-preview-sheet th{font-variant-numeric:tabular-nums}');
$this->registerJs(<<<'JS'
document.addEventListener('click', async function(event){
 const link=event.target.closest('.js-self-payslip'); if(!link)return; event.preventDefault();
 const modal=document.getElementById('self-payslip-modal'),body=document.getElementById('self-payslip-body');
 document.getElementById('self-payslip-period').textContent=link.dataset.name||'';
 body.innerHTML='<div class="text-center py-5"><div class="spinner-border text-primary"></div><div class="mt-2 text-body-secondary">กำลังโหลดสลิป...</div></div>';
 bootstrap.Modal.getOrCreateInstance(modal).show();
 try{const response=await fetch(link.href,{headers:{'X-Requested-With':'XMLHttpRequest'}});if(!response.ok)throw new Error();body.innerHTML=await response.text();}catch(error){body.innerHTML='<div class="alert alert-danger mb-0">ไม่สามารถโหลดสลิปได้</div>';}
});
document.getElementById('self-payslip-print')?.addEventListener('click',function(){const slip=document.querySelector('#self-payslip-body .payslip-preview-sheet');if(!slip)return;const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.appendChild(frame);const styles=Array.from(document.querySelectorAll('link[rel="stylesheet"],style')).map(n=>n.outerHTML).join('');frame.contentDocument.open();frame.contentDocument.write('<!doctype html><html lang="th"><head><meta charset="utf-8">'+styles+'<style>@page{size:A4;margin:14mm}body{margin:0;background:#fff}.payslip-preview-sheet{max-width:none!important;box-shadow:none!important}</style></head><body>'+slip.outerHTML+'</body></html>');frame.contentDocument.close();setTimeout(()=>{frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),1000)},500);});
JS);
?>
