<?php
declare(strict_types=1);
namespace app\modules\housing\controllers;
use app\modules\housing\models\{BillingPeriod,Building,ChargeType,HousingRate,Meter,MeterReading,Unit};
use Yii; use yii\data\ActiveDataProvider; use yii\filters\VerbFilter; use yii\helpers\ArrayHelper; use yii\web\{NotFoundHttpException,Response}; use yii\widgets\ActiveForm;
final class UtilityController extends BaseController {
 public function behaviors():array{return array_merge(parent::behaviors(),['verbs'=>['class'=>VerbFilter::class,'actions'=>['confirm-reading'=>['POST']]]]);}
 public function actionIndex(string $section='readings'){return $this->render('index',['section'=>$section,'rates'=>HousingRate::find()->with(['chargeType','building','unit'])->orderBy(['effective_from'=>SORT_DESC])->all(),'meters'=>Meter::find()->with(['building','unit','room'])->orderBy('name')->all(),'readings'=>MeterReading::find()->with(['meter','billingPeriod'])->orderBy(['reading_date'=>SORT_DESC])->all()]);}
 public function actionCreateRate(){return $this->save(new HousingRate(), 'rate');}
 public function actionUpdateRate(int $id){return $this->save($this->find(HousingRate::class,$id),'rate');}
 public function actionCreateMeter(){return $this->save(new Meter(['status'=>'active']),'meter');}
 public function actionUpdateMeter(int $id){return $this->save($this->find(Meter::class,$id),'meter');}
 public function actionCreateReading(?int $meter_id=null){$m=new MeterReading(['meter_id'=>$meter_id,'reading_date'=>date('Y-m-d'),'status'=>'draft']);if($meter_id){$last=MeterReading::find()->where(['meter_id'=>$meter_id,'status'=>'confirmed'])->orderBy(['reading_date'=>SORT_DESC])->one();$m->previous_value=$last?->current_value??0;$m->unit_rate=$this->rateFor(Meter::findOne($meter_id));}return $this->save($m,'reading');}
 public function actionUpdateReading(int $id){$m=$this->find(MeterReading::class,$id);if($m->status==='confirmed')throw new \yii\web\BadRequestHttpException('รายการที่ยืนยันแล้วไม่สามารถแก้ไขได้');return $this->save($m,'reading');}
 public function actionConfirmReading(int $id){$m=$this->find(MeterReading::class,$id);$m->status='confirmed';$m->confirmed_at=date('Y-m-d H:i:s');$m->confirmed_by=Yii::$app->user->id;$m->save(false);return $this->redirect(['index','section'=>'readings']);}
 private function save($model,string $kind){if($model->load(Yii::$app->request->post())&&$model->save()){if(Yii::$app->request->isAjax){Yii::$app->response->format=Response::FORMAT_JSON;return ['status'=>'success','redirect'=>\yii\helpers\Url::to(['index','section'=>$kind==='rate'?'rates':($kind==='meter'?'meters':'readings')])];}return $this->redirect(['index']);}if(Yii::$app->request->isPost&&Yii::$app->request->isAjax){Yii::$app->response->format=Response::FORMAT_JSON;return ['errors'=>ActiveForm::validate($model)];}$p=['model'=>$model,'kind'=>$kind]+$this->options();if(Yii::$app->request->isAjax){Yii::$app->response->format=Response::FORMAT_JSON;return ['title'=>'บันทึกข้อมูล','content'=>$this->renderAjax('_form',$p)];}return $this->render('_form',$p);}
 private function options():array{return ['chargeTypes'=>ArrayHelper::map(ChargeType::find()->where(['status'=>'active'])->all(),'id','name'),'buildings'=>ArrayHelper::map(Building::find()->all(),'id','name'),'units'=>ArrayHelper::map(Unit::find()->all(),'id',fn($m)=>$m->code.' · '.$m->name),'metersList'=>ArrayHelper::map(Meter::find()->where(['status'=>'active'])->all(),'id',fn($m)=>$m->name.' ('.$m->meter_no.')'),'periods'=>ArrayHelper::map(BillingPeriod::find()->where(['status'=>'open'])->all(),'id','name')];}
 private function rateFor(?Meter $meter):float{if(!$meter)return 0;$code=$meter->meter_type==='water'?'WATER':'ELECTRIC';$type=ChargeType::findOne(['code'=>$code]);if(!$type)return 0;$q=HousingRate::find()->where(['charge_type_id'=>$type->id,'status'=>'active'])->andWhere(['<=','effective_from',date('Y-m-d')])->andWhere(['or',['effective_to'=>null],['>=','effective_to',date('Y-m-d')]])->orderBy(['unit_id'=>SORT_DESC,'building_id'=>SORT_DESC,'effective_from'=>SORT_DESC]);return (float)($q->one()?->rate??0);}
 private function find(string $class,int $id){if(($m=$class::findOne($id))===null)throw new NotFoundHttpException('ไม่พบข้อมูล');return $m;}
}
