<?php

use app\modules\filemanager\components\FileManagerHelper;
use app\modules\housing\models\AssetAssignment;
use app\modules\housing\models\Checkout;
use yii\helpers\Html;

$o=$model->occupancy;
$location=implode(' / ',array_filter([$o?->unit?->building?->name,$o?->unit?->name,$o?->room?->name]));
$this->title='ส่งคืนบ้านพัก '.$model->checkout_no;
$this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock();
?>
<div class="container py-3" style="max-width:920px">
<?php foreach(['success','warning','error'] as $type):if(Yii::$app->session->hasFlash($type)):?><div class="alert alert-<?= $type==='error'?'danger':$type ?>"><?= Html::encode(Yii::$app->session->getFlash($type)) ?></div><?php endif;endforeach;?>
<?= Html::a('กลับไปข้อมูลบ้านพัก',['/profile','name'=>'housing'],['class'=>'btn btn-outline-secondary mb-3']) ?>
<div class="card shadow-sm mb-3"><div class="card-header bg-body d-flex justify-content-between"><strong><?= Html::encode($model->checkout_no) ?></strong><span class="badge bg-warning-subtle text-warning-emphasis"><?= Html::encode(Checkout::statusOptions()[$model->status]) ?></span></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">บ้านพัก/ห้องพัก</dt><dd class="col-sm-8"><?= Html::encode($location) ?></dd><dt class="col-sm-4">วันที่ต้องการคืน</dt><dd class="col-sm-8"><?= Yii::$app->formatter->asDate($model->requested_date,'php:d/m/Y') ?></dd><dt class="col-sm-4">เหตุผล</dt><dd class="col-sm-8"><?= nl2br(Html::encode($model->move_out_reason)) ?></dd><dt class="col-sm-4">เลขมิเตอร์ไฟฟ้า / น้ำ</dt><dd class="col-sm-8"><?= $model->electric_meter_value??'—' ?> / <?= $model->water_meter_value??'—' ?></dd><dt class="col-sm-4">ยอดค้างชำระ ณ วันตรวจ</dt><dd class="col-sm-8 fw-semibold"><?= Yii::$app->formatter->asDecimal($model->outstanding_amount,2) ?> บาท</dd></dl></div></div>
<?php if($model->status!==Checkout::STATUS_REQUESTED):?><div class="card shadow-sm mb-3"><div class="card-header bg-body fw-semibold">ผลตรวจอุปกรณ์</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>รายการ</th><th>จำนวน</th><th>สภาพ</th><th>หมายเหตุ</th></tr></thead><tbody><?php foreach($model->assetItems() as $item):?><tr><td><?= Html::encode($item['item_name']) ?></td><td><?= Html::encode($item['quantity'].' '.$item['unit_name']) ?></td><td><?= Html::encode(AssetAssignment::conditionOptions()[$item['condition']]??$item['condition']) ?></td><td><?= Html::encode($item['note']?:'—') ?></td></tr><?php endforeach;?></tbody></table></div><div class="card-body border-top"><strong>สภาพและหมายเหตุ</strong><p class="mt-2"><?= nl2br(Html::encode($model->condition_note?:'ไม่มีหมายเหตุ')) ?></p><?php if($photos):?><div class="row g-2"><?php foreach($photos as $photo):?><div class="col-6 col-md-3"><img src="<?= Html::encode(FileManagerHelper::getImg($photo->id)) ?>" class="w-100 rounded border" style="aspect-ratio:4/3;object-fit:cover" alt="ภาพสภาพวันส่งคืน"></div><?php endforeach;?></div><?php endif;?></div></div><?php endif;?>
<div class="card shadow-sm"><div class="card-header bg-body fw-semibold">ขั้นตอนการลงนาม</div><div class="card-body"><?php if($model->status===Checkout::STATUS_INSPECTION):?><div class="alert alert-warning">กรุณาตรวจผลการตรวจรับคืน หากข้อมูลถูกต้องให้ลงนามส่งคืน</div><?= Html::beginForm(['sign-checkout','id'=>$model->id],'post',['class'=>'d-grid gap-3']) ?><label class="form-check"><input class="form-check-input" type="checkbox" name="resident_ack" value="1" required><span class="form-check-label">ข้าพเจ้าตรวจข้อมูลแล้ว และยืนยันส่งคืนบ้านพักพร้อมอุปกรณ์ตามรายการ</span></label><button class="btn btn-primary">ลงนามส่งคืนบ้านพัก</button><?= Html::endForm() ?><?php elseif($model->status===Checkout::STATUS_AWAITING_STAFF):?><div class="alert alert-info mb-0">ลงนามส่งคืนแล้ว รอผู้ดูแลตรวจรับและปิดการเข้าพัก</div><?php elseif($model->status===Checkout::STATUS_COMPLETED):?><div class="alert alert-success mb-0">ส่งคืนบ้านพักเรียบร้อยแล้ว</div><?php else:?><div class="alert alert-info mb-0">ผู้ดูแลได้รับคำขอแล้ว และจะบันทึกผลตรวจให้ลงนาม</div><?php endif;?></div></div>
</div>
