<?php
use yii\helpers\Html;
$this->title=$action?'ติดตามแผนปรับปรุง':'สร้างแผนปรับปรุง'; $p=Yii::$app->request->post(); $dimensions=[]; foreach($metrics as $m) $dimensions[$m['dimension_code']]=$m['dimension_title']; $employees=[]; foreach($owners as $o) $employees[$o['id']]=$o['fname'].' '.$o['lname'];
?>
<?= $this->render('_nav') ?>
<?= Html::beginForm('','post',['class'=>'card border-0 shadow-sm rounded-4']) ?><div class="card-body p-4"><h2 class="h5"><?= Html::encode($this->title) ?></h2>
<?php if($action): ?><p class="fw-semibold"><?= Html::encode($action['issue_summary']) ?></p><p>เป้าหมาย: <?= Html::encode($action['target']) ?> · กำหนด <?= Html::encode($action['due_date']) ?></p><label for="action-status" class="form-label">สถานะงาน</label><?= Html::dropDownList('status',$p['status']??$action['status'],['pending'=>'รอเริ่ม','doing'=>'กำลังดำเนินการ','done'=>'เสร็จแล้ว','cancelled'=>'ยกเลิก'],['id'=>'action-status','class'=>'form-select mb-3']) ?><label for="effectiveness" class="form-label">ผลติดตาม / หลักฐานว่าปัญหาดีขึ้น</label><?= Html::textarea('effectiveness_note',$p['effectiveness_note']??$action['effectiveness_note'],['id'=>'effectiveness','class'=>'form-control','rows'=>4,'maxlength'=>3000]) ?><p class="small text-body-secondary">หากเพียงทำงานเสร็จแต่ยังไม่ทราบผล ให้บันทึกว่ายังรอติดตามประสิทธิผล</p>
<?php else: ?><div class="row g-3"><div class="col-12"><label for="action-dimension" class="form-label">ด้านที่ต้องปรับปรุง</label><?= Html::dropDownList('dimension_code',$p['dimension_code']??null,$dimensions,['id'=>'action-dimension','class'=>'form-select','required'=>true,'prompt'=>'เลือกจากผลที่เผยแพร่']) ?></div><div class="col-12"><label for="issue" class="form-label">ประเด็นและสิ่งที่จะดำเนินการ</label><?= Html::textarea('issue_summary',$p['issue_summary']??'',['id'=>'issue','class'=>'form-control','rows'=>3,'required'=>true,'maxlength'=>3000]) ?></div><div class="col-12"><label for="target" class="form-label">เป้าหมายที่ตรวจสอบได้</label><?= Html::textarea('target',$p['target']??'',['id'=>'target','class'=>'form-control','required'=>true,'maxlength'=>3000]) ?></div><div class="col-md-8"><label for="owner" class="form-label">ผู้รับผิดชอบแผน</label><?= Html::dropDownList('owner_emp_id',$p['owner_emp_id']??null,$employees,['id'=>'owner','class'=>'form-select','prompt'=>'เลือกบุคลากร','required'=>true]) ?></div><div class="col-md-4"><label for="due" class="form-label">กำหนดเสร็จ</label><?= Html::input('date','due_date',$p['due_date']??'',['id'=>'due','class'=>'form-control','required'=>true]) ?></div></div><?php endif ?>
<button class="btn btn-primary mt-3">บันทึกแผน</button></div><?= Html::endForm() ?>
