<?php
use yii\helpers\Html;
$this->title='รายการบัญชีร่าง ' . $model->document_no;$this->params['breadcrumbs'][]=['label'=>'ระบบบัญชี','url'=>['/accounting/dashboard']];$this->params['breadcrumbs'][]=['label'=>'รายการบัญชีร่าง','url'=>['index']];$this->params['breadcrumbs'][]=$model->document_no;
$posted=$model->status===$model::STATUS_POSTED;
$this->beginBlock('page-title'); ?><h4 class="mb-0"><?= Html::encode($this->title) ?></h4><?php $this->endBlock();$this->beginBlock('sub-title'); ?>ปีงบประมาณ <?= Html::encode($model->fiscal_year) ?> · <?= $posted?'ผ่านรายการแล้ว':'ยังไม่ผ่านรายการ' ?><?php $this->endBlock();$this->beginBlock('page-action'); ?><div class="d-flex gap-2"><?= Html::a('กลับรายการ',['index'],['class'=>'btn btn-outline-secondary']) ?><?php if(!$posted&&Yii::$app->user->can('accountingPost'))echo Html::beginForm(['post','id'=>$model->id],'post').Html::submitButton('<i class="bi bi-check2-circle me-1"></i>ยืนยันผ่านรายการ',['class'=>'btn btn-success','data'=>['confirm'=>'ยืนยันผ่านรายการเข้าบัญชีแยกประเภท? หลังผ่านแล้วจะไม่สามารถแก้ไขบรรทัดบัญชีได้']]).Html::endForm(); ?></div><?php $this->endBlock(); ?>
<div class="alert <?= $posted?'alert-success':'alert-warning' ?>" role="status"><strong><?= $posted?'ผ่านรายการแล้ว':'สถานะร่าง' ?></strong> — <?= $posted?'บันทึกในบัญชีแยกประเภทเมื่อ '.Yii::$app->formatter->asDatetime($model->posted_at,'php:d/m/Y H:i'):'ใช้ตรวจความถูกต้องเท่านั้น ยังไม่กระทบบัญชีแยกประเภท' ?></div>
<section class="card border"><div class="card-header bg-body d-flex flex-wrap justify-content-between gap-2"><div><h5 class="mb-1"><?= Html::encode($model->description) ?></h5><span class="text-body-secondary small">วันที่ <?= Yii::$app->formatter->asDate($model->document_date,'php:d/m/Y') ?></span></div><span class="badge bg-success-subtle text-success-emphasis align-self-start">เดบิต = เครดิต</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ลำดับ</th><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th>คำอธิบาย</th><th class="text-end">เดบิต</th><th class="text-end">เครดิต</th></tr></thead><tbody>
<?php foreach($model->lines as $line): ?><tr><td><?= number_format($line->sequence) ?></td><td class="font-monospace text-nowrap"><?= Html::encode($line->account_code_snapshot) ?></td><td><?= Html::encode($line->account_name_snapshot) ?></td><td class="text-body-secondary"><?= Html::encode($line->description) ?></td><td class="text-end text-nowrap"><?= $line->debit_amount>0?number_format($line->debit_amount,2):'—' ?></td><td class="text-end text-nowrap"><?= $line->credit_amount>0?number_format($line->credit_amount,2):'—' ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr class="fw-semibold"><td colspan="4">รวม</td><td class="text-end"><?= number_format($model->total_debit,2) ?></td><td class="text-end"><?= number_format($model->total_credit,2) ?></td></tr></tfoot></table></div></section>
