<?php
use app\modules\serviceProfile\models\ServiceProfileSectionComment;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
$canReview=$access->canReview($model);$canResolve=$access->canEdit($model);
$open=array_filter($model->sectionComments,static fn($row)=>$row->status===ServiceProfileSectionComment::STATUS_OPEN);
?>
<?php if($canReview||$model->sectionComments): ?><section class="card bg-body border shadow-sm mb-3" aria-labelledby="sp-section-comments"><div class="card-header bg-body-tertiary d-flex justify-content-between align-items-center gap-2 py-3"><h2 id="sp-section-comments" class="h6 fw-semibold mb-0">ความคิดเห็นรายหัวข้อ</h2><?php if($open): ?><span class="badge bg-warning-subtle text-warning-emphasis"><?= count($open) ?> รายการรอแก้ไข</span><?php endif; ?></div>
<?php if($canReview): ?><div class="card-body border-bottom p-3 p-md-4"><form method="post" action="<?= \yii\helpers\Url::to(['add-section-comment','id'=>$model->id]) ?>"><input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->csrfToken ?>"><div class="row g-3"><div class="col-12 col-md-5"><label class="form-label fw-semibold">หัวข้อ</label><?= Html::dropDownList('section_id',null,ArrayHelper::map($model->sections,'id','title'),['class'=>'form-select','prompt'=>'เลือกหัวข้อ','required'=>true]) ?></div><div class="col-12 col-md-7"><label class="form-label fw-semibold">ความคิดเห็น</label><textarea name="comment" class="form-control" rows="2" required placeholder="ระบุสิ่งที่ควรแก้ไขหรือข้อมูลที่ควรเพิ่มเติม"></textarea></div><div class="col-12 text-end"><button class="btn btn-primary" type="submit">บันทึกความคิดเห็น</button></div></div></form></div><?php endif; ?>
<div class="list-group list-group-flush"><?php foreach($model->sectionComments as $comment): ?><article class="list-group-item p-3"><div class="d-flex flex-column flex-md-row justify-content-between gap-3"><div><div class="fw-semibold"><?= Html::encode($comment->section?->title??'หัวข้อที่ถูกลบ') ?></div><p class="mb-1"><?= nl2br(Html::encode($comment->comment)) ?></p><div class="small text-body-secondary"><?= Html::encode($comment->reviewer?->fullname()??'ผู้แทนคุณภาพ') ?> · <?= Yii::$app->formatter->asDatetime($comment->created_at) ?></div></div><div class="d-flex flex-wrap align-items-start gap-2"><?php if($comment->status===ServiceProfileSectionComment::STATUS_RESOLVED): ?><span class="badge bg-success-subtle text-success-emphasis">แก้ไขแล้ว</span><?php elseif($canResolve): ?><?php if($comment->section): ?><?= Html::a('<i class="bi bi-pencil me-1" aria-hidden="true"></i> แก้ไขหัวข้อนี้',['update-section','id'=>$comment->section_id],['class'=>'btn btn-outline-primary']) ?><?php endif; ?><?= Html::a('<i class="bi bi-check-lg me-1" aria-hidden="true"></i> ยืนยันว่าแก้แล้ว',['resolve-section-comment','id'=>$comment->id],['class'=>'btn btn-outline-success','data-method'=>'post','data-confirm'=>'ยืนยันว่าได้แก้ไขความคิดเห็นรายการนี้เรียบร้อยแล้ว?']) ?><?php else: ?><span class="badge bg-warning-subtle text-warning-emphasis">รอแก้ไข</span><?php endif; ?></div></div></article><?php endforeach; ?></div></section><?php endif; ?>
