<?php
use yii\helpers\Html;
$this->title='เปรียบเทียบ Service Profile';
$labels=['added'=>'เพิ่มใหม่','changed'=>'มีการแก้ไข','removed'=>'นำออก','unchanged'=>'ไม่เปลี่ยนแปลง'];
$classes=['added'=>'bg-success-subtle text-success-emphasis','changed'=>'bg-warning-subtle text-warning-emphasis','removed'=>'bg-danger-subtle text-danger-emphasis','unchanged'=>'bg-body-secondary text-body-secondary'];
?>
<?php $this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('sub-title'); ?><?= Html::encode($model->owner_name_snapshot.' · Revision '.$previous->revision_no.' → '.$model->revision_no) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('page-action'); ?><?= Html::a('<i class="bi bi-arrow-left me-1"></i> กลับไป Service Profile',['view','id'=>$model->id],['class'=>'btn btn-outline-secondary']) ?><?php $this->endBlock(); ?>
<div class="row g-3 mb-3"><?php foreach(['added','changed','removed','unchanged'] as $status): ?><div class="col-6 col-xl-3"><div class="card bg-body border shadow-sm h-100"><div class="card-body p-3"><div class="small text-body-secondary"><?= $labels[$status] ?></div><div class="h3 fw-bold mb-0"><?= (int)$comparison['summary'][$status] ?></div></div></div></div><?php endforeach; ?></div>
<section class="card bg-body border shadow-sm" aria-labelledby="sp-compare-heading"><div class="card-header bg-body-tertiary py-3"><h2 id="sp-compare-heading" class="h5 fw-semibold mb-1">รายละเอียดการเปลี่ยนแปลง</h2><p class="small text-body-secondary mb-0">เปรียบเทียบชื่อ รูปแบบข้อมูล การบังคับกรอก และเนื้อหาในแต่ละหัวข้อ</p></div><div class="list-group list-group-flush"><?php foreach($comparison['rows'] as $row): ?><article class="list-group-item p-3 p-md-4"><div class="d-flex flex-column flex-md-row justify-content-between gap-2"><div><div class="fw-semibold"><?= Html::encode($row['title']) ?></div><div class="small text-body-secondary">รหัส <?= Html::encode($row['code']) ?><?php if($row['current']&&$row['previous']&&$row['current']->block_type!==$row['previous']->block_type): ?> · รูปแบบ <?= Html::encode($row['previous']->block_type) ?> → <?= Html::encode($row['current']->block_type) ?><?php endif; ?></div></div><span class="badge <?= $classes[$row['status']] ?> align-self-start"><?= $labels[$row['status']] ?></span></div><?php if($row['status']==='changed'&&$row['current']&&$row['previous']): ?><div class="row g-3 mt-1"><div class="col-12 col-lg-6"><div class="small fw-semibold text-body-secondary mb-1">Revision <?= (int)$previous->revision_no ?></div><div class="border rounded-3 p-3 h-100"><?= $row['previous']->content?:'<span class="text-body-secondary">ไม่มีข้อความ</span>' ?></div></div><div class="col-12 col-lg-6"><div class="small fw-semibold text-body-secondary mb-1">Revision <?= (int)$model->revision_no ?></div><div class="border rounded-3 p-3 h-100"><?= $row['current']->content?:'<span class="text-body-secondary">ไม่มีข้อความ</span>' ?></div></div></div><?php endif; ?></article><?php endforeach; ?></div></section>
