<?php
use app\components\widgets\DataSummaryWidget;
use app\modules\serviceProfile\models\ServiceProfile;
use yii\helpers\Html;
$this->title = 'Service Profile';
$labels = ServiceProfile::statusLabels();
$badges = ['draft'=>'bg-secondary-subtle text-secondary-emphasis','returned'=>'bg-danger-subtle text-danger-emphasis','review_pending'=>'bg-info-subtle text-info-emphasis','approval_pending'=>'bg-warning-subtle text-warning-emphasis','acknowledgement_pending'=>'bg-warning-subtle text-warning-emphasis','active'=>'bg-success-subtle text-success-emphasis','retired'=>'bg-body-secondary text-body-secondary','cancelled'=>'bg-danger-subtle text-danger-emphasis'];
?>
<?php $this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('page-action'); ?><?= $this->render('@app/modules/serviceProfile/menu', ['active'=>'profile']) ?><?php $this->endBlock(); ?>
<nav class="d-flex flex-wrap gap-2 mb-3" aria-label="ขอบเขตรายการ Service Profile"><?= Html::a('<i class="bi bi-collection me-1"></i> รายการทั้งหมด',['index'],['class'=>'btn '.($scope!=='action'?'btn-primary':'btn-outline-primary')]) ?><?= Html::a('<i class="bi bi-inbox me-1"></i> งานที่รอดำเนินการ <span class="badge '.($scope==='action'?'text-bg-light':'text-bg-primary').' ms-1">'.(int)$actionCount.'</span>',['index','scope'=>'action'],['class'=>'btn '.($scope==='action'?'btn-primary':'btn-outline-primary')]) ?></nav>
<form method="get" class="card bg-body border shadow-sm mb-3"><?= Html::hiddenInput('scope',$scope) ?><div class="card-body"><div class="row g-3 align-items-end"><div class="col-12 col-sm-5"><label class="form-label fw-semibold">ปีงบประมาณ</label><?= Html::textInput('fiscal_year', $year ?: '', ['class'=>'form-control','type'=>'number','placeholder'=>'ทุกปี']) ?></div><div class="col-12 col-sm-4"><label class="form-label fw-semibold">สถานะ</label><?= Html::dropDownList('status',$status,$labels,['class'=>'form-select','prompt'=>'ทุกสถานะ']) ?></div><div class="col-12 col-sm-3 d-flex gap-2"><?= Html::submitButton('ค้นหา',['class'=>'btn btn-primary flex-grow-1']) ?><?= Html::a('ล้าง',['index','scope'=>$scope],['class'=>'btn btn-outline-secondary']) ?></div></div></div></form>
<section class="card bg-body border shadow-sm" aria-labelledby="sp-list-heading">
<div class="card-header bg-body-tertiary d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3 py-3"><div><h2 id="sp-list-heading" class="h5 fw-semibold mb-1"><?= $scope==='action'?'งานที่รอดำเนินการ':'รายการทั้งหมด' ?></h2><p class="small text-body-secondary mb-0"><?= $scope==='action'?'เอกสารที่รอให้คุณตรวจ เห็นชอบ อนุมัติ รับทราบ หรือแก้ไข':'ฉบับร่าง ฉบับที่กำลังพิจารณา และประวัติของหน่วยงาน' ?></p></div><?php if($canCreate): ?><?= Html::a('<i class="bi bi-plus-lg me-1"></i> สร้างฉบับใหม่',['create'],['class'=>'btn btn-primary']) ?><?php endif; ?></div>
<div class="card-body p-0"><div class="d-none d-lg-block"><table class="table align-middle mb-0"><thead><tr><th>หน่วยงาน</th><th class="text-end">ปีงบประมาณ</th><th class="text-center">Revision</th><th>สถานะ</th><th>แก้ไขล่าสุด</th><th class="text-end">จัดการ</th></tr></thead><tbody>
<?php foreach($dataProvider->getModels() as $model): ?><tr><td class="fw-semibold"><?= Html::encode($model->owner_name_snapshot) ?></td><td class="text-end font-monospace"><?= (int)$model->fiscal_year ?></td><td class="text-center font-monospace"><?= (int)$model->revision_no ?></td><td><span class="badge <?= $badges[$model->status]??'bg-body-secondary text-body-secondary' ?>"><?= Html::encode($labels[$model->status]??$model->status) ?></span></td><td><span class="small text-body-secondary"><?= Yii::$app->formatter->asDatetime($model->updated_at) ?></span></td><td class="text-end"><?= Html::a('เปิดดู',['view','id'=>$model->id],['class'=>'btn btn-sm btn-outline-primary']) ?></td></tr><?php endforeach; ?>
<?php if($dataProvider->getCount()===0): ?><tr><td colspan="6" class="text-center py-5"><div class="fw-semibold"><?= $scope==='action'?'ไม่มีงานที่รอดำเนินการ':'ยังไม่มี Service Profile' ?></div><div class="small text-body-secondary mt-1"><?= $scope==='action'?'เมื่อมีเอกสารถึงคิวของคุณ ระบบจะแสดงในรายการนี้':'เริ่มสร้างฉบับแรกจาก Template ของหน่วยงาน' ?></div></td></tr><?php endif; ?>
</tbody></table></div>
<ul class="list-group list-group-flush d-lg-none" role="list"><?php foreach($dataProvider->getModels() as $model): ?><li class="list-group-item p-3"><div class="d-flex justify-content-between gap-3"><div><div class="fw-semibold"><?= Html::encode($model->owner_name_snapshot) ?></div><div class="small text-body-secondary">ปี <?= (int)$model->fiscal_year ?> · Revision <?= (int)$model->revision_no ?></div><span class="badge mt-2 <?= $badges[$model->status]??'bg-body-secondary text-body-secondary' ?>"><?= Html::encode($labels[$model->status]??$model->status) ?></span></div><?= Html::a('เปิดดู',['view','id'=>$model->id],['class'=>'btn btn-outline-primary align-self-start']) ?></div></li><?php endforeach; ?></ul></div>
<div class="card-footer bg-body border-top py-3 px-3 px-md-4"><?= DataSummaryWidget::widget(['dataProvider'=>$dataProvider]) ?></div></section>
