<?php
use app\modules\serviceProfile\models\ServiceProfile;
use app\modules\serviceProfile\models\ServiceProfileApproval;
use app\modules\serviceProfile\services\SectionDefinitionService;
use app\modules\jd\components\RichText;
use yii\helpers\Html;
$this->title='Service Profile ปีงบประมาณ '.$model->fiscal_year;
$labels=ServiceProfile::statusLabels();
$stageLabels=[ServiceProfileApproval::STAGE_QUALITY=>'ผู้แทนคุณภาพเห็นชอบ',ServiceProfileApproval::STAGE_DIRECTOR=>'ผู้อำนวยการอนุมัติ',ServiceProfileApproval::STAGE_HEAD=>'หัวหน้าหน่วยงานรับทราบ'];
$stageStatus=['waiting'=>'ยังไม่ถึงขั้นตอน','pending'=>'รอดำเนินการ','passed'=>'ดำเนินการแล้ว','returned'=>'ส่งกลับแก้ไข'];
$canEdit=$access->canEdit($model); $canSubmit=$access->canSubmit($model)&&($readiness['ready']??true); $canReview=$access->canReview($model); $isLead=$access->isLeadReviewer($model);
$canApprove=$access->canActStage($model,ServiceProfileApproval::STAGE_DIRECTOR); $canAcknowledge=$access->canActStage($model,ServiceProfileApproval::STAGE_HEAD);
$attachmentSection = null;
$firstEditableSection = null;
foreach ($model->sections as $profileSection) {
    if ($profileSection->block_type === 'attachment') {
        $attachmentSection = $profileSection;
    } elseif ($firstEditableSection === null) {
        $firstEditableSection = $profileSection;
    }
}
$this->registerCss(<<<CSS
.sp-richtext{overflow-wrap:anywhere}
.sp-richtext table{width:100%;margin-bottom:1rem;border-collapse:collapse;vertical-align:top}
.sp-richtext th,.sp-richtext td{padding:.5rem .65rem;border:1px solid var(--bs-border-color);vertical-align:top}
.sp-richtext th{font-weight:600;background:var(--bs-tertiary-bg)}
.sp-richtext caption{padding:.5rem 0;color:var(--bs-secondary-color);text-align:start}
.sp-richtext ul,.sp-richtext ol{padding-inline-start:1.5rem}
CSS);
?>
<?php $this->beginBlock('page-title'); ?><?= Html::encode($this->title) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('sub-title'); ?><?= Html::encode($model->owner_name_snapshot.' · Revision '.$model->revision_no) ?><?php $this->endBlock(); ?>
<?php $this->beginBlock('page-action'); ?><div class="d-flex flex-wrap gap-2"><?= Html::a('<i class="bi bi-arrow-left me-1"></i> รายการทั้งหมด',['index'],['class'=>'btn btn-outline-secondary']) ?><?= Html::a('<i class="bi bi-inbox me-1"></i> งานที่รอดำเนินการ <span class="badge text-bg-primary ms-1">'.(int)$actionCount.'</span>',['index','scope'=>'action'],['class'=>'btn btn-outline-primary','aria-label'=>'งานที่รอดำเนินการ '.(int)$actionCount.' รายการ']) ?><?= Html::a('<i class="bi bi-clock-history me-1"></i> ประวัติการแก้ไข',['history','id'=>$model->id],['class'=>'btn btn-outline-secondary']) ?><?= Html::a('<i class="bi bi-file-earmark-pdf me-1"></i> PDF',['pdf','id'=>$model->id],['class'=>'btn btn-outline-secondary','target'=>'_blank']) ?><?php if($model->supersedes_id): ?><?= Html::a('<i class="bi bi-files me-1"></i> เปรียบเทียบ Revision',['compare','id'=>$model->id],['class'=>'btn btn-outline-secondary']) ?><?php endif; ?><?php if($canEdit && $firstEditableSection): ?><?= Html::a('<i class="bi bi-pencil me-1"></i> แก้ไขเอกสาร',['update-section','id'=>$firstEditableSection->id],['class'=>'btn btn-primary']) ?><?= Html::a('<i class="bi bi-people me-1"></i> คณะผู้จัดทำ',['authors','id'=>$model->id],['class'=>'btn btn-outline-primary']) ?><?php endif; ?><?php if($canSubmit): ?><?= Html::a('<i class="bi bi-send me-1"></i> ส่งพิจารณา',['submit','id'=>$model->id],['class'=>'btn btn-primary','data-method'=>'post','data-confirm'=>'ยืนยันส่งเอกสารเข้าสู่กระบวนการพิจารณา?']) ?><?php endif; ?></div><?php $this->endBlock(); ?>
<?php if($model->status===ServiceProfile::STATUS_RETURNED && $canEdit): ?><div class="alert alert-warning d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3" role="status"><div><div class="fw-semibold">เอกสารถูกส่งกลับให้แก้ไข</div><div class="small">ตรวจความคิดเห็น แก้ไขหัวข้อที่เกี่ยวข้อง แล้วส่งพิจารณาอีกครั้ง</div></div><?php if($firstEditableSection): ?><?= Html::a('เริ่มแก้ไขเอกสาร',['update-section','id'=>$firstEditableSection->id],['class'=>'btn btn-warning flex-shrink-0']) ?><?php endif; ?></div><?php endif; ?>
<?= $this->render('_section_comments', ['model'=>$model,'access'=>$access]) ?>
<?php if(in_array($model->status,[ServiceProfile::STATUS_DRAFT,ServiceProfile::STATUS_RETURNED],true)): ?><?= $this->render('_readiness', ['readiness'=>$readiness]) ?><?php endif; ?>
<div class="row g-3 mb-3"><div class="col-12 col-xl-8"><div class="card bg-body border shadow-sm h-100"><div class="card-body p-3 p-md-4"><div class="d-flex flex-column flex-sm-row justify-content-between gap-3"><div><div class="small text-body-secondary">สถานะปัจจุบัน</div><div class="h5 fw-semibold mb-1"><?= Html::encode($labels[$model->status]??$model->status) ?></div><div class="small text-body-secondary">Template Revision <?= (int)$model->template_revision_snapshot ?> · แก้ไขล่าสุด <?= Yii::$app->formatter->asDatetime($model->updated_at) ?></div></div><div class="text-sm-end"><div class="small text-body-secondary">ความครบถ้วน</div><?php $required=array_filter($model->sections,fn($s)=>$s->is_required);$complete=array_filter($required,fn($s)=>$s->isComplete()); ?><div class="h5 fw-semibold mb-1"><?= count($complete) ?>/<?= count($required) ?> หัวข้อบังคับ</div></div></div></div></div></div><div class="col-12 col-xl-4"><div class="card bg-body border shadow-sm h-100"><div class="card-body p-3"><h2 class="h6 fw-semibold">คณะผู้จัดทำ</h2><ul class="list-unstyled mb-0"><?php foreach($model->authors as $author): ?><li class="py-1 d-flex justify-content-between gap-2"><span><?= Html::encode($author->employee?->fullname()??('บุคลากร #'.$author->employee_id)) ?></span><?php if($author->role==='coordinator'): ?><span class="badge bg-primary-subtle text-primary-emphasis">ผู้ประสานหลัก</span><?php endif; ?></li><?php endforeach; ?></ul></div></div></div></div>
<?php if($model->approvals): ?><section class="card bg-body border shadow-sm mb-3" aria-labelledby="sp-workflow"><div class="card-header bg-body-tertiary py-3"><h2 id="sp-workflow" class="h6 fw-semibold mb-0">ลำดับการพิจารณา</h2></div><div class="list-group list-group-flush"><?php foreach($model->approvals as $row): ?><div class="list-group-item d-flex justify-content-between align-items-start gap-3 py-3"><div><div class="fw-semibold"><?= Html::encode($stageLabels[$row->stage]??$row->stage) ?></div><div class="small text-body-secondary"><?= Html::encode($row->employee_name_snapshot) ?><?php if($row->acted_at): ?> · <?= Yii::$app->formatter->asDatetime($row->acted_at) ?><?php endif; ?></div><?php if($row->comment): ?><div class="small mt-1"><?= Html::encode($row->comment) ?></div><?php endif; ?></div><span class="badge <?= $row->status==='passed'?'bg-success-subtle text-success-emphasis':($row->status==='pending'?'bg-warning-subtle text-warning-emphasis':'bg-body-secondary text-body-secondary') ?>"><?= Html::encode($stageStatus[$row->status]??$row->status) ?></span></div><?php endforeach; ?></div></section><?php endif; ?>
<?php if($canReview||$canApprove||$canAcknowledge): ?><section class="card bg-body border shadow-sm mb-3"><div class="card-body p-3 p-md-4"><h2 class="h6 fw-semibold mb-3">ดำเนินการกับเอกสาร</h2><form method="post" action="<?= $canReview?\yii\helpers\Url::to(['review','id'=>$model->id]):($canApprove?\yii\helpers\Url::to(['approve','id'=>$model->id]):\yii\helpers\Url::to(['acknowledge','id'=>$model->id])) ?>"><input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->csrfToken ?>"><div class="mb-3"><label class="form-label fw-semibold">ความคิดเห็น</label><textarea name="comment" class="form-control" rows="3" placeholder="ระบุความคิดเห็นหรือข้อเสนอแนะ"></textarea></div><div class="d-flex flex-wrap justify-content-end gap-2"><?php if($canReview||$canApprove): ?><button type="submit" formaction="<?= \yii\helpers\Url::to(['return','id'=>$model->id]) ?>" class="btn btn-outline-danger">ส่งกลับแก้ไข</button><?php endif; ?><?php if($canReview): ?><button type="submit" name="decision" value="commented" class="btn btn-outline-primary">บันทึกความคิดเห็น</button><?php if($isLead): ?><button type="submit" name="decision" value="endorsed" class="btn btn-primary">เห็นชอบและส่งต่อ</button><?php endif; ?><?php elseif($canApprove): ?><button type="submit" class="btn btn-primary">อนุมัติเอกสาร</button><?php else: ?><button type="submit" class="btn btn-success">รับทราบและประกาศใช้</button><?php endif; ?></div></form></div></section><?php endif; ?>
<div class="d-flex flex-column gap-3"><?php foreach($model->sections as $section): if($section->block_type === 'attachment') continue; $columns=SectionDefinitionService::columns($section->block_type);$items=(array)($section->getData()['items']??[]); ?><section id="section-<?= $section->id ?>" class="card bg-body border shadow-sm"><div class="card-header bg-body-tertiary d-flex justify-content-between align-items-start gap-3 py-3"><div><h2 class="h6 fw-semibold mb-1"><?= Html::encode($section->title) ?><?php if($section->is_required): ?><span class="text-danger" aria-label="บังคับกรอก"> *</span><?php endif; ?></h2><div class="small text-body-secondary"><?= $section->isComplete()?'บันทึกข้อมูลแล้ว':'ยังไม่มีข้อมูล' ?></div></div><?php if($canEdit): ?><?= Html::a('<i class="bi bi-pencil me-1"></i> แก้ไข',['update-section','id'=>$section->id],['class'=>'btn btn-sm btn-outline-primary']) ?><?php endif; ?></div><div class="card-body p-3 p-md-4"><?php if($section->content): ?><div class="sp-richtext mb-3"><?= RichText::render($section->content) ?></div><?php endif; ?><?php if($columns&&$items): ?><div class="d-none d-lg-block"><table class="table table-bordered align-middle mb-0"><thead><tr><?php foreach($columns as $label): ?><th><?= Html::encode($label) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($items as $item): ?><tr><?php foreach($columns as $key=>$label): ?><td class="sp-richtext"><?= RichText::render((string)($item[$key]??'')) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><div class="d-lg-none d-flex flex-column gap-3"><?php foreach($items as $item): ?><dl class="border rounded-3 p-3 mb-0"><?php foreach($columns as $key=>$label): ?><dt class="small text-body-secondary"><?= Html::encode($label) ?></dt><dd class="sp-richtext"><?= RichText::render((string)($item[$key]??'')) ?: '—' ?></dd><?php endforeach; ?></dl><?php endforeach; ?></div><?php elseif(!$section->content): ?><p class="text-body-secondary mb-0">ยังไม่มีข้อมูลในหัวข้อนี้</p><?php endif; ?></div></section><?php endforeach; ?>
<section id="<?= $attachmentSection ? 'section-' . $attachmentSection->id : 'attachments' ?>" class="card bg-body border shadow-sm"><div class="card-header bg-body-tertiary py-3"><h2 class="h6 fw-semibold mb-0"><?= Html::encode($attachmentSection?->title ?? 'เอกสารแนบ') ?></h2></div><div class="card-body p-3 p-md-4"><?= $model->fileUpload(!$canEdit) ?></div></section></div>
