
services:
  php:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build:
      context: .
    environment:
      PHP_POST_MAX_SIZE: 16M
      PHP_UPLOAD_MAX_FILESIZE: 16M
    ports:
       - '${HOS_CODE}:80'
    volumes:
      - ./fileupload:/app/modules/filemanager/fileupload
    links:
      - mysqlDB:db
    environment:
      - YII_ENV=pro
    env_file:
      - ./.env

  mysqlDB:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}_db
    hostname: mysqldboffice
    volumes:
      - ./database/mysql8.0/data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
    command:
      [
        'mysqld',
        '--max-allowed-packet=64M',
        '--wait_timeout=28800',
        '--interactive_timeout=28800',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
      ]
  phpmyadmin_mysql:
    image: phpmyadmin
    container_name: ${CONTAINER_NAME}_pma
    restart: always
    links:
      - mysqlDB:db
    ports:
      - ${PAM_PORT}:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mysqlDB
      UPLOAD_LIMIT: 300M