services:
  certbot:
    image: certbot/certbot
    # volumes:
    #   - ./certbot/www:/var/www/certbot
    #   - ./certbot/conf:/etc/letsencrypt
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email patjawat@gmail.com -d dansai.hospital-erp.org
    restart: unless-stopped
    networks:
      web-network:
        aliases:
          - certbot
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    # restart: always
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      # - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certbot/www:/var/www/certbot
      # - ./certbot/conf:/etc/letsencrypt
    networks:
      web-network:
        aliases:
          - nginx_proxy


  mysqlDB:
    image: mysql:8.0
    container_name: mysql_db
    hostname: mysqldboffice
    networks:
      web-network:
        aliases:
          - mysqlDB
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql8.0/data:/var/lib/mysql
    command: [ "mysqld", "--innodb-buffer-pool-size=1G", "--innodb-log-file-size=256M", "--innodb-flush-log-at-trx-commit=2", "--innodb-flush-method=O_DIRECT", "--tmp_table_size=64M", "--max-heap-table-size=64M", "--max-connections=200", "--table-open-cache=400", "--max-allowed-packet=64M", "--wait_timeout=28800", "--interactive_timeout=28800", "--character-set-server=utf8", "--collation-server=utf8_general_ci", "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" ]

  phpmyadmin_mysql:
    image: phpmyadmin
    container_name: phpmyadmin_pma
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysqlDB
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    networks:
      web-network:
        aliases:
          - phpmyadmin_pma

  app:
    image: ${APP_IMAGE}
    container_name: app-erp
    platform: linux/amd64
    volumes:
      - ../fileupload:/app/modules/filemanager/fileupload
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:80"
    networks:
      web-network:
        aliases:
          - app-erp


networks:
  web-network:
    driver: bridge
