<?php
$this->registerCss(<<<CSS
.idp-shell{--idp-ink:#212529;--idp-muted:#667085;--idp-line:rgba(15,23,42,.1);--idp-soft:#f7f9fc;--idp-blue:#0d6efd;--idp-green:#198754;--idp-amber:#b45309;--idp-red:#b42318;color:var(--idp-ink)}
.idp-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:1rem}.idp-head h1{font-size:1.25rem;font-weight:700;margin:0 0 .25rem}.idp-head p{color:var(--idp-muted);margin:0;max-width:68ch}
.idp-surface{background:#fff;border:1px solid var(--idp-line);border-radius:10px;box-shadow:0 1px 2px rgba(15,23,42,.04);overflow:hidden}
.idp-actions{display:grid;grid-template-columns:repeat(3,1fr);border-bottom:1px solid var(--idp-line)}
.idp-action{display:flex;align-items:center;gap:.75rem;padding:1rem;border-right:1px solid var(--idp-line)}.idp-action:last-child{border-right:0}
.idp-action__icon{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:#e7f1ff;color:#0a58ca;flex:none}.idp-action__icon.is-warning{background:#fff4e5;color:var(--idp-amber)}.idp-action__icon.is-danger{background:#fdecec;color:var(--idp-red)}
.idp-action__label{font-size:.76rem;color:var(--idp-muted)}.idp-action__value{font-size:1.15rem;font-weight:700;font-variant-numeric:tabular-nums}
.idp-toolbar{display:flex;align-items:end;gap:.75rem;padding:1rem;border-bottom:1px solid var(--idp-line);flex-wrap:wrap}.idp-toolbar label{display:block;font-size:.74rem;font-weight:600;margin-bottom:.25rem;color:#475569}
.idp-table{margin:0}.idp-table th{padding:.65rem .8rem;background:var(--idp-soft);font-size:.76rem;font-weight:600;color:#475569;border-color:var(--idp-line)}.idp-table td{padding:.7rem .8rem;font-size:.86rem;vertical-align:middle;border-color:var(--idp-line)}
.idp-status{display:inline-flex;padding:.22rem .55rem;border-radius:999px;background:#eef2f7;color:#475569;font-size:.72rem;font-weight:600}.idp-status--submitted,.idp-status--revision{background:#fff4e5;color:var(--idp-amber)}.idp-status--approved,.idp-status--in_progress{background:#e7f1ff;color:#0a58ca}.idp-status--assessment,.idp-status--completed{background:#e8f5ee;color:var(--idp-green)}.idp-status--cancelled{background:#fdecec;color:var(--idp-red)}
.idp-progress{height:6px;background:#e9ecef;border-radius:999px;overflow:hidden}.idp-progress span{display:block;height:100%;background:var(--idp-blue);border-radius:inherit}
.idp-cycle{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem;border-bottom:1px solid var(--idp-line)}.idp-cycle h2{font-size:1rem;margin:0}.idp-cycle p{font-size:.78rem;color:var(--idp-muted);margin:.2rem 0 0}
.idp-steps{display:grid;grid-template-columns:repeat(4,1fr);padding:1rem;border-bottom:1px solid var(--idp-line)}.idp-step{position:relative;text-align:center;color:#64748b;font-size:.72rem}.idp-step:not(:last-child)::after{position:absolute;top:13px;left:calc(50% + 18px);right:calc(-50% + 18px);height:1px;background:#cbd5e1;content:""}.idp-step__num{position:relative;z-index:1;display:grid;place-items:center;width:28px;height:28px;margin:0 auto .4rem;border-radius:50%;background:#eef2f7;color:#475569;font-weight:700}.idp-step.is-current{color:#0a58ca;font-weight:600}.idp-step.is-current .idp-step__num,.idp-step.is-done .idp-step__num{background:var(--idp-blue);color:#fff}
.idp-goals{padding:0 1rem}.idp-goal{padding:1rem 0;border-bottom:1px solid var(--idp-line)}.idp-goal:last-child{border-bottom:0}.idp-goal__head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.idp-goal__title{display:flex;gap:.65rem;font-weight:700}.idp-goal__num{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#e7f1ff;color:#0a58ca;flex:none}.idp-goal__copy{padding-left:2.65rem;color:var(--idp-muted);font-size:.82rem;max-width:70ch}.idp-activity{display:grid;grid-template-columns:minmax(0,1fr) 120px auto;gap:.75rem;align-items:center;margin-left:2.65rem;padding:.65rem 0;border-top:1px dashed rgba(15,23,42,.1);font-size:.82rem}
.idp-empty{padding:3rem 1.25rem;text-align:center}.idp-empty h2{font-size:1.05rem}.idp-empty p{color:var(--idp-muted);max-width:55ch;margin:.35rem auto 1rem}
.idp-review{padding:1rem;border-top:1px solid var(--idp-line);background:var(--idp-soft)}
@media(max-width:767.98px){.idp-actions{grid-template-columns:1fr}.idp-action{border-right:0;border-bottom:1px solid var(--idp-line)}.idp-action:last-child{border-bottom:0}.idp-head{flex-direction:column}.idp-head .btn{width:100%}.idp-toolbar>*{width:100%}.idp-steps{overflow-x:auto;grid-template-columns:repeat(4,minmax(110px,1fr))}.idp-activity{grid-template-columns:1fr;margin-left:0}.idp-goal__copy{padding-left:0;margin-top:.5rem}.idp-table-wrap{overflow-x:auto}}
@media(prefers-reduced-motion:reduce){.idp-shell *{transition:none!important;scroll-behavior:auto!important}}
CSS);
?>
