name: Push To DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Image
      run: docker build . --file Dockerfile --tag patjawat/erp:latest
    - name: Push Image
      run: docker push patjawat/erp:latest
